// This file is autogenerated. Do not edit by hand.
// Edit the generator script instead.
// clang-format off

#pragma once

#include "CoreMinimal.h"
#include <utility>

#include "soa_vectors.generated.h"

template <typename T>
struct TVectors2View
{
    using size_type = TArrayView<T>::SizeType;

    TArrayView<T> xs;
    TArrayView<T> ys;

    template <typename TFunc>
    auto apply_arrays(TFunc&& func) -> decltype(auto)
    {
        return std::forward<TFunc>(func)(xs, ys);
    }

    template <typename TFunc>
    auto apply_arrays(TFunc&& func) const -> decltype(auto)
    {
        return std::forward<TFunc>(func)(xs, ys);
    }

    auto num() const -> size_type
    {
        return xs.Num();
    }
};
template <typename T>
struct TVectors3View
{
    using size_type = TArrayView<T>::SizeType;

    TArrayView<T> xs;
    TArrayView<T> ys;
    TArrayView<T> zs;

    template <typename TFunc>
    auto apply_arrays(TFunc&& func) -> decltype(auto)
    {
        return std::forward<TFunc>(func)(xs, ys, zs);
    }

    template <typename TFunc>
    auto apply_arrays(TFunc&& func) const -> decltype(auto)
    {
        return std::forward<TFunc>(func)(xs, ys, zs);
    }

    auto num() const -> size_type
    {
        return xs.Num();
    }
};

USTRUCT()
struct FVectors2f
{
    GENERATED_BODY()

    using value_type = float;
    using size_type = TArray<value_type>::SizeType;
    using View = TVectors2View<value_type>;
    using ConstView = TVectors2View<value_type const>;

    UPROPERTY()
    TArray<float> xs;
    UPROPERTY()
    TArray<float> ys;

    auto get_view() -> View
    {
        return View{xs, ys};
    }

    auto get_view() const -> ConstView
    {
        return ConstView{xs, ys};
    }

    auto get_const_view() const -> ConstView
    {
        return ConstView{xs, ys};
    }

    template <typename TFunc>
    auto apply_arrays(TFunc&& func) -> decltype(auto)
    {
        return std::forward<TFunc>(func)(xs, ys);
    }

    template <typename TFunc>
    auto apply_arrays(TFunc&& func) const -> decltype(auto)
    {
        return std::forward<TFunc>(func)(xs, ys);
    }

    auto num() const -> size_type
    {
        return xs.Num();
    }

    auto is_empty() const -> bool
    {
        return num() == 0;
    }

    auto reset() -> void
    {
        xs.Reset();
        ys.Reset();
    }

    auto empty() -> void
    {
        xs.Empty();
        ys.Empty();
    }

    auto reserve(size_type const count) -> void
    {
        xs.Reserve(count);
        ys.Reserve(count);
    }

    auto set_num_uninitialized(size_type const count) -> void
    {
        xs.SetNumUninitialized(count);
        ys.SetNumUninitialized(count);
    }

    auto add_uninitialized(size_type const count) -> void
    {
        xs.AddUninitialized(count);
        ys.AddUninitialized(count);
    }
};

USTRUCT()
struct FVectors2d
{
    GENERATED_BODY()

    using value_type = double;
    using size_type = TArray<value_type>::SizeType;
    using View = TVectors2View<value_type>;
    using ConstView = TVectors2View<value_type const>;

    UPROPERTY()
    TArray<double> xs;
    UPROPERTY()
    TArray<double> ys;

    auto get_view() -> View
    {
        return View{xs, ys};
    }

    auto get_view() const -> ConstView
    {
        return ConstView{xs, ys};
    }

    auto get_const_view() const -> ConstView
    {
        return ConstView{xs, ys};
    }

    template <typename TFunc>
    auto apply_arrays(TFunc&& func) -> decltype(auto)
    {
        return std::forward<TFunc>(func)(xs, ys);
    }

    template <typename TFunc>
    auto apply_arrays(TFunc&& func) const -> decltype(auto)
    {
        return std::forward<TFunc>(func)(xs, ys);
    }

    auto num() const -> size_type
    {
        return xs.Num();
    }

    auto is_empty() const -> bool
    {
        return num() == 0;
    }

    auto reset() -> void
    {
        xs.Reset();
        ys.Reset();
    }

    auto empty() -> void
    {
        xs.Empty();
        ys.Empty();
    }

    auto reserve(size_type const count) -> void
    {
        xs.Reserve(count);
        ys.Reserve(count);
    }

    auto set_num_uninitialized(size_type const count) -> void
    {
        xs.SetNumUninitialized(count);
        ys.SetNumUninitialized(count);
    }

    auto add_uninitialized(size_type const count) -> void
    {
        xs.AddUninitialized(count);
        ys.AddUninitialized(count);
    }
};

USTRUCT()
struct FVectors2i32
{
    GENERATED_BODY()

    using value_type = int32;
    using size_type = TArray<value_type>::SizeType;
    using View = TVectors2View<value_type>;
    using ConstView = TVectors2View<value_type const>;

    UPROPERTY()
    TArray<int32> xs;
    UPROPERTY()
    TArray<int32> ys;

    auto get_view() -> View
    {
        return View{xs, ys};
    }

    auto get_view() const -> ConstView
    {
        return ConstView{xs, ys};
    }

    auto get_const_view() const -> ConstView
    {
        return ConstView{xs, ys};
    }

    template <typename TFunc>
    auto apply_arrays(TFunc&& func) -> decltype(auto)
    {
        return std::forward<TFunc>(func)(xs, ys);
    }

    template <typename TFunc>
    auto apply_arrays(TFunc&& func) const -> decltype(auto)
    {
        return std::forward<TFunc>(func)(xs, ys);
    }

    auto num() const -> size_type
    {
        return xs.Num();
    }

    auto is_empty() const -> bool
    {
        return num() == 0;
    }

    auto reset() -> void
    {
        xs.Reset();
        ys.Reset();
    }

    auto empty() -> void
    {
        xs.Empty();
        ys.Empty();
    }

    auto reserve(size_type const count) -> void
    {
        xs.Reserve(count);
        ys.Reserve(count);
    }

    auto set_num_uninitialized(size_type const count) -> void
    {
        xs.SetNumUninitialized(count);
        ys.SetNumUninitialized(count);
    }

    auto add_uninitialized(size_type const count) -> void
    {
        xs.AddUninitialized(count);
        ys.AddUninitialized(count);
    }
};

USTRUCT()
struct FVectors2u32
{
    GENERATED_BODY()

    using value_type = uint32;
    using size_type = TArray<value_type>::SizeType;
    using View = TVectors2View<value_type>;
    using ConstView = TVectors2View<value_type const>;

    UPROPERTY()
    TArray<uint32> xs;
    UPROPERTY()
    TArray<uint32> ys;

    auto get_view() -> View
    {
        return View{xs, ys};
    }

    auto get_view() const -> ConstView
    {
        return ConstView{xs, ys};
    }

    auto get_const_view() const -> ConstView
    {
        return ConstView{xs, ys};
    }

    template <typename TFunc>
    auto apply_arrays(TFunc&& func) -> decltype(auto)
    {
        return std::forward<TFunc>(func)(xs, ys);
    }

    template <typename TFunc>
    auto apply_arrays(TFunc&& func) const -> decltype(auto)
    {
        return std::forward<TFunc>(func)(xs, ys);
    }

    auto num() const -> size_type
    {
        return xs.Num();
    }

    auto is_empty() const -> bool
    {
        return num() == 0;
    }

    auto reset() -> void
    {
        xs.Reset();
        ys.Reset();
    }

    auto empty() -> void
    {
        xs.Empty();
        ys.Empty();
    }

    auto reserve(size_type const count) -> void
    {
        xs.Reserve(count);
        ys.Reserve(count);
    }

    auto set_num_uninitialized(size_type const count) -> void
    {
        xs.SetNumUninitialized(count);
        ys.SetNumUninitialized(count);
    }

    auto add_uninitialized(size_type const count) -> void
    {
        xs.AddUninitialized(count);
        ys.AddUninitialized(count);
    }
};

USTRUCT()
struct FVectors3f
{
    GENERATED_BODY()

    using value_type = float;
    using size_type = TArray<value_type>::SizeType;
    using View = TVectors3View<value_type>;
    using ConstView = TVectors3View<value_type const>;

    UPROPERTY()
    TArray<float> xs;
    UPROPERTY()
    TArray<float> ys;
    UPROPERTY()
    TArray<float> zs;

    auto get_view() -> View
    {
        return View{xs, ys, zs};
    }

    auto get_view() const -> ConstView
    {
        return ConstView{xs, ys, zs};
    }

    auto get_const_view() const -> ConstView
    {
        return ConstView{xs, ys, zs};
    }

    template <typename TFunc>
    auto apply_arrays(TFunc&& func) -> decltype(auto)
    {
        return std::forward<TFunc>(func)(xs, ys, zs);
    }

    template <typename TFunc>
    auto apply_arrays(TFunc&& func) const -> decltype(auto)
    {
        return std::forward<TFunc>(func)(xs, ys, zs);
    }

    auto num() const -> size_type
    {
        return xs.Num();
    }

    auto is_empty() const -> bool
    {
        return num() == 0;
    }

    auto reset() -> void
    {
        xs.Reset();
        ys.Reset();
        zs.Reset();
    }

    auto empty() -> void
    {
        xs.Empty();
        ys.Empty();
        zs.Empty();
    }

    auto reserve(size_type const count) -> void
    {
        xs.Reserve(count);
        ys.Reserve(count);
        zs.Reserve(count);
    }

    auto set_num_uninitialized(size_type const count) -> void
    {
        xs.SetNumUninitialized(count);
        ys.SetNumUninitialized(count);
        zs.SetNumUninitialized(count);
    }

    auto add_uninitialized(size_type const count) -> void
    {
        xs.AddUninitialized(count);
        ys.AddUninitialized(count);
        zs.AddUninitialized(count);
    }
};

USTRUCT()
struct FVectors3d
{
    GENERATED_BODY()

    using value_type = double;
    using size_type = TArray<value_type>::SizeType;
    using View = TVectors3View<value_type>;
    using ConstView = TVectors3View<value_type const>;

    UPROPERTY()
    TArray<double> xs;
    UPROPERTY()
    TArray<double> ys;
    UPROPERTY()
    TArray<double> zs;

    auto get_view() -> View
    {
        return View{xs, ys, zs};
    }

    auto get_view() const -> ConstView
    {
        return ConstView{xs, ys, zs};
    }

    auto get_const_view() const -> ConstView
    {
        return ConstView{xs, ys, zs};
    }

    template <typename TFunc>
    auto apply_arrays(TFunc&& func) -> decltype(auto)
    {
        return std::forward<TFunc>(func)(xs, ys, zs);
    }

    template <typename TFunc>
    auto apply_arrays(TFunc&& func) const -> decltype(auto)
    {
        return std::forward<TFunc>(func)(xs, ys, zs);
    }

    auto num() const -> size_type
    {
        return xs.Num();
    }

    auto is_empty() const -> bool
    {
        return num() == 0;
    }

    auto reset() -> void
    {
        xs.Reset();
        ys.Reset();
        zs.Reset();
    }

    auto empty() -> void
    {
        xs.Empty();
        ys.Empty();
        zs.Empty();
    }

    auto reserve(size_type const count) -> void
    {
        xs.Reserve(count);
        ys.Reserve(count);
        zs.Reserve(count);
    }

    auto set_num_uninitialized(size_type const count) -> void
    {
        xs.SetNumUninitialized(count);
        ys.SetNumUninitialized(count);
        zs.SetNumUninitialized(count);
    }

    auto add_uninitialized(size_type const count) -> void
    {
        xs.AddUninitialized(count);
        ys.AddUninitialized(count);
        zs.AddUninitialized(count);
    }
};

USTRUCT()
struct FVectors3i32
{
    GENERATED_BODY()

    using value_type = int32;
    using size_type = TArray<value_type>::SizeType;
    using View = TVectors3View<value_type>;
    using ConstView = TVectors3View<value_type const>;

    UPROPERTY()
    TArray<int32> xs;
    UPROPERTY()
    TArray<int32> ys;
    UPROPERTY()
    TArray<int32> zs;

    auto get_view() -> View
    {
        return View{xs, ys, zs};
    }

    auto get_view() const -> ConstView
    {
        return ConstView{xs, ys, zs};
    }

    auto get_const_view() const -> ConstView
    {
        return ConstView{xs, ys, zs};
    }

    template <typename TFunc>
    auto apply_arrays(TFunc&& func) -> decltype(auto)
    {
        return std::forward<TFunc>(func)(xs, ys, zs);
    }

    template <typename TFunc>
    auto apply_arrays(TFunc&& func) const -> decltype(auto)
    {
        return std::forward<TFunc>(func)(xs, ys, zs);
    }

    auto num() const -> size_type
    {
        return xs.Num();
    }

    auto is_empty() const -> bool
    {
        return num() == 0;
    }

    auto reset() -> void
    {
        xs.Reset();
        ys.Reset();
        zs.Reset();
    }

    auto empty() -> void
    {
        xs.Empty();
        ys.Empty();
        zs.Empty();
    }

    auto reserve(size_type const count) -> void
    {
        xs.Reserve(count);
        ys.Reserve(count);
        zs.Reserve(count);
    }

    auto set_num_uninitialized(size_type const count) -> void
    {
        xs.SetNumUninitialized(count);
        ys.SetNumUninitialized(count);
        zs.SetNumUninitialized(count);
    }

    auto add_uninitialized(size_type const count) -> void
    {
        xs.AddUninitialized(count);
        ys.AddUninitialized(count);
        zs.AddUninitialized(count);
    }
};

USTRUCT()
struct FVectors3u32
{
    GENERATED_BODY()

    using value_type = uint32;
    using size_type = TArray<value_type>::SizeType;
    using View = TVectors3View<value_type>;
    using ConstView = TVectors3View<value_type const>;

    UPROPERTY()
    TArray<uint32> xs;
    UPROPERTY()
    TArray<uint32> ys;
    UPROPERTY()
    TArray<uint32> zs;

    auto get_view() -> View
    {
        return View{xs, ys, zs};
    }

    auto get_view() const -> ConstView
    {
        return ConstView{xs, ys, zs};
    }

    auto get_const_view() const -> ConstView
    {
        return ConstView{xs, ys, zs};
    }

    template <typename TFunc>
    auto apply_arrays(TFunc&& func) -> decltype(auto)
    {
        return std::forward<TFunc>(func)(xs, ys, zs);
    }

    template <typename TFunc>
    auto apply_arrays(TFunc&& func) const -> decltype(auto)
    {
        return std::forward<TFunc>(func)(xs, ys, zs);
    }

    auto num() const -> size_type
    {
        return xs.Num();
    }

    auto is_empty() const -> bool
    {
        return num() == 0;
    }

    auto reset() -> void
    {
        xs.Reset();
        ys.Reset();
        zs.Reset();
    }

    auto empty() -> void
    {
        xs.Empty();
        ys.Empty();
        zs.Empty();
    }

    auto reserve(size_type const count) -> void
    {
        xs.Reserve(count);
        ys.Reserve(count);
        zs.Reserve(count);
    }

    auto set_num_uninitialized(size_type const count) -> void
    {
        xs.SetNumUninitialized(count);
        ys.SetNumUninitialized(count);
        zs.SetNumUninitialized(count);
    }

    auto add_uninitialized(size_type const count) -> void
    {
        xs.AddUninitialized(count);
        ys.AddUninitialized(count);
        zs.AddUninitialized(count);
    }
};

// clang-format on
