#include <codegen/ast.h>

#include <gtest/gtest.h>

#include <filesystem>
#include <stdexcept>
#include <string>
#include <vector>

namespace codegen {
namespace {

TEST(Ast, NodeProvidesVariantInterface) {
    Node node{Raw{"initial", {}}};

    EXPECT_TRUE(node.is<Raw>());
    ASSERT_NE(node.get_if<Raw>(), nullptr);
    EXPECT_EQ(node.get_if<Raw>()->text, "initial");
    EXPECT_EQ(std::visit([](auto const& value) { return sizeof(value); }, node), sizeof(Raw));

    node = NewLines{2};

    EXPECT_TRUE(node.is<NewLines>());
    EXPECT_EQ(node.get_if<NewLines>()->count, 2);
    EXPECT_EQ(node.get_if<Raw>(), nullptr);
}

TEST(Ast, RendersBraceInitialisedTree) {
    CppFile const file{
        .path = std::filesystem::path{"Example.h"},
        .nodes = {
            Include{"Example/Dependency.h", false},
            lines(2),
            Namespace{
                "example",
                {
                    Struct{
                        .name = "FValue",
                        .children = {
                            Member{"int32", "value"},
                            header_function(FunctionSpec{
                                .name = "get",
                                .return_type = "auto",
                                .body = {raw("return value;")},
                                .suffix = " const -> int32",
                                .is_inline = true,
                            }),
                        },
                    },
                },
            },
        },
    };

    EXPECT_EQ(render(file), R"(// This file is autogenerated. Do not edit by hand.
// Edit Codegen/manifests and regenerate it instead.

#pragma once

#include "Example/Dependency.h"

namespace example {
struct FValue {
    int32 value;

    auto get() const -> int32 {
        return value;
    }
};
} // namespace example
)");
}

TEST(Ast, CollectsNestedTypeDependenciesOnceAndInGroups) {
    TypeDependency const element{"FElement", "Project/Element.h", {}};
    CppType const array{
        "TArray<FElement>",
        {TypeDependency{"TArray<FElement>", "Containers/Array.h", {element}}},
    };
    CppFile const file{
        .path = "Example.h",
        .nodes = {
            IncludeDependencies{},
            lines(2),
            Struct{
                .name = "FData",
                .children = {Member{array, "first"}, Member{array, "second"}},
            },
        },
        .include_order = {"Project/"},
    };

    auto const rendered{render(file)};
    EXPECT_EQ(rendered.find("Project/Element.h"), rendered.rfind("Project/Element.h"));
    EXPECT_EQ(rendered.find("Containers/Array.h"), rendered.rfind("Containers/Array.h"));
    EXPECT_LT(rendered.find("Project/Element.h"), rendered.find("Containers/Array.h"));
}

TEST(Ast, RendersDeclarationsAndOutOfLineDefinitionsFromOneSpec) {
    FunctionSpec const spec{
        .name = "set",
        .return_type = "void",
        .parameters = {FunctionParameter{"int32 const", "value", "0"}},
        .body = {raw("stored = value;")},
        .suffix = " noexcept",
    };

    EXPECT_EQ(render(declaration(spec)), "void set(int32 const value = 0) noexcept;");
    EXPECT_EQ(render(definition(spec, "FValue")),
              "void FValue::set(int32 const value) noexcept {\n"
              "    stored = value;\n"
              "}");
}

TEST(Ast, RejectsInvalidNewLineCounts) {
    EXPECT_THROW(lines(0), std::invalid_argument);
}

TEST(Ast, TypeOperationsAreStronglyTyped) {
    CppType type{"FContainer"};
    type.member_operations.emplace(TypeOperation::remove_at_swap, "remove_at_swap");

    EXPECT_EQ(type.operation(TypeOperation::remove_at_swap), "remove_at_swap");
}

} // namespace
} // namespace codegen
