#include <codegen/ast.h>

#include <gtest/gtest.h>

#include <filesystem>
#include <stdexcept>
#include <string>
#include <vector>

namespace codegen {
namespace {

TEST(Ast, NodeProvidesVariantInterface) {
    Node node{Raw{"initial", {}}};

    EXPECT_TRUE(node.is<Raw>());
    ASSERT_NE(node.get_if<Raw>(), nullptr);
    EXPECT_EQ(node.get_if<Raw>()->text, "initial");
    EXPECT_EQ(std::visit([](auto const& value) { return sizeof(value); }, node), sizeof(Raw));

    node = NewLines{2};

    EXPECT_TRUE(node.is<NewLines>());
    EXPECT_EQ(node.get_if<NewLines>()->count, 2);
    EXPECT_EQ(node.get_if<Raw>(), nullptr);
}

TEST(Ast, NodeListBuilderComposesSectionsAndSpacing) {
    NodeListBuilder section;
    section.add(Member{"int32", "first"}, 1).add(Member{"int32", "second"});

    NodeListBuilder builder;
    auto nodes{builder.add(AccessSpecifier{"public"}, 1)
                   .append(section.build())
                   .new_lines(2)
                   .add(Member{"int32", "third"})
                   .build()};

    ASSERT_EQ(nodes.size(), 7);
    EXPECT_TRUE(nodes[0].is<AccessSpecifier>());
    EXPECT_EQ(nodes[1].get_if<NewLines>()->count, 1);
    EXPECT_EQ(nodes[2].get_if<Member>()->name, "first");
    EXPECT_EQ(nodes[3].get_if<NewLines>()->count, 1);
    EXPECT_EQ(nodes[4].get_if<Member>()->name, "second");
    EXPECT_EQ(nodes[5].get_if<NewLines>()->count, 2);
    EXPECT_EQ(nodes[6].get_if<Member>()->name, "third");
}

TEST(Ast, RendersFriendDeclarations) {
    EXPECT_EQ(render(Node{FriendDeclaration{"FOwner"}}), "friend class FOwner;");
    EXPECT_EQ(render(Node{FriendDeclaration{"FValue", "struct"}}), "friend struct FValue;");
}

TEST(Ast, RendersTypedStatements) {
    EXPECT_EQ(render(Node{ExpressionStatement{"apply(value)"}}), "apply(value);");
    EXPECT_EQ(render(Node{ReturnStatement{"value"}}), "return value;");
    EXPECT_EQ(render(Node{ReturnStatement{}}), "return;");
    EXPECT_EQ(render(Node{AssignmentStatement{"target", "value"}}), "target = value;");
    EXPECT_EQ(render(Node{VariableDeclarationStatement{"auto const", "count", "values.Num()"}}),
              "auto const count{values.Num()};");
}

TEST(Ast, TypedStatementsReportDependencies) {
    TypeDependency const dependency{"FValue", "Project/Value.h", {}};

    EXPECT_EQ(dependencies(Node{ExpressionStatement{"use_value()", {dependency}}}),
              std::vector<TypeDependency>{dependency});
    EXPECT_EQ(dependencies(Node{ReturnStatement{"FValue{}", {dependency}}}),
              std::vector<TypeDependency>{dependency});
    EXPECT_EQ(dependencies(Node{AssignmentStatement{"target", "FValue{}", {dependency}}}),
              std::vector<TypeDependency>{dependency});
    EXPECT_EQ(dependencies(Node{VariableDeclarationStatement{
                  CppType{"FValue", {dependency}}, "value", "make_value()"}}),
              std::vector<TypeDependency>{dependency});
}

TEST(Ast, RendersAccessSpecifiersWithExplicitIndentation) {
    auto const context{RenderContext{.indent_level = 1, .indent_text = "    "}};

    EXPECT_EQ(render(Node{AccessSpecifier{"public"}}, context), "  public:");
    EXPECT_EQ(render(Node{AccessSpecifier{"private", AccessSpecifier::Indentation::normal}}, context),
              "    private:");
}

TEST(Ast, RendersBraceInitialisedTree) {
    CppFile const file{
        .path = std::filesystem::path{"Example.h"},
        .nodes = {
            Include{"Example/Dependency.h", false},
            lines(2),
            Namespace{
                "example",
                {
                    Struct{
                        .name = "FValue",
                        .children = {
                            Member{"int32", "value"},
                            header_function(FunctionSpec{
                                .name = "get",
                                .return_type = "auto",
                                .body = {raw("return value;")},
                                .suffix = " const -> int32",
                                .is_inline = true,
                            }),
                        },
                    },
                },
            },
        },
    };

    EXPECT_EQ(render(file), R"(// This file is autogenerated. Do not edit by hand.
// Edit Codegen/manifests and regenerate it instead.

#pragma once

#include "Example/Dependency.h"

namespace example {
struct FValue {
    int32 value;

    auto get() const -> int32 {
        return value;
    }
};
} // namespace example
)");
}

TEST(Ast, CollectsNestedTypeDependenciesOnceAndInGroups) {
    TypeDependency const element{"FElement", "Project/Element.h", {}};
    CppType const array{
        "TArray<FElement>",
        {TypeDependency{"TArray<FElement>", "Containers/Array.h", {element}}},
    };
    CppFile const file{
        .path = "Example.h",
        .nodes = {
            IncludeDependencies{},
            lines(2),
            Struct{
                .name = "FData",
                .children = {Member{array, "first"}, Member{array, "second"}},
            },
        },
        .include_order = {"Project/"},
    };

    auto const rendered{render(file)};
    EXPECT_EQ(rendered.find("Project/Element.h"), rendered.rfind("Project/Element.h"));
    EXPECT_EQ(rendered.find("Containers/Array.h"), rendered.rfind("Containers/Array.h"));
    EXPECT_LT(rendered.find("Project/Element.h"), rendered.find("Containers/Array.h"));
}

TEST(Ast, SortsDependencyIncludesWithinConfiguredGroups) {
    CppFile const file{
        .path = "Example.h",
        .nodes = {
            IncludeDependencies{},
            Member{CppType{"FZ", "Project/Z.h"}, "z"},
            Member{CppType{"FA", "Project/A.h"}, "a"},
            Member{CppType{"TArray<int32>", "Containers/Array.h"}, "values"},
        },
        .include_order = {"Project/"},
    };

    auto const rendered{render(file)};
    EXPECT_LT(rendered.find("Project/A.h"), rendered.find("Project/Z.h"));
    EXPECT_LT(rendered.find("Project/Z.h"), rendered.find("Containers/Array.h"));
}

TEST(Ast, RendersExplicitIncludesAtTheirNodeLocation) {
    CppFile const file{
        .path = "Example.cpp",
        .nodes = {
            Include{"Project/Explicit.h", false},
            lines(2),
            raw("int value;"),
        },
        .pragma_once = false,
    };

    auto const rendered{render(file)};
    EXPECT_LT(rendered.find("Project/Explicit.h"), rendered.find("int value;"));
    EXPECT_EQ(rendered.find("Project/Explicit.h"), rendered.rfind("Project/Explicit.h"));
}

TEST(Ast, InfersSystemIncludesFromExtensionlessPaths) {
    EXPECT_TRUE(include_is_system(Include{"vector", std::nullopt}));
    EXPECT_FALSE(include_is_system(Include{"Project/Value.h", std::nullopt}));
    EXPECT_FALSE(include_is_system(Include{"vector", false}));
    EXPECT_TRUE(include_is_system(Include{"Project/Value.h", true}));
}

TEST(Ast, ExposesChildrenForNestedAndDefinedNodes) {
    Node const structure{Struct{.name = "FData", .children = {raw("int value;")}}};
    Node const name_space{Namespace{"example", {raw("int value;")}}};
    Node const function{Function{.spec = FunctionSpec{.name = "f", .body = {raw("return;")}}}};
    Node const declaration_node{
        Function{.spec = FunctionSpec{.name = "f"}, .declaration = true}};
    Node const leaf{raw("int value;")};

    ASSERT_NE(children(structure), nullptr);
    EXPECT_EQ(children(structure)->size(), 1);
    ASSERT_NE(children(name_space), nullptr);
    EXPECT_EQ(children(name_space)->size(), 1);
    ASSERT_NE(children(function), nullptr);
    EXPECT_EQ(children(function)->size(), 1);
    EXPECT_EQ(children(declaration_node), nullptr);
    EXPECT_EQ(children(leaf), nullptr);
}

TEST(Ast, RendersClassInheritanceAndMemberInitializers) {
    auto const rendered{render(Node{Struct{
        .name = "FDerived",
        .children = {Member{"int", "value", "42"}},
        .bases = {CppType{"FBase"}},
        .export_specifier = "PROJECT_API",
        .record_kind = "class",
    }})};

    EXPECT_EQ(rendered,
              "class PROJECT_API FDerived : FBase {\n"
              "    int value{42};\n"
              "};");
}

TEST(Ast, RendersTemplatedConstrainedFunctions) {
    FunctionSpec const spec{
        .name = "append",
        .return_type = "void",
        .parameters = {FunctionParameter{"Other const&", "other"}},
        .body = {raw("append_from(other);")},
        .is_inline = true,
        .template_parameters = "typename Other",
        .requires_clause = "Appendable<Other>",
    };

    auto const rendered{render(header_function(spec))};
    EXPECT_NE(rendered.find("template <typename Other>"), std::string::npos);
    EXPECT_NE(rendered.find("requires Appendable<Other>"), std::string::npos);
    EXPECT_NE(rendered.find("append_from(other);"), std::string::npos);
}

TEST(Ast, RendersTypedFunctionFormattingPolicies) {
    auto compact{FunctionSpec{
        .name = "apply",
        .return_type = "void",
        .body = {raw("func();")},
        .is_inline = true,
        .template_parameters = "typename TFunc",
        .requires_clause = "Invocable<TFunc>",
        .formatting = FunctionFormatting{
            .body_layout = FunctionFormatting::BodyLayout::compact,
            .requires_placement =
                FunctionFormatting::RequiresPlacement::trailing_same_line,
            .template_placement = FunctionFormatting::TemplatePlacement::same_line,
        },
    }};
    EXPECT_EQ(render(header_function(compact)),
              "template <typename TFunc> void apply() requires Invocable<TFunc> { func(); }");

    auto prefixed{compact};
    prefixed.formatting = FunctionFormatting{
        .requires_placement = FunctionFormatting::RequiresPlacement::before_signature,
    };
    EXPECT_EQ(render(header_function(prefixed)),
              "template <typename TFunc>\n"
              "    requires Invocable<TFunc>\n"
              "void apply() {\n"
              "    func();\n"
              "}");

    auto separate_brace{compact};
    separate_brace.template_parameters.reset();
    separate_brace.formatting = FunctionFormatting{
        .opening_brace_placement =
            FunctionFormatting::OpeningBracePlacement::separate_line,
    };
    EXPECT_EQ(render(header_function(separate_brace)),
              "void apply()\n"
              "    requires Invocable<TFunc>\n"
              "{\n"
              "    func();\n"
              "}");
}

TEST(Ast, RendersConstrainedStructuresAndSpecialMembers) {
    TypeDependency const dependency{"check", "CoreMinimal.h", {}};
    Node const structure{Struct{
        .name = "TFixedData",
        .children = {
            declaration(FunctionSpec{
                .name = "TFixedData",
                .suffix = " noexcept = default",
            }),
            lines(1),
            header_function(FunctionSpec{
                .name = "apply",
                .return_type = "void",
                .parameters = {FunctionParameter{"TFunc&&", "func"}},
                .body = {raw("func();")},
                .is_inline = true,
                .template_parameters = "typename TFunc",
                .formatting = FunctionFormatting{
                    .body_layout = FunctionFormatting::BodyLayout::compact,
                    .template_placement = FunctionFormatting::TemplatePlacement::same_line,
                },
            }),
            lines(2),
            AccessSpecifier{"private"},
        },
        .template_parameters = "int Capacity",
        .requires_clause = "(Capacity >= 0)",
        .dependencies = {dependency},
    }};

    EXPECT_EQ(render(structure),
              "template <int Capacity>\n"
              "    requires (Capacity >= 0)\n"
              "struct TFixedData {\n"
              "    TFixedData() noexcept = default;\n"
              "    template <typename TFunc> void apply(TFunc&& func) { func(); }\n\n"
              "  private:\n"
              "};");
    EXPECT_EQ(dependencies(structure), std::vector<TypeDependency>{dependency});
}

TEST(Ast, RawNodesReportExplicitDependencies) {
    TypeDependency const dependency{"FValue", "Project/Value.h", {}};
    Node const node{Raw{"use_value();", {dependency}}};

    EXPECT_EQ(dependencies(node), std::vector<TypeDependency>{dependency});
}

TEST(Ast, RendersDeclarationsAndOutOfLineDefinitionsFromOneSpec) {
    FunctionSpec const spec{
        .name = "set",
        .return_type = "void",
        .parameters = {FunctionParameter{"int32 const", "value", "0"}},
        .body = {raw("stored = value;")},
        .suffix = " noexcept",
    };

    EXPECT_EQ(render(declaration(spec)), "void set(int32 const value = 0) noexcept;");
    EXPECT_EQ(render(definition(spec, "FValue")),
              "void FValue::set(int32 const value) noexcept {\n"
              "    stored = value;\n"
              "}");
}

TEST(Ast, RejectsInvalidNewLineCounts) {
    EXPECT_THROW(lines(0), std::invalid_argument);
}

TEST(Ast, TypeOperationsAreStronglyTyped) {
    CppType type{"FContainer"};
    type.member_operations.emplace(TypeOperation::remove_at_swap, "remove_at_swap");

    EXPECT_EQ(type.operation(TypeOperation::remove_at_swap), "remove_at_swap");
}

} // namespace
} // namespace codegen
