import unittest
from pathlib import Path

from Codegen.cpp_types import F_VECTORS_3F
from Codegen.generate import collect_files, render_files
from Codegen.manifest import modules
from Codegen.nodes import (
    CppType,
    CppFile,
    ForwardDeclaration,
    FreeFunctionSpec,
    FunctionBody,
    FunctionParameter,
    Include,
    IncludeDependencies,
    Member,
    MemberFunctionOperation,
    MemberFunctionSpec,
    Module,
    Namespace,
    NewLines,
    Node,
    ParameterRef,
    Raw,
    REMOVE_AT_SWAP,
    RenderContext,
    Struct,
    TypeDependency,
    UsingDeclaration,
    composed_type,
    type_spelling,
    walk_tree,
)
from Codegen.soa import (
    ForEachSoAMemberCall,
    ForEachSoAMemberOperationCall,
    HomogeneousSoALayout,
    HomogeneousSoAValueType,
    SoAMember,
    SoAStruct,
    SoAStructNames,
    SoAStorageOperation,
    ForEachSoAMemberFreeFunctionCall,
    ForEachSoAMemberPairFreeFunctionCall,
    lower_soa_struct,
    lower_soa_structs_with_source,
    lower_homogeneous_soa_layouts,
    lower_homogeneous_soa_permutation_definitions,
    soa_member,
    tarray_member,
)


class ReturnParameterBody(FunctionBody):
    def __init__(self, parameter: FunctionParameter) -> None:
        self.parameter_to_return = parameter

    def render(self, context: RenderContext) -> str:
        parameter = self.function.parameter(self.parameter_to_return)
        return Raw(f"return {parameter.cpp_name};").render(context)


class NodeRenderingTests(unittest.TestCase):
    def test_cpp_file_renders_node_tree_exactly(self) -> None:
        file = CppFile(
            path=Path("Example.h"),
            nodes=(
                Include("Example/Dependency.h"),
                NewLines(2),
                Include("utility"),
                NewLines(2),
                Namespace(
                    "example",
                    (
                        Struct(
                            "FValue",
                            (
                                Member("int32", "value"),
                                MemberFunctionSpec(
                                    "get",
                                    "auto",
                                    (),
                                    Raw("return value;"),
                                    suffix=" const -> int32",
                                    is_inline=True,
                                ).header_node(),
                            ),
                        ),
                    ),
                ),
            ),
        )

        self.assertEqual(
            file.render(),
            """// This file is autogenerated. Do not edit by hand.
// Edit Codegen/manifest.py and regenerate it instead.

#pragma once

#include "Example/Dependency.h"

#include <utility>

namespace example {
struct FValue {
    int32 value;

    auto get() const -> int32 {
        return value;
    }
};
} // namespace example
""",
        )

    def test_rendering_is_deterministic(self) -> None:
        modules = (Module("empty", header=CppFile(Path("Empty.h"))),)

        first = render_files(modules)
        second = render_files(modules)

        self.assertEqual(first, second)

    def test_manifest_matches_committed_generated_files(self) -> None:
        for generated_file in render_files(modules()):
            self.assertTrue(generated_file.file.path.exists())
            self.assertEqual(
                generated_file.file.path.read_text(encoding="utf-8"),
                generated_file.content,
            )

    def test_manifest_groups_multiple_soa_types_in_one_header(self) -> None:
        generated_modules = modules()
        module_names = {module.name for module in generated_modules}

        self.assertIn("test_capital_ships_soa", module_names)
        self.assertIn("test_lasers_soa", module_names)
        self.assertIn("test_laser_collision_data_soa", module_names)
        self.assertIn("collision_damage_events_soa", module_names)
        self.assertIn("test_capital_ship_fighter_order_queue", module_names)
        self.assertIn("test_entity_registry_data_soa", module_names)
        self.assertIn("registry_entity_handles_soa", module_names)
        self.assertIn("entity_death_info", module_names)
        self.assertIn("sandbox_core_soa_vectors", module_names)
        self.assertIn("soa_vectors_3f", module_names)
        self.assertIn("sandbox_core_soa_rotators", module_names)
        self.assertEqual(len(generated_modules), 25)

    def test_duplicate_output_paths_are_rejected(self) -> None:
        modules = (
            Module("first", header=CppFile(Path("Same.h"))),
            Module("second", header=CppFile(Path("Same.h"))),
        )

        with self.assertRaisesRegex(ValueError, "Duplicate generated output paths"):
            collect_files(modules)

    def test_new_lines_rejects_non_positive_counts(self) -> None:
        with self.assertRaisesRegex(ValueError, "must be positive"):
            NewLines(0)

    def test_walk_tree_visits_leaf_and_nested_nodes_in_preorder(self) -> None:
        leaf = Raw("value")
        self.assertEqual(tuple(walk_tree(leaf)), (leaf,))

        member = Member("int32", "value")
        struct = Struct("FValue", (member,))
        namespace = Namespace("example", (struct,))
        file = CppFile(Path("Example.h"), nodes=(namespace,))

        self.assertEqual(tuple(walk_tree(file)), (file, namespace, struct, member))
        self.assertEqual(tuple(file.children()), (namespace,))
        self.assertEqual(tuple(namespace.children()), (struct,))
        self.assertEqual(tuple(struct.children()), (member,))

        parameter = FunctionParameter("int32", "value")
        body = Raw("return value;")
        function = MemberFunctionSpec(
            "get", "int32", (parameter,), body, is_inline=True
        )
        definition = function.header_node()
        declaration = function.declaration_node()
        self.assertEqual(tuple(walk_tree(definition)), (definition, parameter, body))
        self.assertEqual(tuple(walk_tree(declaration)), (declaration, parameter))

    def test_include_dependencies_collect_nested_types_and_deduplicate(self) -> None:
        element = TypeDependency("FElement", "Project/Element.h")
        array = composed_type(
            "TArray<FElement>", element, header="Containers/Array.h"
        )
        file = CppFile(
            Path("Example.h"),
            include_order=("Project/",),
            nodes=(
                IncludeDependencies(),
                NewLines(2),
                Namespace(
                    "example",
                    (Struct("FData", (Member(array, "first"), Member(array, "second"))),),
                ),
            ),
        )

        rendered = file.render()
        self.assertEqual(rendered.count('#include "Project/Element.h"'), 1)
        self.assertEqual(rendered.count('#include "Containers/Array.h"'), 1)

    def test_include_dependencies_group_and_sort_deterministically(self) -> None:
        dependencies = (
            TypeDependency("Z", "Project/Z.h"),
            TypeDependency("B", "Project/Sub/B.h"),
            TypeDependency("A", "Project/A.h"),
            TypeDependency("Other", "Other.h"),
            TypeDependency("Vector", "vector"),
            TypeDependency("Utility", "utility"),
        )
        file = CppFile(
            Path("Example.h"),
            include_order=("Project/Sub/", "Project/"),
            nodes=(IncludeDependencies(), Raw("struct FValue {};", dependencies)),
        )

        includes = "\n".join(
            line for line in file.render().splitlines() if line.startswith("#include") or not line
        )
        self.assertIn(
            '#include "Project/Sub/B.h"\n\n'
            '#include "Project/A.h"\n#include "Project/Z.h"\n\n'
            '#include "Other.h"\n\n'
            '#include <utility>\n#include <vector>',
            includes,
        )

    def test_include_dependencies_render_from_context_at_their_location(self) -> None:
        dependency = TypeDependency("FValue", "Value.h")
        file = CppFile(
            Path("Example.h"),
            nodes=(
                Raw("// before", (dependency,)),
                NewLines(1),
                IncludeDependencies(),
                NewLines(1),
                Raw("// after"),
            ),
        )

        rendered = file.render()
        self.assertLess(rendered.index("// before"), rendered.index('#include "Value.h"'))
        self.assertLess(rendered.index('#include "Value.h"'), rendered.index("// after"))
        self.assertEqual(
            IncludeDependencies().render(
                RenderContext(include_groups=((Include("Prepared.h"),),))
            ),
            '#include "Prepared.h"',
        )

    def test_explicit_include_renders_in_place_without_becoming_a_dependency(self) -> None:
        file = CppFile(
            Path("Example.h"),
            nodes=(
                Include("Manual.h"),
                NewLines(2),
                IncludeDependencies(),
                Raw("value", (TypeDependency("FValue", "Automatic.h"),)),
            ),
        )

        rendered = file.render()
        self.assertEqual(rendered.count('#include "Manual.h"'), 1)
        self.assertEqual(rendered.count('#include "Automatic.h"'), 1)
        self.assertLess(rendered.index("Manual.h"), rendered.index("Automatic.h"))
        self.assertEqual(
            Include("ForcedQuoted", system=False).render(RenderContext()),
            '#include "ForcedQuoted"',
        )
        self.assertEqual(
            Include("ForcedSystem.h", system=True).render(RenderContext()),
            "#include <ForcedSystem.h>",
        )

    def test_generic_declaration_nodes_render_in_a_struct(self) -> None:
        node = Struct(
            "FExportedData",
            (UsingDeclaration("IndexType", "int32"), Member("IndexType", "index")),
            export_specifier="SANDBOX_API",
        )

        self.assertEqual(
            node.render(RenderContext()),
            """struct SANDBOX_API FExportedData {
    using IndexType = int32;

    IndexType index;
};""",
        )
        self.assertEqual(
            ForwardDeclaration("FExportedData").render(RenderContext()),
            "struct FExportedData;",
        )

    def test_member_function_spec_emits_header_and_source_nodes(self) -> None:
        function = MemberFunctionSpec(
            "update",
            "void",
            (FunctionParameter("int32 const", "value", "0"),),
            Raw("this->value = value;"),
        )

        declaration = function.declaration_node()
        definition = function.definition_node("FData")
        self.assertIs(declaration.function, function)
        self.assertIs(definition.function, function)
        self.assertEqual(
            declaration.render(RenderContext()),
            "void update(int32 const value = 0);",
        )
        self.assertEqual(
            definition.render(RenderContext()),
            """void FData::update(int32 const value) {
    this->value = value;
}""",
        )
        bool_function = MemberFunctionSpec("is_valid", "bool", (), Raw("return true;"))
        self.assertEqual(
            bool_function.declaration_node().render(RenderContext()),
            "bool is_valid();",
        )
        pointer_function = MemberFunctionSpec(
            "get_data", "void*", (), Raw("return nullptr;")
        )
        self.assertEqual(
            pointer_function.declaration_node().render(RenderContext()),
            "auto get_data() -> void*;",
        )
        static_function = MemberFunctionSpec("reset", "void", (), Raw(""), is_static=True)
        self.assertEqual(
            static_function.declaration_node().render(RenderContext()),
            "static void reset();",
        )
        self.assertEqual(
            static_function.definition_node("FData").render(RenderContext()),
            "void FData::reset() {\n\n}",
        )

    def test_free_function_spec_handles_inline_bodies(self) -> None:
        function = FreeFunctionSpec(
            "make_value",
            "int32",
            (FunctionParameter("int32", "value", "1"),),
            Raw("return value;"),
            is_inline=True,
        )

        self.assertEqual(
            function.header_node().render(RenderContext()),
            """inline auto make_value(int32 value = 1) -> int32 {
    return value;
}""",
        )
        self.assertEqual(
            function.definition_node().render(RenderContext()),
            """auto make_value(int32 value) -> int32 {
    return value;
}""",
        )

    def test_function_body_binds_to_member_function_and_tracks_parameter_name(self) -> None:
        weight = FunctionParameter("float", "weight")
        body = ReturnParameterBody(weight)
        function = MemberFunctionSpec("get_weight", "float", (weight,), body)

        self.assertIs(body.function, function)
        self.assertIsInstance(function.parameter(weight), ParameterRef)
        self.assertEqual(
            function.definition_node("FData").render(RenderContext()),
            """auto FData::get_weight(float weight) -> float {
    return weight;
}""",
        )

        weight.name = "strength"
        self.assertEqual(
            function.definition_node("FData").render(RenderContext()),
            """auto FData::get_weight(float strength) -> float {
    return strength;
}""",
        )

    def test_function_body_works_for_free_functions_and_rejects_reuse(self) -> None:
        value = FunctionParameter("int32", "value")
        body = ReturnParameterBody(value)
        function = FreeFunctionSpec("identity", "int32", (value,), body)

        self.assertEqual(
            function.definition_node().render(RenderContext()),
            """auto identity(int32 value) -> int32 {
    return value;
}""",
        )

        with self.assertRaisesRegex(ValueError, "already bound"):
            MemberFunctionSpec("identity", "int32", (value,), body)

    def test_function_body_rejects_rendering_before_binding(self) -> None:
        body = ReturnParameterBody(FunctionParameter("int32", "value"))

        with self.assertRaisesRegex(ValueError, "must be bound"):
            body.render(RenderContext())


class SoARenderingTests(unittest.TestCase):
    def test_type_directed_operation_uses_registered_member_function(self) -> None:
        function = MemberFunctionSpec(
            "remove_at_swap",
            "void",
            (
                FunctionParameter("int32 const", "index"),
                FunctionParameter("int32 const", "count"),
                FunctionParameter("EAllowShrinking const", "allow_shrinking"),
            ),
            ForEachSoAMemberOperationCall(
                (tarray_member("values", "int32"),),
                REMOVE_AT_SWAP,
                "ml::remove_at_swap",
            ),
        )

        self.assertIn(
            "values.RemoveAtSwap(index, count, allow_shrinking);",
            function.definition_node("FData").render(RenderContext()),
        )

    def test_generated_soa_container_registers_its_remove_at_swap(self) -> None:
        function = MemberFunctionSpec(
            "remove_at_swap",
            "void",
            (
                FunctionParameter("int32 const", "index"),
                FunctionParameter("int32 const", "count"),
                FunctionParameter("EAllowShrinking const", "allow_shrinking"),
            ),
            ForEachSoAMemberOperationCall(
                (soa_member("locations", F_VECTORS_3F),),
                REMOVE_AT_SWAP,
                "ml::remove_at_swap",
            ),
        )

        self.assertIn(
            "locations.remove_at_swap(index, count, allow_shrinking);",
            function.definition_node("FData").render(RenderContext()),
        )

    def test_type_directed_operation_uses_generic_fallback(self) -> None:
        function = MemberFunctionSpec(
            "remove_at_swap",
            "void",
            (
                FunctionParameter("int32 const", "index"),
                FunctionParameter("int32 const", "count"),
                FunctionParameter("EAllowShrinking const", "allow_shrinking"),
            ),
            ForEachSoAMemberOperationCall(
                (soa_member("values", "FNestedValues"),),
                REMOVE_AT_SWAP,
                "ml::remove_at_swap",
            ),
        )

        self.assertIn(
            "ml::remove_at_swap(values, index, count, allow_shrinking);",
            function.definition_node("FData").render(RenderContext()),
        )

    def test_operation_lookup_does_not_use_type_dependencies(self) -> None:
        dependency = TypeDependency("FSharedDependency", "SharedDependency.h")
        operation = MemberFunctionOperation("RemoveAtSwap")
        direct_type = CppType(
            "FValues",
            (dependency,),
            {REMOVE_AT_SWAP: operation},
        )
        fallback_type = CppType("FValues", (dependency,))

        self.assertIs(direct_type.operation(REMOVE_AT_SWAP), operation)
        self.assertIsNone(fallback_type.operation(REMOVE_AT_SWAP))

    def test_tarray_types_share_construction_without_template_awareness(self) -> None:
        floats = tarray_member("floats", "float").container_type
        tasks = tarray_member("tasks", "ETask").container_type

        self.assertIsNot(floats, tasks)
        self.assertEqual(floats.spelling, "TArray<float>")
        self.assertEqual(tasks.spelling, "TArray<ETask>")
        self.assertIs(
            floats.operation(REMOVE_AT_SWAP), tasks.operation(REMOVE_AT_SWAP)
        )

    def test_function_parameter_stores_a_cpp_type(self) -> None:
        parameter = FunctionParameter("int32 const", "count")

        self.assertIsInstance(parameter.type_name, CppType)
        self.assertEqual(parameter.type_name.spelling, "int32 const")

    def test_member_free_function_call_uses_bound_function_parameters(self) -> None:
        count = FunctionParameter("int32 const", "count")
        function = MemberFunctionSpec(
            "add_defaulted",
            "void",
            (count,),
            ForEachSoAMemberFreeFunctionCall(
                (tarray_member("handles", "int32"), tarray_member("weights", "float")),
                "ml::add_defaulted",
            ),
        )

        self.assertEqual(
            function.definition_node("FData").render(RenderContext()),
            """void FData::add_defaulted(int32 const count) {
    ml::add_defaulted(handles, count);
    ml::add_defaulted(weights, count);
}""",
        )

        count.name = "new_count"
        self.assertIn("new_count);", function.definition_node("FData").render(RenderContext()))

    def test_member_pair_free_function_call_expands_other_members(self) -> None:
        dst_i = FunctionParameter("int32 const", "dst_i")
        other = FunctionParameter("FData const&", "other")
        src_i = FunctionParameter("int32 const", "src_i")
        function = MemberFunctionSpec(
            "copy_element",
            "void",
            (dst_i, other, src_i),
            ForEachSoAMemberPairFreeFunctionCall(
                (tarray_member("handles", "int32"), tarray_member("weights", "float")),
                "ml::copy_element",
                other,
            ),
        )

        self.assertEqual(
            function.definition_node("FData").render(RenderContext()),
            """void FData::copy_element(int32 const dst_i, FData const& other, int32 const src_i) {
    ml::copy_element(handles, dst_i, other.handles, src_i);
    ml::copy_element(weights, dst_i, other.weights, src_i);
}""",
        )

    def test_soa_copy_element_operation_also_generates_copy_elements(self) -> None:
        soa = SoAStruct(
            SoAStructNames("FData"),
            (
                tarray_member("values", "int32"),
                soa_member("nested_values", "FNestedValues"),
            ),
            storage_operations=(SoAStorageOperation.COPY_ELEMENT,),
        )

        header = lower_soa_struct(soa)[-1].render(RenderContext())

        self.assertIn(
            "    template <typename Other>\n"
            "    void copy_elements(int32 const dst_i, Other const& other, int32 const src_i, int32 const count)",
            header,
        )
        self.assertIn(
            "ml::copy_elements(values, dst_i, other.values, src_i, count);", header
        )
        self.assertIn(
            "ml::copy_elements(nested_values, dst_i, other.nested_values, src_i, count);",
            header,
        )
        self.assertIn(
            "    template <typename Other>\n    void copy_to_tail(Other const& other)", header
        )
        self.assertIn("check(num() >= count);", header)
        self.assertIn("copy_elements(num() - count, other, 0, count);", header)

    def test_member_pair_free_function_call_rejects_an_unowned_other_parameter(self) -> None:
        function = MemberFunctionSpec(
            "append_from",
            "void",
            (FunctionParameter("FData const&", "other"),),
            ForEachSoAMemberPairFreeFunctionCall(
                (tarray_member("values", "int32"),),
                "ml::append_from",
                FunctionParameter("FData const&", "other"),
            ),
        )

        with self.assertRaisesRegex(ValueError, "does not belong"):
            function.definition_node("FData").render(RenderContext())

    def test_member_function_spec_renders_templated_requires_clause(self) -> None:
        other = FunctionParameter("Other const&", "other")
        function = MemberFunctionSpec(
            "append_from",
            "void",
            (other,),
            ForEachSoAMemberPairFreeFunctionCall(
                (tarray_member("values", "int32"),), "ml::append_from", other
            ),
            is_inline=True,
            template_parameters="typename Other",
            requires_clause="ml::SupportsApplyArrayPairsWith<FData, Other>",
        )

        self.assertEqual(
            function.header_node().render(RenderContext()),
            """template <typename Other>
requires ml::SupportsApplyArrayPairsWith<FData, Other>
void append_from(Other const& other) {
    ml::append_from(values, other.values);
}""",
        )

    def test_soa_storage_operations_generate_direct_member_functions(self) -> None:
        soa = SoAStruct(
            SoAStructNames("FData"),
            (tarray_member("values", "int32"),),
            storage_operations=(
                SoAStorageOperation.ADD_DEFAULTED,
                SoAStorageOperation.REMOVE_AT_SWAP,
                SoAStorageOperation.COPY_ELEMENT,
                SoAStorageOperation.APPEND_FROM,
            ),
        )

        lowered = lower_soa_structs_with_source((soa,))
        header = lowered.header_nodes[-1].render(RenderContext())
        source = "\n".join(node.render(RenderContext()) for node in lowered.source_nodes)

        self.assertIn("void add_defaulted(int32 const count);", header)
        self.assertIn("ml::add_defaulted(", source)
        self.assertIn("void remove_at_swap(", header)
        self.assertIn("values.RemoveAtSwap(", header)
        self.assertIn("ml::copy_element(", header)
        self.assertIn("ml::copy_elements(", header)
        self.assertIn("template <typename Other>", header)
        self.assertLess(header.index("void add_defaulted"), header.index("apply_arrays"))

    def test_soa_storage_operations_share_header_and_source_specs(self) -> None:
        first = SoAStruct(
            SoAStructNames("FFirst"),
            (tarray_member("values", "int32"),),
            storage_operations=(
                SoAStorageOperation.RESET,
                SoAStorageOperation.COPY_ELEMENT,
            ),
        )
        second = SoAStruct(
            SoAStructNames("FSecond"),
            (tarray_member("weights", "float"),),
            storage_operations=(SoAStorageOperation.ADD_DEFAULTED,),
        )

        lowered = lower_soa_structs_with_source((first, second))
        header = "\n".join(node.render(RenderContext()) for node in lowered.header_nodes)
        source = "\n".join(node.render(RenderContext()) for node in lowered.source_nodes)

        self.assertIn("void reset();", header)
        self.assertIn("void add_defaulted(int32 const count);", header)
        self.assertIn("void FFirst::reset()", source)
        self.assertIn("void FSecond::add_defaulted(int32 const count)", source)
        self.assertNotIn("copy_element", source)

    def test_soa_sort_generates_callable_permutation_api(self) -> None:
        soa = SoAStruct(
            SoAStructNames("FData"),
            (
                tarray_member("keys", "int32"),
                soa_member("locations", "FVectors3f"),
                tarray_member("values", "float"),
            ),
        )

        lowered = lower_soa_structs_with_source((soa,))
        header = "\n".join(node.render(RenderContext()) for node in lowered.header_nodes)
        source = "\n".join(node.render(RenderContext()) for node in lowered.source_nodes)

        self.assertIn("void apply_permutation(TArrayView<int32> indices);", header)
        self.assertNotIn("ml::apply_permutation(keys, indices);", header)
        self.assertIn("template <typename Compare>", header)
        self.assertIn("void sort(Compare&& compare, TArrayView<int32> scratch_indices)", header)
        self.assertIn("check(scratch_indices.Num() == n);", header)
        self.assertIn("ml::fill_indices(scratch_indices);", header)
        self.assertIn("scratch_indices.Sort", header)
        self.assertIn("apply_permutation(scratch_indices);", header)
        self.assertNotIn("auto indices{scratch_indices};", header)
        self.assertIn("indices[new_index] is the old row index", header)
        self.assertIn("return compare(*this, lhs, rhs);", header)
        self.assertIn("template <auto Compare>", header)
        self.assertIn("void sort(TArrayView<int32> scratch_indices)", header)
        self.assertIn("return Compare(*this, lhs, rhs);", header)
        self.assertNotIn("TFunction", header)
        self.assertNotIn("std::function", header)
        self.assertIn("void FData::apply_permutation(TArrayView<int32> indices)", source)
        self.assertIn("check(indices.Num() == num());", source)
        self.assertIn("ml::apply_permutation(keys, indices);", source)
        self.assertIn("ml::apply_permutation(locations, indices);", source)
        self.assertIn("ml::apply_permutation(values, indices);", source)

    def test_for_each_soa_member_call_uses_bound_function_parameters(self) -> None:
        handles = tarray_member("handles", "FRegistryEntityHandle")
        weights = tarray_member("weights", "float")
        handle = FunctionParameter("FRegistryEntityHandle const", "handle")
        weight = FunctionParameter("float", "weight")
        function = MemberFunctionSpec(
            "add",
            "void",
            (handle, weight),
            ForEachSoAMemberCall((handles, weights), "Add"),
        )

        self.assertEqual(
            function.definition_node("FData").render(RenderContext()),
            """void FData::add(FRegistryEntityHandle const handle, float weight) {
    handles.Add(handle);
    weights.Add(weight);
}""",
        )

        weight.name = "strength"
        self.assertEqual(
            function.definition_node("FData").render(RenderContext()),
            """void FData::add(FRegistryEntityHandle const handle, float strength) {
    handles.Add(handle);
    weights.Add(strength);
}""",
        )

    def test_for_each_soa_member_call_rejects_mismatched_parameters(self) -> None:
        function = MemberFunctionSpec(
            "add",
            "void",
            (FunctionParameter("int32", "value"),),
            ForEachSoAMemberCall(
                (tarray_member("values", "int32"), tarray_member("weights", "float")),
                "Add",
            ),
        )

        with self.assertRaisesRegex(ValueError, "one parameter per SOA member"):
            function.definition_node("FData").render(RenderContext())

    def test_tarray_member_derives_storage_and_view_types(self) -> None:
        member = tarray_member("values", "int32")

        self.assertEqual(type_spelling(member.container_type), "TArray<int32>")
        self.assertEqual(type_spelling(member.view_type), "TArrayView<int32>")
        self.assertEqual(type_spelling(member.const_view_type), "TConstArrayView<int32>")

    def test_soa_struct_names_derive_and_override_view_names(self) -> None:
        default_names = SoAStructNames("FData")
        overridden_names = SoAStructNames("FData", "TDataView", "TDataConstView")

        self.assertEqual(default_names.view_name, "FDataView")
        self.assertEqual(default_names.const_view_name, "FDataConstView")
        self.assertEqual(overridden_names.view_name, "TDataView")
        self.assertEqual(overridden_names.const_view_name, "TDataConstView")

        lowered = lower_soa_struct(
            SoAStruct(overridden_names, (tarray_member("values", "int32"),))
        )
        rendered = "\n".join(node.render(RenderContext()) for node in lowered)
        self.assertIn("struct TDataView", rendered)
        self.assertIn("struct TDataConstView", rendered)

    def test_soa_struct_names_reject_empty_names(self) -> None:
        with self.assertRaisesRegex(ValueError, "SOA struct name"):
            SoAStructNames("")
        with self.assertRaisesRegex(ValueError, "SOA view struct names"):
            SoAStructNames("FData", "")

    def test_homogeneous_soa_layout_lowers_to_generic_struct_nodes(self) -> None:
        layout = HomogeneousSoALayout(
            "Values",
            ("xs", "ys"),
            (
                HomogeneousSoAValueType(
                    "float", "f", "FVector2f", ("FVector2f",)
                ),
            ),
        )

        nodes = lower_homogeneous_soa_layouts((layout,))
        rendered = "\n".join(node.render(RenderContext()) for node in nodes)

        self.assertTrue(all(isinstance(node, (NewLines, Raw, Struct)) for node in nodes))
        self.assertIn("template <typename T>", rendered)
        self.assertIn("struct TValuesEquivalentType<float>", rendered)
        self.assertIn("struct TValuesView", rendered)
        self.assertIn("struct FValuesf", rendered)
        self.assertIn(
            "    template <typename Other>\n"
            "    auto copy_elements(size_type const dst_i, Other const& src, size_type const src_i, size_type const count) -> void",
            rendered,
        )
        self.assertIn("for (auto i{0}; i < count; ++i)", rendered)
        self.assertIn("xs[dst_i + i] = src.xs[src_i + i];", rendered)
        self.assertIn("ys[dst_i + i] = src.ys[src_i + i];", rendered)
        self.assertIn(
            "    template <typename Other>\n    auto copy_to_tail(Other const& src) -> void",
            rendered,
        )
        self.assertIn("copy_elements(num() - count, src, 0, count);", rendered)
        self.assertIn("using equivalent_type = FVector2f;", rendered)
        self.assertIn("auto operator[](size_type const index) const -> equivalent_type", rendered)
        self.assertIn("auto operator[](size_type const index) const -> FVector2f", rendered)
        self.assertIn("auto add(value_type const x, value_type const y) -> size_type", rendered)

        source_nodes = lower_homogeneous_soa_permutation_definitions((layout,))
        source = "\n".join(node.render(RenderContext()) for node in source_nodes)
        self.assertIn("void FValuesf::apply_permutation(TArrayView<int32> indices)", source)
        self.assertIn("ml::apply_permutation(xs, indices);", source)
        self.assertIn("ml::apply_permutation(ys, indices);", source)

    def test_soa_struct_lowers_to_ordered_generic_declarations(self) -> None:
        soa = SoAStruct(
            SoAStructNames("FData", "TDataView", "TDataConstView"),
            (
                tarray_member("values", "int32"),
                soa_member("vectors", "FVectors3f"),
            ),
            equivalent_type="FValue",
        )

        lowered = lower_soa_struct(soa)
        rendered = "\n\n".join(
            node.render(RenderContext())
            for node in lowered
            if not isinstance(node, NewLines)
        )

        self.assertLess(rendered.index("self.values"), rendered.index("self.vectors"))
        self.assertIn("self.values, other.values", rendered)
        self.assertIn("self.vectors, other.vectors", rendered)
        self.assertEqual(rendered.count("auto operator[](int32 const index) const -> FValue"), 3)
        self.assertIn("auto get_view() -> View", rendered)
        self.assertIn("auto slice(int32 const offset, int32 const count) -> View", rendered)
        self.assertIn("auto left(int32 const count) -> View", rendered)
        self.assertIn("auto right(int32 const count) -> View", rendered)
        self.assertNotIn("FSoAViewMixin", rendered)
        self.assertNotIn("FSoAArrayMixin", rendered)
        self.assertNotIn("std::conditional_t", rendered)
        self.assertNotIsInstance(soa, Node)
        self.assertIsInstance(lowered[0], ForwardDeclaration)
        self.assertTrue(all(isinstance(node, (ForwardDeclaration, NewLines, Struct)) for node in lowered))

    def test_invalid_members_are_rejected(self) -> None:
        with self.assertRaisesRegex(ValueError, "must not be empty"):
            SoAMember("TArray<int32>", "", "TConstArrayView<int32>", "values")

        member = tarray_member("values", "int32")
        with self.assertRaisesRegex(ValueError, "duplicate members"):
            lower_soa_struct(SoAStruct(SoAStructNames("FData"), (member, member)))

        with self.assertRaisesRegex(ValueError, "at least one member"):
            SoAStruct(SoAStructNames("FData"), ())

    def test_struct_rejects_duplicate_member_names(self) -> None:
        with self.assertRaisesRegex(ValueError, "duplicate members"):
            Struct("FData", (Member("int32", "value"), Member("float", "value")))

    def test_storage_export_and_nodes_are_rendered(self) -> None:
        soa = SoAStruct(
            SoAStructNames("FExportedData"),
            (tarray_member("values", "int32"),),
            storage_export_specifier="SANDBOX_API",
            nodes=(UsingDeclaration("CountType", "int32"),),
        )

        rendered = lower_soa_struct(soa)[-1].render(RenderContext())

        self.assertIn("struct SANDBOX_API FExportedData", rendered)
        self.assertIn("using CountType = int32;", rendered)

    def test_soa_lowering_inserts_nodes_before_generated_functions_and_members(self) -> None:
        soa = SoAStruct(
            SoAStructNames("FData"),
            (tarray_member("values", "FValue"),),
            nodes=(
                MemberFunctionSpec(
                    "reset_values", "void", (), Raw("values.Reset();"), is_inline=True
                ).header_node(),
                NewLines(1),
                MemberFunctionSpec("validate_values", "void", (), Raw("")).declaration_node(),
            ),
        )

        rendered = lower_soa_struct(soa)[-1].render(RenderContext())

        self.assertLess(rendered.index("void reset_values()"), rendered.index("TArray<FValue> values"))
        self.assertLess(rendered.index("void validate_values"), rendered.index("apply_arrays"))
        self.assertLess(rendered.index("apply_array_pairs"), rendered.index("TArray<FValue> values"))


if __name__ == "__main__":
    unittest.main()
