import unittest
from pathlib import Path

from Codegen.generate import collect_files, render_files
from Codegen.manifest import modules
from Codegen.nodes import (
    CppFile,
    Function,
    Include,
    Member,
    Module,
    Namespace,
    RenderContext,
    Struct,
)
from Codegen.soa import SoAMember, SoAStruct, soa_member, tarray_member


class NodeRenderingTests(unittest.TestCase):
    def test_cpp_file_renders_node_tree_exactly(self) -> None:
        file = CppFile(
            path=Path("Example.h"),
            includes=(Include("utility"),),
            nodes=(
                Namespace(
                    "example",
                    (
                        Struct(
                            "FValue",
                            (
                                Member("int32 value"),
                                Function("auto get() const -> int32", ("return value;",)),
                            ),
                        ),
                    ),
                ),
            ),
        )

        self.assertEqual(
            file.render(),
            """// This file is autogenerated. Do not edit by hand.
// Edit Codegen/manifest.py and regenerate it instead.

#pragma once

#include <utility>

namespace example {
struct FValue {
    int32 value;

    auto get() const -> int32 {
        return value;
    }
};
} // namespace example
""",
        )

    def test_rendering_is_deterministic(self) -> None:
        modules = (Module("empty", header=CppFile(Path("Empty.h"))),)

        first = render_files(modules)
        second = render_files(modules)

        self.assertEqual(first, second)

    def test_manifest_matches_committed_generated_files(self) -> None:
        for generated_file in render_files(modules()):
            self.assertTrue(generated_file.file.path.exists())
            self.assertEqual(
                generated_file.file.path.read_text(encoding="utf-8"),
                generated_file.content,
            )

    def test_duplicate_output_paths_are_rejected(self) -> None:
        modules = (
            Module("first", header=CppFile(Path("Same.h"))),
            Module("second", header=CppFile(Path("Same.h"))),
        )

        with self.assertRaisesRegex(ValueError, "Duplicate generated output paths"):
            collect_files(modules)


class SoARenderingTests(unittest.TestCase):
    def test_tarray_member_derives_storage_and_view_types(self) -> None:
        member = tarray_member("values", "int32")

        self.assertEqual(member.container_type, "TArray<int32>")
        self.assertEqual(member.view_type, "TArrayView<int32>")
        self.assertEqual(member.const_view_type, "TConstArrayView<int32>")

    def test_soa_struct_renders_ordered_apply_functions(self) -> None:
        node = SoAStruct(
            "FData",
            "TDataView",
            (
                tarray_member("values", "int32"),
                soa_member("vectors", "FVectors3f"),
            ),
        )

        rendered = node.render(RenderContext())

        self.assertLess(rendered.index("self.values"), rendered.index("self.vectors"))
        self.assertLess(rendered.index("self.values,"), rendered.index("other.values,"))
        self.assertLess(rendered.index("other.values,"), rendered.index("self.vectors,"))
        self.assertLess(rendered.index("self.vectors,"), rendered.index("other.vectors"))
        self.assertIn("public ml::FSoAViewMixin", rendered)
        self.assertIn("public ml::FSoAArrayMixin", rendered)

    def test_invalid_members_are_rejected(self) -> None:
        with self.assertRaisesRegex(ValueError, "must not be empty"):
            SoAMember("TArray<int32>", "", "TConstArrayView<int32>", "values")

        member = tarray_member("values", "int32")
        with self.assertRaisesRegex(ValueError, "duplicate members"):
            SoAStruct("FData", "TDataView", (member, member))

        with self.assertRaisesRegex(ValueError, "at least one member"):
            SoAStruct("FData", "TDataView", ())


if __name__ == "__main__":
    unittest.main()
