import unittest
from pathlib import Path

from Codegen.generate import collect_files, render_files
from Codegen.manifest import modules
from Codegen.nodes import (
    CppFile,
    ForwardDeclaration,
    FreeFunctionSpec,
    Function,
    FunctionDeclaration,
    FunctionParameter,
    Include,
    Member,
    MemberFunctionSpec,
    Module,
    Namespace,
    NewLines,
    Node,
    RenderContext,
    Struct,
    UsingDeclaration,
)
from Codegen.soa import (
    SoAMember,
    SoAStruct,
    lower_soa_struct,
    soa_member,
    tarray_member,
)


class NodeRenderingTests(unittest.TestCase):
    def test_cpp_file_renders_node_tree_exactly(self) -> None:
        file = CppFile(
            path=Path("Example.h"),
            nodes=(
                Include("Example/Dependency.h"),
                NewLines(2),
                Include("utility"),
                NewLines(2),
                Namespace(
                    "example",
                    (
                        Struct(
                            "FValue",
                            (
                                Member("int32 value"),
                                Function("auto get() const -> int32", ("return value;",)),
                            ),
                        ),
                    ),
                ),
            ),
        )

        self.assertEqual(
            file.render(),
            """// This file is autogenerated. Do not edit by hand.
// Edit Codegen/manifest.py and regenerate it instead.

#pragma once

#include <Example/Dependency.h>

#include <utility>

namespace example {
struct FValue {
    int32 value;

    auto get() const -> int32 {
        return value;
    }
};
} // namespace example
""",
        )

    def test_rendering_is_deterministic(self) -> None:
        modules = (Module("empty", header=CppFile(Path("Empty.h"))),)

        first = render_files(modules)
        second = render_files(modules)

        self.assertEqual(first, second)

    def test_manifest_matches_committed_generated_files(self) -> None:
        for generated_file in render_files(modules()):
            self.assertTrue(generated_file.file.path.exists())
            self.assertEqual(
                generated_file.file.path.read_text(encoding="utf-8"),
                generated_file.content,
            )

    def test_manifest_groups_multiple_soa_types_in_one_header(self) -> None:
        generated_modules = modules()
        module_names = {module.name for module in generated_modules}

        self.assertIn("test_capital_ships_soa", module_names)
        self.assertIn("test_lasers_soa", module_names)
        self.assertIn("collision_damage_events_soa", module_names)
        self.assertIn("test_capital_ship_fighter_order_queue", module_names)
        self.assertIn("entity_death_info", module_names)
        self.assertEqual(len(generated_modules), 11)

    def test_duplicate_output_paths_are_rejected(self) -> None:
        modules = (
            Module("first", header=CppFile(Path("Same.h"))),
            Module("second", header=CppFile(Path("Same.h"))),
        )

        with self.assertRaisesRegex(ValueError, "Duplicate generated output paths"):
            collect_files(modules)

    def test_new_lines_rejects_non_positive_counts(self) -> None:
        with self.assertRaisesRegex(ValueError, "must be positive"):
            NewLines(0)

    def test_generic_declaration_nodes_render_in_a_struct(self) -> None:
        node = Struct(
            "FExportedData",
            (UsingDeclaration("IndexType", "int32"), Member("IndexType index")),
            export_specifier="SANDBOX_API",
        )

        self.assertEqual(
            node.render(RenderContext()),
            """struct SANDBOX_API FExportedData {
    using IndexType = int32;

    IndexType index;
};""",
        )
        self.assertEqual(
            ForwardDeclaration("FExportedData").render(RenderContext()),
            "struct FExportedData;",
        )

    def test_member_function_spec_emits_header_and_source_nodes(self) -> None:
        function = MemberFunctionSpec(
            "update",
            "void",
            (FunctionParameter("int32 const", "value", "0"),),
            ("this->value = value;",),
        )

        self.assertEqual(
            function.declaration_node().render(RenderContext()),
            "void update(int32 const value = 0);",
        )
        self.assertEqual(
            function.definition_node("FData").render(RenderContext()),
            """void FData::update(int32 const value) {
    this->value = value;
}""",
        )
        static_function = MemberFunctionSpec("reset", "void", (), (), is_static=True)
        self.assertEqual(
            static_function.declaration_node().render(RenderContext()),
            "static void reset();",
        )
        self.assertEqual(
            static_function.definition_node("FData").render(RenderContext()),
            "void FData::reset() {\n\n}",
        )

    def test_free_function_spec_handles_inline_bodies(self) -> None:
        function = FreeFunctionSpec(
            "make_value",
            "int32",
            (FunctionParameter("int32", "value", "1"),),
            ("return value;",),
            is_inline=True,
        )

        self.assertEqual(
            function.header_node().render(RenderContext()),
            """inline int32 make_value(int32 value = 1) {
    return value;
}""",
        )
        self.assertEqual(
            function.definition_node().render(RenderContext()),
            """int32 make_value(int32 value) {
    return value;
}""",
        )


class SoARenderingTests(unittest.TestCase):
    def test_tarray_member_derives_storage_and_view_types(self) -> None:
        member = tarray_member("values", "int32")

        self.assertEqual(member.container_type, "TArray<int32>")
        self.assertEqual(member.view_type, "TArrayView<int32>")
        self.assertEqual(member.const_view_type, "TConstArrayView<int32>")

    def test_soa_struct_lowers_to_ordered_generic_declarations(self) -> None:
        soa = SoAStruct(
            "FData",
            "TDataView",
            "TDataConstView",
            (
                tarray_member("values", "int32"),
                soa_member("vectors", "FVectors3f"),
            ),
        )

        lowered = lower_soa_struct(soa)
        rendered = "\n\n".join(
            node.render(RenderContext())
            for node in lowered
            if not isinstance(node, NewLines)
        )

        self.assertLess(rendered.index("self.values"), rendered.index("self.vectors"))
        self.assertIn("self.values, other.values", rendered)
        self.assertIn("self.vectors, other.vectors", rendered)
        self.assertIn("public ml::FSoAViewMixin", rendered)
        self.assertIn("public ml::FSoAArrayMixin", rendered)
        self.assertNotIn("std::conditional_t", rendered)
        self.assertNotIsInstance(soa, Node)
        self.assertIsInstance(lowered[0], ForwardDeclaration)
        self.assertTrue(all(isinstance(node, (ForwardDeclaration, NewLines, Struct)) for node in lowered))

    def test_invalid_members_are_rejected(self) -> None:
        with self.assertRaisesRegex(ValueError, "must not be empty"):
            SoAMember("TArray<int32>", "", "TConstArrayView<int32>", "values")

        member = tarray_member("values", "int32")
        with self.assertRaisesRegex(ValueError, "duplicate members"):
            SoAStruct("FData", "TDataView", "TDataConstView", (member, member))

        with self.assertRaisesRegex(ValueError, "at least one member"):
            SoAStruct("FData", "TDataView", "TDataConstView", ())

    def test_storage_metadata_is_rendered(self) -> None:
        soa = SoAStruct(
            "FExportedData",
            "FExportedDataView",
            "FExportedDataConstView",
            (tarray_member("values", "int32"),),
            storage_export_specifier="SANDBOX_API",
            storage_type_aliases=(("CountType", "int32"),),
        )

        rendered = lower_soa_struct(soa)[-1].render(RenderContext())

        self.assertIn("struct SANDBOX_API FExportedData", rendered)
        self.assertIn("using CountType = int32;", rendered)

    def test_soa_lowering_inserts_storage_extra_nodes_in_order(self) -> None:
        soa = SoAStruct(
            "FData",
            "FDataView",
            "FDataConstView",
            (tarray_member("values", "FValue"),),
            storage_prefix_nodes=(Function("void reset_values()", ("values.Reset();",)),),
            storage_suffix_nodes=(FunctionDeclaration("void validate_values()"),),
        )

        rendered = "\n\n".join(
            node.render(RenderContext())
            for node in lower_soa_struct(soa)
            if not isinstance(node, NewLines)
        )

        self.assertLess(rendered.index("void reset_values()"), rendered.index("TArray<FValue> values"))
        self.assertLess(rendered.index("TArray<FValue> values"), rendered.index("void validate_values"))
        self.assertLess(rendered.index("void validate_values"), rendered.index("apply_arrays"))


if __name__ == "__main__":
    unittest.main()
