import unittest
from pathlib import Path
from typing import override

from Codegen.cpp import (
    CppFile,
    CppWriter,
    ForwardDeclaration,
    FreeFunctionSpec,
    FunctionBody,
    FunctionParameter,
    Include,
    IncludeDependencies,
    Member,
    MemberFunctionSpec,
    Namespace,
    NewLines,
    ParameterRef,
    Raw,
    RenderContext,
    Struct,
    TypeDependency,
    UsingDeclaration,
    composed_type,
    walk_tree,
)


class ReturnParameterBody(FunctionBody):
    def __init__(self, parameter: FunctionParameter) -> None:
        self.parameter_to_return = parameter

    @override
    def render(self, context: RenderContext) -> str:
        parameter = self.function.parameter(self.parameter_to_return)
        return Raw(f"return {parameter.cpp_name};").render(context)


class CppRenderingTests(unittest.TestCase):
    def test_cpp_writer_renders_nested_blocks_deterministically(self) -> None:
        writer = CppWriter()
        with writer.block("struct FValue", "};"):
            writer.line("int32 value{};")
            writer.line()
            with writer.block("void reset()"):
                writer.line("value = 0;")

        self.assertEqual(
            writer.render(),
            "struct FValue {\n"
            "    int32 value{};\n"
            "\n"
            "    void reset() {\n"
            "        value = 0;\n"
            "    }\n"
            "};",
        )

    def test_cpp_writer_rejects_ambiguous_multiline_input(self) -> None:
        writer = CppWriter()
        with self.assertRaisesRegex(ValueError, "exactly one line"):
            writer.line("first\nsecond")

    def test_cpp_file_renders_node_tree_exactly(self) -> None:
        file = CppFile(
            path=Path("Example.h"),
            nodes=(
                Include("Example/Dependency.h"),
                NewLines(2),
                Include("utility"),
                NewLines(2),
                Namespace(
                    "example",
                    (
                        Struct(
                            "FValue",
                            (
                                Member("int32", "value"),
                                MemberFunctionSpec(
                                    "get",
                                    "auto",
                                    (),
                                    Raw("return value;"),
                                    suffix=" const -> int32",
                                    is_inline=True,
                                ).header_node(),
                            ),
                        ),
                    ),
                ),
            ),
        )

        self.assertEqual(
            file.render(),
            """// This file is autogenerated. Do not edit by hand.
// Edit Codegen/manifest.py and regenerate it instead.

#pragma once

#include "Example/Dependency.h"

#include <utility>

namespace example {
struct FValue {
    int32 value;

    auto get() const -> int32 {
        return value;
    }
};
} // namespace example
""",
        )

    def test_new_lines_rejects_non_positive_counts(self) -> None:
        with self.assertRaisesRegex(ValueError, "must be positive"):
            NewLines(0)

    def test_walk_tree_visits_leaf_and_nested_nodes_in_preorder(self) -> None:
        leaf = Raw("value")
        self.assertEqual(tuple(walk_tree(leaf)), (leaf,))

        member = Member("int32", "value")
        struct = Struct("FValue", (member,))
        namespace = Namespace("example", (struct,))
        file = CppFile(Path("Example.h"), nodes=(namespace,))

        self.assertEqual(tuple(walk_tree(file)), (file, namespace, struct, member))
        self.assertEqual(tuple(file.children()), (namespace,))
        self.assertEqual(tuple(namespace.children()), (struct,))
        self.assertEqual(tuple(struct.children()), (member,))

        parameter = FunctionParameter("int32", "value")
        body = Raw("return value;")
        function = MemberFunctionSpec(
            "get", "int32", (parameter,), body, is_inline=True
        )
        definition = function.header_node()
        declaration = function.declaration_node()
        self.assertEqual(tuple(walk_tree(definition)), (definition, parameter, body))
        self.assertEqual(tuple(walk_tree(declaration)), (declaration, parameter))

    def test_include_dependencies_collect_nested_types_and_deduplicate(self) -> None:
        element = TypeDependency("FElement", "Project/Element.h")
        array = composed_type(
            "TArray<FElement>", element, header="Containers/Array.h"
        )
        file = CppFile(
            Path("Example.h"),
            include_order=("Project/",),
            nodes=(
                IncludeDependencies(),
                NewLines(2),
                Namespace(
                    "example",
                    (Struct("FData", (Member(array, "first"), Member(array, "second"))),),
                ),
            ),
        )

        rendered = file.render()
        self.assertEqual(rendered.count('#include "Project/Element.h"'), 1)
        self.assertEqual(rendered.count('#include "Containers/Array.h"'), 1)

    def test_include_dependencies_group_and_sort_deterministically(self) -> None:
        dependencies = (
            TypeDependency("Z", "Project/Z.h"),
            TypeDependency("B", "Project/Sub/B.h"),
            TypeDependency("A", "Project/A.h"),
            TypeDependency("Other", "Other.h"),
            TypeDependency("Vector", "vector"),
            TypeDependency("Utility", "utility"),
        )
        file = CppFile(
            Path("Example.h"),
            include_order=("Project/Sub/", "Project/"),
            nodes=(IncludeDependencies(), Raw("struct FValue {};", dependencies)),
        )

        includes = "\n".join(
            line for line in file.render().splitlines() if line.startswith("#include") or not line
        )
        self.assertIn(
            '#include "Project/Sub/B.h"\n\n'
            '#include "Project/A.h"\n#include "Project/Z.h"\n\n'
            '#include "Other.h"\n\n'
            '#include <utility>\n#include <vector>',
            includes,
        )

    def test_include_dependencies_render_from_context_at_their_location(self) -> None:
        dependency = TypeDependency("FValue", "Value.h")
        file = CppFile(
            Path("Example.h"),
            nodes=(
                Raw("// before", (dependency,)),
                NewLines(1),
                IncludeDependencies(),
                NewLines(1),
                Raw("// after"),
            ),
        )

        rendered = file.render()
        self.assertLess(rendered.index("// before"), rendered.index('#include "Value.h"'))
        self.assertLess(rendered.index('#include "Value.h"'), rendered.index("// after"))
        self.assertEqual(
            IncludeDependencies().render(
                RenderContext(include_groups=((Include("Prepared.h"),),))
            ),
            '#include "Prepared.h"',
        )

    def test_explicit_include_renders_in_place_without_becoming_a_dependency(self) -> None:
        file = CppFile(
            Path("Example.h"),
            nodes=(
                Include("Manual.h"),
                NewLines(2),
                IncludeDependencies(),
                Raw("value", (TypeDependency("FValue", "Automatic.h"),)),
            ),
        )

        rendered = file.render()
        self.assertEqual(rendered.count('#include "Manual.h"'), 1)
        self.assertEqual(rendered.count('#include "Automatic.h"'), 1)
        self.assertLess(rendered.index("Manual.h"), rendered.index("Automatic.h"))
        self.assertEqual(
            Include("ForcedQuoted", system=False).render(RenderContext()),
            '#include "ForcedQuoted"',
        )
        self.assertEqual(
            Include("ForcedSystem.h", system=True).render(RenderContext()),
            "#include <ForcedSystem.h>",
        )

    def test_generic_declaration_nodes_render_in_a_struct(self) -> None:
        node = Struct(
            "FExportedData",
            (UsingDeclaration("IndexType", "int32"), Member("IndexType", "index")),
            export_specifier="SANDBOX_API",
        )

        self.assertEqual(
            node.render(RenderContext()),
            """struct SANDBOX_API FExportedData {
    using IndexType = int32;

    IndexType index;
};""",
        )
        self.assertEqual(
            ForwardDeclaration("FExportedData").render(RenderContext()),
            "struct FExportedData;",
        )

    def test_struct_can_render_a_class(self) -> None:
        node = Struct(
            "FValue",
            (Raw("public:"), Member("int32", "value")),
            record_kind="class",
        )

        self.assertEqual(
            node.render(RenderContext()),
            """class FValue {
    public:

    int32 value;
};""",
        )

        with self.assertRaisesRegex(ValueError, "Record kind"):
            Struct("FValue", (), record_kind="union")

    def test_member_function_spec_emits_header_and_source_nodes(self) -> None:
        function = MemberFunctionSpec(
            "update",
            "void",
            (FunctionParameter("int32 const", "value", "0"),),
            Raw("this->value = value;"),
        )

        declaration = function.declaration_node()
        definition = function.definition_node("FData")
        self.assertIs(declaration.function, function)
        self.assertIs(definition.function, function)
        self.assertEqual(
            declaration.render(RenderContext()),
            "void update(int32 const value = 0);",
        )
        self.assertEqual(
            definition.render(RenderContext()),
            """void FData::update(int32 const value) {
    this->value = value;
}""",
        )
        bool_function = MemberFunctionSpec("is_valid", "bool", (), Raw("return true;"))
        self.assertEqual(
            bool_function.declaration_node().render(RenderContext()),
            "bool is_valid();",
        )
        pointer_function = MemberFunctionSpec(
            "get_data", "void*", (), Raw("return nullptr;")
        )
        self.assertEqual(
            pointer_function.declaration_node().render(RenderContext()),
            "auto get_data() -> void*;",
        )
        static_function = MemberFunctionSpec("reset", "void", (), Raw(""), is_static=True)
        self.assertEqual(
            static_function.declaration_node().render(RenderContext()),
            "static void reset();",
        )
        self.assertEqual(
            static_function.definition_node("FData").render(RenderContext()),
            "void FData::reset() {\n\n}",
        )

    def test_free_function_spec_handles_inline_bodies(self) -> None:
        function = FreeFunctionSpec(
            "make_value",
            "int32",
            (FunctionParameter("int32", "value", "1"),),
            Raw("return value;"),
            is_inline=True,
        )

        self.assertEqual(
            function.header_node().render(RenderContext()),
            """inline auto make_value(int32 value = 1) -> int32 {
    return value;
}""",
        )
        self.assertEqual(
            function.definition_node().render(RenderContext()),
            """auto make_value(int32 value) -> int32 {
    return value;
}""",
        )

    def test_function_body_binds_to_member_function_and_tracks_parameter_name(self) -> None:
        weight = FunctionParameter("float", "weight")
        body = ReturnParameterBody(weight)
        function = MemberFunctionSpec("get_weight", "float", (weight,), body)

        self.assertIs(body.function, function)
        self.assertIsInstance(function.parameter(weight), ParameterRef)
        self.assertEqual(
            function.definition_node("FData").render(RenderContext()),
            """auto FData::get_weight(float weight) -> float {
    return weight;
}""",
        )

        weight.name = "strength"
        self.assertEqual(
            function.definition_node("FData").render(RenderContext()),
            """auto FData::get_weight(float strength) -> float {
    return strength;
}""",
        )

    def test_function_body_works_for_free_functions_and_rejects_reuse(self) -> None:
        value = FunctionParameter("int32", "value")
        body = ReturnParameterBody(value)
        function = FreeFunctionSpec("identity", "int32", (value,), body)

        self.assertEqual(
            function.definition_node().render(RenderContext()),
            """auto identity(int32 value) -> int32 {
    return value;
}""",
        )

        with self.assertRaisesRegex(ValueError, "already bound"):
            MemberFunctionSpec("identity", "int32", (value,), body)

    def test_function_body_rejects_rendering_before_binding(self) -> None:
        body = ReturnParameterBody(FunctionParameter("int32", "value"))

        with self.assertRaisesRegex(ValueError, "must be bound"):
            body.render(RenderContext())
