// clang-format off
// This file is autogenerated. Do not edit by hand.
// Edit Codegen/manifests and regenerate it instead.

#include "SpaceGame/entities/TestEntityType.h"

namespace {
auto get_test_entity_type_name(ETestEntityType const value) -> TCHAR const* {
    switch (value) {
    case ETestEntityType::PlayerShip: {
        return TEXT("PlayerShip");
    }
    case ETestEntityType::Turret: {
        return TEXT("Turret");
    }
    case ETestEntityType::CapitalShip: {
        return TEXT("CapitalShip");
    }
    case ETestEntityType::CapitalShipFighter: {
        return TEXT("CapitalShipFighter");
    }
    case ETestEntityType::TubeSpinner: {
        return TEXT("TubeSpinner");
    }
    case ETestEntityType::COUNT: {
        return TEXT("COUNT");
    }
    }

    ensureMsgf(false,
               TEXT("Unhandled ETestEntityType value: %lld"),
               static_cast<int64>(value));
    return TEXT("<invalid ETestEntityType>");
}

auto get_test_entity_type_display_name(ETestEntityType const value) -> TCHAR const* {
    switch (value) {
    case ETestEntityType::PlayerShip: {
        return TEXT("Player Ship");
    }
    case ETestEntityType::CapitalShip: {
        return TEXT("Capital Ship");
    }
    case ETestEntityType::CapitalShipFighter: {
        return TEXT("Capital Ship Fighter");
    }
    case ETestEntityType::TubeSpinner: {
        return TEXT("Tube Spinner");
    }
    default: {
        break;
    }
    }

    return get_test_entity_type_name(value);
}


} // namespace

auto LexToString(ETestEntityType const value) -> TCHAR const* {
    return get_test_entity_type_name(value);
}

namespace ml {
auto to_string_view(ETestEntityType const value) -> FStringView {
    return FStringView{get_test_entity_type_name(value)};
}

auto to_display_string_view(ETestEntityType const value) -> FStringView {
    return FStringView{get_test_entity_type_display_name(value)};
}


} // namespace ml
// clang-format on
