// This file is autogenerated. Do not edit by hand.
// Edit lispb/schema and regenerate it instead.

#include "SpaceGame/simulation/StaticCollisionSources.h"

#include "SandboxCore/container_ops.h"
#include "SandboxCore/soa_storage_ops.h"

#include "Components/PrimitiveComponent.h"
#include "Containers/ArrayView.h"
#include "Engine/EngineTypes.h"

namespace ml::ioj {
auto FStaticCollisionSources::add(UPrimitiveComponent* component,
                                  ECollisionEnabled::Type const original_collision_mode) -> void {
    components.Add(component);
    original_collision_modes.Add(original_collision_mode);
}

auto FStaticCollisionSourcesConstView::get_view() const -> ConstView {
    return get_view(0, num());
}

auto FStaticCollisionSourcesConstView::get_view(int32 const offset, int32 const count) const
    -> ConstView {
    return ConstView{
        TConstArrayView<TWeakObjectPtr<UPrimitiveComponent>>{components}.Slice(offset, count),
        TConstArrayView<ECollisionEnabled::Type>{original_collision_modes}.Slice(offset, count),
    };
}

auto FStaticCollisionSourcesConstView::get_const_view() const -> ConstView {
    return get_const_view(0, num());
}

auto FStaticCollisionSourcesConstView::get_const_view(int32 const offset, int32 const count) const
    -> ConstView {
    return ConstView{
        TConstArrayView<TWeakObjectPtr<UPrimitiveComponent>>{components}.Slice(offset, count),
        TConstArrayView<ECollisionEnabled::Type>{original_collision_modes}.Slice(offset, count),
    };
}

auto FStaticCollisionSourcesConstView::num() const noexcept -> int32 {
    return ml::num(components);
}

auto FStaticCollisionSourcesConstView::is_empty() const noexcept -> bool {
    return num() == 0;
}

void FStaticCollisionSourcesConstView::validate_array_sizes() const {
    ml::soa_ops::validate_array_sizes(*this);
}

auto FStaticCollisionSourcesConstView::slice(int32 const offset, int32 const count) const
    -> ConstView {
    return get_view(offset, count);
}

auto FStaticCollisionSourcesConstView::left(int32 const count) const -> ConstView {
    return slice(0, count);
}

auto FStaticCollisionSourcesConstView::right(int32 const count) const -> ConstView {
    return slice(num() - count, count);
}

auto FStaticCollisionSourcesView::get_view() -> View {
    return get_view(0, num());
}

auto FStaticCollisionSourcesView::get_view(int32 const offset, int32 const count) -> View {
    return View{
        TArrayView<TWeakObjectPtr<UPrimitiveComponent>>{components}.Slice(offset, count),
        TArrayView<ECollisionEnabled::Type>{original_collision_modes}.Slice(offset, count),
    };
}

auto FStaticCollisionSourcesView::get_view() const -> ConstView {
    return get_view(0, num());
}

auto FStaticCollisionSourcesView::get_view(int32 const offset, int32 const count) const
    -> ConstView {
    return ConstView{
        TConstArrayView<TWeakObjectPtr<UPrimitiveComponent>>{components}.Slice(offset, count),
        TConstArrayView<ECollisionEnabled::Type>{original_collision_modes}.Slice(offset, count),
    };
}

auto FStaticCollisionSourcesView::get_const_view() const -> ConstView {
    return get_const_view(0, num());
}

auto FStaticCollisionSourcesView::get_const_view(int32 const offset, int32 const count) const
    -> ConstView {
    return ConstView{
        TConstArrayView<TWeakObjectPtr<UPrimitiveComponent>>{components}.Slice(offset, count),
        TConstArrayView<ECollisionEnabled::Type>{original_collision_modes}.Slice(offset, count),
    };
}

auto FStaticCollisionSourcesView::num() const noexcept -> int32 {
    return ml::num(components);
}

auto FStaticCollisionSourcesView::is_empty() const noexcept -> bool {
    return num() == 0;
}

void FStaticCollisionSourcesView::validate_array_sizes() const {
    ml::soa_ops::validate_array_sizes(*this);
}

auto FStaticCollisionSourcesView::slice(int32 const offset, int32 const count) -> View {
    return get_view(offset, count);
}

auto FStaticCollisionSourcesView::left(int32 const count) -> View {
    return slice(0, count);
}

auto FStaticCollisionSourcesView::right(int32 const count) -> View {
    return slice(num() - count, count);
}

auto FStaticCollisionSourcesView::slice(int32 const offset, int32 const count) const -> ConstView {
    return get_view(offset, count);
}

auto FStaticCollisionSourcesView::left(int32 const count) const -> ConstView {
    return slice(0, count);
}

auto FStaticCollisionSourcesView::right(int32 const count) const -> ConstView {
    return slice(num() - count, count);
}

void FStaticCollisionSources::reset() {
    ml::soa_ops::reset(*this);
}

void FStaticCollisionSources::apply_permutation(TArrayView<int32> indices) {
    ml::soa_ops::apply_permutation(*this, indices);
}

auto FStaticCollisionSources::get_view() -> View {
    return get_view(0, num());
}

auto FStaticCollisionSources::get_view(int32 const offset, int32 const count) -> View {
    return View{
        TArrayView<TWeakObjectPtr<UPrimitiveComponent>>{components}.Slice(offset, count),
        TArrayView<ECollisionEnabled::Type>{original_collision_modes}.Slice(offset, count),
    };
}

auto FStaticCollisionSources::get_view() const -> ConstView {
    return get_view(0, num());
}

auto FStaticCollisionSources::get_view(int32 const offset, int32 const count) const -> ConstView {
    return ConstView{
        TConstArrayView<TWeakObjectPtr<UPrimitiveComponent>>{components}.Slice(offset, count),
        TConstArrayView<ECollisionEnabled::Type>{original_collision_modes}.Slice(offset, count),
    };
}

auto FStaticCollisionSources::get_const_view() const -> ConstView {
    return get_const_view(0, num());
}

auto FStaticCollisionSources::get_const_view(int32 const offset, int32 const count) const
    -> ConstView {
    return ConstView{
        TConstArrayView<TWeakObjectPtr<UPrimitiveComponent>>{components}.Slice(offset, count),
        TConstArrayView<ECollisionEnabled::Type>{original_collision_modes}.Slice(offset, count),
    };
}

auto FStaticCollisionSources::num() const noexcept -> int32 {
    return ml::num(components);
}

auto FStaticCollisionSources::is_empty() const noexcept -> bool {
    return num() == 0;
}

void FStaticCollisionSources::validate_array_sizes() const {
    ml::soa_ops::validate_array_sizes(*this);
}

auto FStaticCollisionSources::slice(int32 const offset, int32 const count) -> View {
    return get_view(offset, count);
}

auto FStaticCollisionSources::left(int32 const count) -> View {
    return slice(0, count);
}

auto FStaticCollisionSources::right(int32 const count) -> View {
    return slice(num() - count, count);
}

auto FStaticCollisionSources::slice(int32 const offset, int32 const count) const -> ConstView {
    return get_view(offset, count);
}

auto FStaticCollisionSources::left(int32 const count) const -> ConstView {
    return slice(0, count);
}

auto FStaticCollisionSources::right(int32 const count) const -> ConstView {
    return slice(num() - count, count);
}
} // namespace ml::ioj
