#pragma once
#include <Logging/LogMacros.h>

SPACEGAMEPRESENTATION_API DECLARE_LOG_CATEGORY_EXTERN(LogSandboxUI, Log, All);
SPACEGAMEPRESENTATION_API DECLARE_LOG_CATEGORY_EXTERN(LogSandboxAudio, Log, All);
