// This file is autogenerated. Do not edit by hand.
// Edit lispb/schema and regenerate it instead.

#pragma once

#include "ioj/sim/player/fire_rate.h"
#include "SpaceGameSimulation/ships/player/TestShipFireRate.h"
namespace ml {
[[nodiscard]] constexpr auto to_native(ETestShipFireRate const value) noexcept
    -> ::ioj::sim::ShipFireRate {
    switch (value) {
        case ETestShipFireRate::Single: {
            return ::ioj::sim::ShipFireRate::Single;
        }
        case ETestShipFireRate::Burst3: {
            return ::ioj::sim::ShipFireRate::Burst3;
        }
        case ETestShipFireRate::FullAuto: {
            return ::ioj::sim::ShipFireRate::FullAuto;
        }
        case ETestShipFireRate::COUNT: {
            return ::ioj::sim::ShipFireRate::COUNT;
        }
    }

    return static_cast<::ioj::sim::ShipFireRate>(value);
}

[[nodiscard]] constexpr auto to_unreal(::ioj::sim::ShipFireRate const value) noexcept
    -> ETestShipFireRate {
    switch (value) {
        case ::ioj::sim::ShipFireRate::Single: {
            return ETestShipFireRate::Single;
        }
        case ::ioj::sim::ShipFireRate::Burst3: {
            return ETestShipFireRate::Burst3;
        }
        case ::ioj::sim::ShipFireRate::FullAuto: {
            return ETestShipFireRate::FullAuto;
        }
        case ::ioj::sim::ShipFireRate::COUNT: {
            return ETestShipFireRate::COUNT;
        }
    }

    return static_cast<ETestShipFireRate>(value);
}

static_assert(static_cast<int>(ETestShipFireRate::Single) ==
              static_cast<int>(::ioj::sim::ShipFireRate::Single));
static_assert(static_cast<int>(ETestShipFireRate::Burst3) ==
              static_cast<int>(::ioj::sim::ShipFireRate::Burst3));
static_assert(static_cast<int>(ETestShipFireRate::FullAuto) ==
              static_cast<int>(::ioj::sim::ShipFireRate::FullAuto));
static_assert(static_cast<int>(ETestShipFireRate::COUNT) ==
              static_cast<int>(::ioj::sim::ShipFireRate::COUNT));
} // namespace ml
