// This file is autogenerated. Do not edit by hand.
// Edit lispb/schema and regenerate it instead.

#pragma once

#include "ioj/sim/player/flight_mode.h"
#include "SpaceGameSimulation/ships/player/TestSpaceShipFlightMode.h"
namespace ml {
[[nodiscard]] constexpr auto to_native(ETestSpaceShipFlightMode const value) noexcept
    -> ::ioj::sim::SpaceShipFlightMode {
    switch (value) {
        case ETestSpaceShipFlightMode::ForwardSpeed: {
            return ::ioj::sim::SpaceShipFlightMode::ForwardSpeed;
        }
        case ETestSpaceShipFlightMode::PlanarVelocity: {
            return ::ioj::sim::SpaceShipFlightMode::PlanarVelocity;
        }
    }

    return static_cast<::ioj::sim::SpaceShipFlightMode>(value);
}

[[nodiscard]] constexpr auto to_unreal(::ioj::sim::SpaceShipFlightMode const value) noexcept
    -> ETestSpaceShipFlightMode {
    switch (value) {
        case ::ioj::sim::SpaceShipFlightMode::ForwardSpeed: {
            return ETestSpaceShipFlightMode::ForwardSpeed;
        }
        case ::ioj::sim::SpaceShipFlightMode::PlanarVelocity: {
            return ETestSpaceShipFlightMode::PlanarVelocity;
        }
    }

    return static_cast<ETestSpaceShipFlightMode>(value);
}

static_assert(static_cast<int>(ETestSpaceShipFlightMode::ForwardSpeed) ==
              static_cast<int>(::ioj::sim::SpaceShipFlightMode::ForwardSpeed));
static_assert(static_cast<int>(ETestSpaceShipFlightMode::PlanarVelocity) ==
              static_cast<int>(::ioj::sim::SpaceShipFlightMode::PlanarVelocity));
} // namespace ml
