#pragma once

#include "Logging/LogMacros.h"

// Don't forget to update SandboxConsoleCommands.cpp

SPACEGAME_API DECLARE_LOG_CATEGORY_EXTERN(LogSandboxFrameCount, Log, All);

// Systems
SPACEGAME_API DECLARE_LOG_CATEGORY_EXTERN(LogSandbox, Log, All);
SPACEGAME_API DECLARE_LOG_CATEGORY_EXTERN(LogSandboxUI, Log, All);
SPACEGAME_API DECLARE_LOG_CATEGORY_EXTERN(LogSandboxMassEntity, Log, All);
SPACEGAME_API DECLARE_LOG_CATEGORY_EXTERN(LogSandboxAI, Log, All);
SPACEGAME_API DECLARE_LOG_CATEGORY_EXTERN(LogSandboxActor, Log, All);
SPACEGAME_API DECLARE_LOG_CATEGORY_EXTERN(LogSandboxCharacter, Log, All);
SPACEGAME_API DECLARE_LOG_CATEGORY_EXTERN(LogSandboxController, Log, All);
SPACEGAME_API DECLARE_LOG_CATEGORY_EXTERN(LogSandboxActorComponent, Log, All);
SPACEGAME_API DECLARE_LOG_CATEGORY_EXTERN(LogSandboxSubsystem, Log, All);
SPACEGAME_API DECLARE_LOG_CATEGORY_EXTERN(LogSandboxGameMode, Log, All);

// Gameplay
SPACEGAME_API DECLARE_LOG_CATEGORY_EXTERN(LogSandboxWeapon, Log, All);
SPACEGAME_API DECLARE_LOG_CATEGORY_EXTERN(LogSandboxInput, Log, All);
SPACEGAME_API DECLARE_LOG_CATEGORY_EXTERN(LogSandboxInventory, Log, All);
SPACEGAME_API DECLARE_LOG_CATEGORY_EXTERN(LogSandboxHealth, Log, All);

SPACEGAME_API DECLARE_LOG_CATEGORY_EXTERN(LogSandboxEntities, Log, All);
SPACEGAME_API DECLARE_LOG_CATEGORY_EXTERN(LogSandboxNavigation, Log, All);
SPACEGAME_API DECLARE_LOG_CATEGORY_EXTERN(LogSandboxTargeting, Log, All);
SPACEGAME_API DECLARE_LOG_CATEGORY_EXTERN(LogSandboxCombat, Log, All);

// Misc
SPACEGAME_API DECLARE_LOG_CATEGORY_EXTERN(LogSandboxLearning, Log, All);
