// This file is autogenerated. Do not edit by hand.
// Edit lispb/schema and regenerate it instead.

#pragma once

#include <array>

#include <cstdint>

#include <cstddef>

#include <optional>

#include <string_view>

#include "sandbox/core/enum_traits.h"

namespace ioj::sim {
enum class SpaceShipFlightMode : std::uint8_t {
    ForwardSpeed = 0,
    PlanarVelocity = 1,
};

[[nodiscard]] constexpr auto to_string(SpaceShipFlightMode const value) noexcept
    -> std::string_view {
    switch (value) {
        case SpaceShipFlightMode::ForwardSpeed: {
            return "ForwardSpeed";
        }
        case SpaceShipFlightMode::PlanarVelocity: {
            return "PlanarVelocity";
        }
    }

    return "<invalid SpaceShipFlightMode>";
}

[[nodiscard]] constexpr auto try_parse_space_ship_flight_mode(std::string_view const value) noexcept
    -> std::optional<SpaceShipFlightMode> {
    if (value == "ForwardSpeed") {
        return SpaceShipFlightMode::ForwardSpeed;
    }
    if (value == "PlanarVelocity") {
        return SpaceShipFlightMode::PlanarVelocity;
    }

    return std::nullopt;
}

[[nodiscard]] constexpr auto to_display_string(SpaceShipFlightMode const value) noexcept
    -> std::string_view {
    switch (value) {
        case SpaceShipFlightMode::ForwardSpeed: {
            return "Forward Speed";
        }
        case SpaceShipFlightMode::PlanarVelocity: {
            return "Planar Velocity";
        }
    }

    return "<invalid SpaceShipFlightMode>";
}

[[nodiscard]] constexpr auto to_serialized_string(SpaceShipFlightMode const value) noexcept
    -> std::string_view {
    switch (value) {
        case SpaceShipFlightMode::ForwardSpeed: {
            return "forward_speed";
        }
        case SpaceShipFlightMode::PlanarVelocity: {
            return "planar_velocity";
        }
        default: {
            return "<invalid SpaceShipFlightMode>";
        }
    }
}

[[nodiscard]] constexpr auto
    try_parse_serialized_space_ship_flight_mode(std::string_view const value) noexcept
    -> std::optional<SpaceShipFlightMode> {
    if (value == "forward_speed") {
        return SpaceShipFlightMode::ForwardSpeed;
    }
    if (value == "planar_velocity") {
        return SpaceShipFlightMode::PlanarVelocity;
    }

    return std::nullopt;
}

} // namespace ioj::sim
namespace ml {
template <>
struct EnumTraits<::ioj::sim::SpaceShipFlightMode> {
    inline static constexpr std::array values{
        ::ioj::sim::SpaceShipFlightMode::ForwardSpeed,
        ::ioj::sim::SpaceShipFlightMode::PlanarVelocity,
    };
    inline static constexpr std::array names{
        std::string_view{"ForwardSpeed"},
        std::string_view{"PlanarVelocity"},
    };
    inline static constexpr std::size_t count{values.size()};
};

} // namespace ml
