#undef RETURN_VALUE_AND_WARN_IF_EXPR

#undef RETURN_IF_NULLPTR
#undef RETURN_VALUE_IF_NULLPTR
#undef TRY_INIT_PTR
#undef INIT_PTR_OR_RETURN_VALUE

#undef TRY_INIT_BTTASK_PTR

#undef RETURN_IF_INVALID
#undef TRY_INIT_VALID

#undef RETURN_IF_NULLOPT
#undef TRY_INIT_OPTIONAL
#undef RETURN_VALUE_IF_NULLOPT
#undef INIT_OPTIONAL_OR_RETURN_VALUE

#undef RETURN_IF_TRUE
#undef RETURN_IF_FALSE
