// This file is autogenerated. Do not edit by hand.
// Edit lispb/schema and regenerate it instead.

#pragma once

#include "native_soa/storage.h"
#include "sandbox/core/soa_permutation.h"
#include "sandbox/simulation/laser_source.h"
#include "sandbox/simulation/vectors3f.h"

namespace ml::simulation {
struct LaserHitDetailsView;
struct LaserHitDetailsConstView;
struct LaserHitDetailsConstView {
    using View = LaserHitDetailsView;
    using ConstView = LaserHitDetailsConstView;
    using size_type = std::int32_t;
    Vectors3fConstView locations;
    Vectors3fConstView emission_directions;
    std::span<ml::simulation::LaserSource const> sources;
    auto num() const noexcept -> size_type { return static_cast<size_type>(locations.xs.size()); }
    auto is_empty() const noexcept -> bool { return num() == 0; }
    template <typename Fn>
    void each_column(Fn&& fn) const {
        fn(locations.xs);
        fn(locations.ys);
        fn(locations.zs);
        fn(emission_directions.xs);
        fn(emission_directions.ys);
        fn(emission_directions.zs);
        fn(sources);
    }
    void validate_array_sizes() const {
        auto const count{num()};
        each_column([count](auto column) {
            ml::native_soa::require(column.size() == static_cast<std::size_t>(count));
        });
    }
    auto slice(size_type const offset, size_type const count) const -> LaserHitDetailsConstView {
        ml::native_soa::require(offset >= 0 && count >= 0 && offset <= num() &&
                                count <= num() - offset);
        return {
            locations.slice(offset, count),
            emission_directions.slice(offset, count),
            sources.subspan(static_cast<std::size_t>(offset), static_cast<std::size_t>(count)),
        };
    }
    auto get_view() const -> LaserHitDetailsConstView { return *this; }
    auto get_view(size_type const offset, size_type const count) const -> LaserHitDetailsConstView {
        return slice(offset, count);
    }
    auto get_const_view() const -> ConstView {
        return {
            locations.get_const_view(),
            emission_directions.get_const_view(),
            sources,
        };
    }
    auto get_const_view(size_type const offset, size_type const count) const -> ConstView {
        return get_const_view().slice(offset, count);
    }
    auto left(size_type const count) const -> LaserHitDetailsConstView { return slice(0, count); }
    auto right(size_type const count) const -> LaserHitDetailsConstView {
        return slice(num() - count, count);
    }
};
struct LaserHitDetailsView {
    using View = LaserHitDetailsView;
    using ConstView = LaserHitDetailsConstView;
    using size_type = std::int32_t;
    Vectors3fView locations;
    Vectors3fView emission_directions;
    std::span<ml::simulation::LaserSource> sources;
    auto num() const noexcept -> size_type { return static_cast<size_type>(locations.xs.size()); }
    auto is_empty() const noexcept -> bool { return num() == 0; }
    template <typename Fn>
    void each_column(Fn&& fn) const {
        fn(locations.xs);
        fn(locations.ys);
        fn(locations.zs);
        fn(emission_directions.xs);
        fn(emission_directions.ys);
        fn(emission_directions.zs);
        fn(sources);
    }
    void validate_array_sizes() const {
        auto const count{num()};
        each_column([count](auto column) {
            ml::native_soa::require(column.size() == static_cast<std::size_t>(count));
        });
    }
    auto slice(size_type const offset, size_type const count) const -> LaserHitDetailsView {
        ml::native_soa::require(offset >= 0 && count >= 0 && offset <= num() &&
                                count <= num() - offset);
        return {
            locations.slice(offset, count),
            emission_directions.slice(offset, count),
            sources.subspan(static_cast<std::size_t>(offset), static_cast<std::size_t>(count)),
        };
    }
    auto get_view() const -> LaserHitDetailsView { return *this; }
    auto get_view(size_type const offset, size_type const count) const -> LaserHitDetailsView {
        return slice(offset, count);
    }
    auto get_const_view() const -> ConstView {
        return {
            locations.get_const_view(),
            emission_directions.get_const_view(),
            sources,
        };
    }
    auto get_const_view(size_type const offset, size_type const count) const -> ConstView {
        return get_const_view().slice(offset, count);
    }
    auto left(size_type const count) const -> LaserHitDetailsView { return slice(0, count); }
    auto right(size_type const count) const -> LaserHitDetailsView {
        return slice(num() - count, count);
    }
};
struct LaserHitDetails {
    using View = LaserHitDetailsView;
    using ConstView = LaserHitDetailsConstView;
    using size_type = std::int32_t;
    Vectors3f locations;
    Vectors3f emission_directions;
    ml::native_soa::Vector<ml::simulation::LaserSource> sources;
    auto num() const noexcept -> size_type { return static_cast<size_type>(locations.xs.size()); }
    auto is_empty() const noexcept -> bool { return num() == 0; }
    template <typename Fn>
    void each_column(Fn&& fn) {
        fn(locations.xs);
        fn(locations.ys);
        fn(locations.zs);
        fn(emission_directions.xs);
        fn(emission_directions.ys);
        fn(emission_directions.zs);
        fn(sources);
    }
    template <typename Fn>
    void each_column(Fn&& fn) const {
        fn(locations.xs);
        fn(locations.ys);
        fn(locations.zs);
        fn(emission_directions.xs);
        fn(emission_directions.ys);
        fn(emission_directions.zs);
        fn(sources);
    }
    void validate_array_sizes() const { get_const_view().validate_array_sizes(); }
    void reserve(size_type const count) {
        ml::native_soa::require(count >= 0);
        locations.xs.reserve(static_cast<std::size_t>(count));
        locations.ys.reserve(static_cast<std::size_t>(count));
        locations.zs.reserve(static_cast<std::size_t>(count));
        emission_directions.xs.reserve(static_cast<std::size_t>(count));
        emission_directions.ys.reserve(static_cast<std::size_t>(count));
        emission_directions.zs.reserve(static_cast<std::size_t>(count));
        sources.reserve(static_cast<std::size_t>(count));
    }
    void reset() noexcept {
        locations.xs.clear();
        locations.ys.clear();
        locations.zs.clear();
        emission_directions.xs.clear();
        emission_directions.ys.clear();
        emission_directions.zs.clear();
        sources.clear();
    }
    void set_num(size_type const count) {
        ml::native_soa::require(count >= 0);
        auto const size{static_cast<std::size_t>(count)};
        locations.xs.resize(size);
        locations.ys.resize(size);
        locations.zs.resize(size);
        emission_directions.xs.resize(size);
        emission_directions.ys.resize(size);
        emission_directions.zs.resize(size);
        sources.resize(size);
    }
    void add_uninitialised(size_type const count) {
        auto const old_num{num()};
        ml::native_soa::require(count >= 0 &&
                                count <= std::numeric_limits<size_type>::max() - old_num);
        set_num(old_num + count);
    }
    void add_defaulted(size_type const count) { add_uninitialised(count); }
    void remove_at_swap(size_type const index, size_type const count) {
        auto const old_num{num()};
        ml::native_soa::require(index >= 0 && index <= old_num && count >= 0 &&
                                count <= old_num - index);
        auto const moved{std::min(count, old_num - index - count)};
        auto const source{old_num - moved};
        for (size_type i{}; i < moved; ++i) {
            locations.xs[index + i] = locations.xs[source + i];
        }
        for (size_type i{}; i < moved; ++i) {
            locations.ys[index + i] = locations.ys[source + i];
        }
        for (size_type i{}; i < moved; ++i) {
            locations.zs[index + i] = locations.zs[source + i];
        }
        for (size_type i{}; i < moved; ++i) {
            emission_directions.xs[index + i] = emission_directions.xs[source + i];
        }
        for (size_type i{}; i < moved; ++i) {
            emission_directions.ys[index + i] = emission_directions.ys[source + i];
        }
        for (size_type i{}; i < moved; ++i) {
            emission_directions.zs[index + i] = emission_directions.zs[source + i];
        }
        for (size_type i{}; i < moved; ++i) {
            sources[index + i] = sources[source + i];
        }
        set_num(old_num - count);
    }
    void append_from(ConstView source) {
        auto const count{source.num()};
        ml::native_soa::require(count <= std::numeric_limits<size_type>::max() - num());
        source.validate_array_sizes();
        if (count == 0) {
            return;
        }
        {
            auto const address{reinterpret_cast<std::uintptr_t>(source.locations.xs.data())};
            auto const begin{reinterpret_cast<std::uintptr_t>(locations.xs.data())};
            ml::native_soa::require(address < begin ||
                                    address >= begin + locations.xs.size() * sizeof(float));
        }
        {
            auto const address{reinterpret_cast<std::uintptr_t>(source.locations.ys.data())};
            auto const begin{reinterpret_cast<std::uintptr_t>(locations.ys.data())};
            ml::native_soa::require(address < begin ||
                                    address >= begin + locations.ys.size() * sizeof(float));
        }
        {
            auto const address{reinterpret_cast<std::uintptr_t>(source.locations.zs.data())};
            auto const begin{reinterpret_cast<std::uintptr_t>(locations.zs.data())};
            ml::native_soa::require(address < begin ||
                                    address >= begin + locations.zs.size() * sizeof(float));
        }
        {
            auto const address{
                reinterpret_cast<std::uintptr_t>(source.emission_directions.xs.data())};
            auto const begin{reinterpret_cast<std::uintptr_t>(emission_directions.xs.data())};
            ml::native_soa::require(address < begin ||
                                    address >=
                                        begin + emission_directions.xs.size() * sizeof(float));
        }
        {
            auto const address{
                reinterpret_cast<std::uintptr_t>(source.emission_directions.ys.data())};
            auto const begin{reinterpret_cast<std::uintptr_t>(emission_directions.ys.data())};
            ml::native_soa::require(address < begin ||
                                    address >=
                                        begin + emission_directions.ys.size() * sizeof(float));
        }
        {
            auto const address{
                reinterpret_cast<std::uintptr_t>(source.emission_directions.zs.data())};
            auto const begin{reinterpret_cast<std::uintptr_t>(emission_directions.zs.data())};
            ml::native_soa::require(address < begin ||
                                    address >=
                                        begin + emission_directions.zs.size() * sizeof(float));
        }
        {
            auto const address{reinterpret_cast<std::uintptr_t>(source.sources.data())};
            auto const begin{reinterpret_cast<std::uintptr_t>(sources.data())};
            ml::native_soa::require(address < begin ||
                                    address >= begin + sources.size() *
                                                           sizeof(ml::simulation::LaserSource));
        }
        locations.xs.insert(
            locations.xs.end(), source.locations.xs.begin(), source.locations.xs.end());
        locations.ys.insert(
            locations.ys.end(), source.locations.ys.begin(), source.locations.ys.end());
        locations.zs.insert(
            locations.zs.end(), source.locations.zs.begin(), source.locations.zs.end());
        emission_directions.xs.insert(emission_directions.xs.end(),
                                      source.emission_directions.xs.begin(),
                                      source.emission_directions.xs.end());
        emission_directions.ys.insert(emission_directions.ys.end(),
                                      source.emission_directions.ys.begin(),
                                      source.emission_directions.ys.end());
        emission_directions.zs.insert(emission_directions.zs.end(),
                                      source.emission_directions.zs.begin(),
                                      source.emission_directions.zs.end());
        sources.insert(sources.end(), source.sources.begin(), source.sources.end());
    }
    auto get_view() -> View {
        return {
            locations.get_view(),
            emission_directions.get_view(),
            sources,
        };
    }
    auto get_view() const -> ConstView {
        return {
            locations.get_view(),
            emission_directions.get_view(),
            sources,
        };
    }
    auto get_const_view() const -> ConstView { return get_view(); }
    auto get_view(size_type const offset, size_type const count) -> View {
        return get_view().slice(offset, count);
    }
    auto get_view(size_type const offset, size_type const count) const -> ConstView {
        return get_view().slice(offset, count);
    }
    auto get_const_view(size_type const offset, size_type const count) const -> ConstView {
        return get_const_view().slice(offset, count);
    }
    auto slice(size_type const offset, size_type const count) -> View {
        return get_view(offset, count);
    }
    auto slice(size_type const offset, size_type const count) const -> ConstView {
        return get_const_view(offset, count);
    }
    auto left(size_type const count) -> View { return slice(0, count); }
    auto right(size_type const count) -> View { return slice(num() - count, count); }
    auto left(size_type const count) const -> ConstView { return slice(0, count); }
    auto right(size_type const count) const -> ConstView { return slice(num() - count, count); }
    template <typename Other>
    void copy_element(size_type const dst_index, Other const& other, size_type const src_index) {
        locations.copy_element(dst_index, other.locations, src_index);
        emission_directions.copy_element(dst_index, other.emission_directions, src_index);
        sources[static_cast<std::size_t>(dst_index)] =
            other.sources[static_cast<std::size_t>(src_index)];
    }
    template <typename Other>
    void copy_elements(size_type const dst_index,
                       Other const& other,
                       size_type const src_index,
                       size_type const count) {
        for (size_type i{}; i < count; ++i) {
            copy_element(dst_index + i, other, src_index + i);
        }
    }
    void apply_permutation(std::span<std::int32_t> const indices) {
        validate_array_sizes();
        ml::native_soa::require(indices.size() == static_cast<std::size_t>(num()));
        each_column([indices](auto& column) { ml::apply_permutation(std::span{column}, indices); });
    }
    template <typename Compare>
    void sort(Compare&& compare, std::span<std::int32_t> const scratch_indices) {
        validate_array_sizes();
        ml::native_soa::require(scratch_indices.size() == static_cast<std::size_t>(num()));
        for (size_type i{}; i < num(); ++i) {
            scratch_indices[static_cast<std::size_t>(i)] = i;
        }
        std::sort(scratch_indices.begin(),
                  scratch_indices.end(),
                  [this, &compare](size_type const lhs, size_type const rhs) {
                      return compare(*this, lhs, rhs);
                  });
        apply_permutation(scratch_indices);
    }
};

} // namespace ml::simulation
