// This file is autogenerated. Do not edit by hand.
// Edit lispb/schema and regenerate it instead.

#pragma once

#include "native_soa/storage.h"
#include "sandbox/core/soa_permutation.h"

struct RegistryEntityHandlesView;
struct RegistryEntityHandlesConstView;
struct RegistryEntityHandlesConstView {
    using View = RegistryEntityHandlesView;
    using ConstView = RegistryEntityHandlesConstView;
    using size_type = std::int32_t;
    std::span<std::int32_t const> registry_indices;
    std::span<std::int32_t const> generations;
    auto num() const noexcept -> size_type {
        return static_cast<size_type>(registry_indices.size());
    }
    auto is_empty() const noexcept -> bool { return num() == 0; }
    template <typename Fn>
    void each_column(Fn&& fn) const {
        fn(registry_indices);
        fn(generations);
    }
    void validate_array_sizes() const {
        auto const count{num()};
        each_column([count](auto column) {
            ml::native_soa::require(column.size() == static_cast<std::size_t>(count));
        });
    }
    auto slice(size_type const offset, size_type const count) const
        -> RegistryEntityHandlesConstView {
        ml::native_soa::require(offset >= 0 && count >= 0 && offset <= num() &&
                                count <= num() - offset);
        return {
            registry_indices.subspan(static_cast<std::size_t>(offset),
                                     static_cast<std::size_t>(count)),
            generations.subspan(static_cast<std::size_t>(offset), static_cast<std::size_t>(count)),
        };
    }
    auto get_view() const -> RegistryEntityHandlesConstView { return *this; }
    auto get_view(size_type const offset, size_type const count) const
        -> RegistryEntityHandlesConstView {
        return slice(offset, count);
    }
    auto get_const_view() const -> ConstView {
        return {
            registry_indices,
            generations,
        };
    }
    auto get_const_view(size_type const offset, size_type const count) const -> ConstView {
        return get_const_view().slice(offset, count);
    }
    auto left(size_type const count) const -> RegistryEntityHandlesConstView {
        return slice(0, count);
    }
    auto right(size_type const count) const -> RegistryEntityHandlesConstView {
        return slice(num() - count, count);
    }
};
struct RegistryEntityHandlesView {
    using View = RegistryEntityHandlesView;
    using ConstView = RegistryEntityHandlesConstView;
    using size_type = std::int32_t;
    std::span<std::int32_t> registry_indices;
    std::span<std::int32_t> generations;
    auto num() const noexcept -> size_type {
        return static_cast<size_type>(registry_indices.size());
    }
    auto is_empty() const noexcept -> bool { return num() == 0; }
    template <typename Fn>
    void each_column(Fn&& fn) const {
        fn(registry_indices);
        fn(generations);
    }
    void validate_array_sizes() const {
        auto const count{num()};
        each_column([count](auto column) {
            ml::native_soa::require(column.size() == static_cast<std::size_t>(count));
        });
    }
    auto slice(size_type const offset, size_type const count) const -> RegistryEntityHandlesView {
        ml::native_soa::require(offset >= 0 && count >= 0 && offset <= num() &&
                                count <= num() - offset);
        return {
            registry_indices.subspan(static_cast<std::size_t>(offset),
                                     static_cast<std::size_t>(count)),
            generations.subspan(static_cast<std::size_t>(offset), static_cast<std::size_t>(count)),
        };
    }
    auto get_view() const -> RegistryEntityHandlesView { return *this; }
    auto get_view(size_type const offset, size_type const count) const
        -> RegistryEntityHandlesView {
        return slice(offset, count);
    }
    auto get_const_view() const -> ConstView {
        return {
            registry_indices,
            generations,
        };
    }
    auto get_const_view(size_type const offset, size_type const count) const -> ConstView {
        return get_const_view().slice(offset, count);
    }
    auto left(size_type const count) const -> RegistryEntityHandlesView { return slice(0, count); }
    auto right(size_type const count) const -> RegistryEntityHandlesView {
        return slice(num() - count, count);
    }
    void set(size_type const index,
             std::int32_t const new_registry_indices,
             std::int32_t const new_generations) const {
        ml::native_soa::require(index >= 0 && index < num());
        registry_indices[static_cast<std::size_t>(index)] = new_registry_indices;
        generations[static_cast<std::size_t>(index)] = new_generations;
    }
};
struct RegistryEntityHandles {
    using View = RegistryEntityHandlesView;
    using ConstView = RegistryEntityHandlesConstView;
    using size_type = std::int32_t;
    ml::native_soa::Vector<std::int32_t> registry_indices;
    ml::native_soa::Vector<std::int32_t> generations;
    auto num() const noexcept -> size_type {
        return static_cast<size_type>(registry_indices.size());
    }
    auto is_empty() const noexcept -> bool { return num() == 0; }
    template <typename Fn>
    void each_column(Fn&& fn) {
        fn(registry_indices);
        fn(generations);
    }
    template <typename Fn>
    void each_column(Fn&& fn) const {
        fn(registry_indices);
        fn(generations);
    }
    void validate_array_sizes() const { get_const_view().validate_array_sizes(); }
    void reserve(size_type const count) {
        ml::native_soa::require(count >= 0);
        registry_indices.reserve(static_cast<std::size_t>(count));
        generations.reserve(static_cast<std::size_t>(count));
    }
    void reset() noexcept {
        registry_indices.clear();
        generations.clear();
    }
    void set_num(size_type const count) {
        ml::native_soa::require(count >= 0);
        auto const size{static_cast<std::size_t>(count)};
        registry_indices.resize(size);
        generations.resize(size);
    }
    void add_uninitialised(size_type const count) {
        auto const old_num{num()};
        ml::native_soa::require(count >= 0 &&
                                count <= std::numeric_limits<size_type>::max() - old_num);
        set_num(old_num + count);
    }
    void add_defaulted(size_type const count) { add_uninitialised(count); }
    void remove_at_swap(size_type const index, size_type const count) {
        auto const old_num{num()};
        ml::native_soa::require(index >= 0 && index <= old_num && count >= 0 &&
                                count <= old_num - index);
        auto const moved{std::min(count, old_num - index - count)};
        auto const source{old_num - moved};
        for (size_type i{}; i < moved; ++i) {
            registry_indices[index + i] = registry_indices[source + i];
        }
        for (size_type i{}; i < moved; ++i) {
            generations[index + i] = generations[source + i];
        }
        set_num(old_num - count);
    }
    void set(size_type const index,
             std::int32_t const new_registry_indices,
             std::int32_t const new_generations) {
        get_view().set(index, new_registry_indices, new_generations);
    }
    auto add(std::int32_t const new_registry_indices, std::int32_t const new_generations)
        -> size_type {
        auto const index{num()};
        add_defaulted(1);
        set(index, new_registry_indices, new_generations);
        return index;
    }
    void append_from(ConstView source) {
        auto const count{source.num()};
        ml::native_soa::require(count <= std::numeric_limits<size_type>::max() - num());
        source.validate_array_sizes();
        if (count == 0) {
            return;
        }
        {
            auto const address{reinterpret_cast<std::uintptr_t>(source.registry_indices.data())};
            auto const begin{reinterpret_cast<std::uintptr_t>(registry_indices.data())};
            ml::native_soa::require(address < begin || address >= begin + registry_indices.size() *
                                                                              sizeof(std::int32_t));
        }
        {
            auto const address{reinterpret_cast<std::uintptr_t>(source.generations.data())};
            auto const begin{reinterpret_cast<std::uintptr_t>(generations.data())};
            ml::native_soa::require(address < begin ||
                                    address >= begin + generations.size() * sizeof(std::int32_t));
        }
        registry_indices.insert(
            registry_indices.end(), source.registry_indices.begin(), source.registry_indices.end());
        generations.insert(generations.end(), source.generations.begin(), source.generations.end());
    }
    auto get_view() -> View {
        return {
            registry_indices,
            generations,
        };
    }
    auto get_view() const -> ConstView {
        return {
            registry_indices,
            generations,
        };
    }
    auto get_const_view() const -> ConstView { return get_view(); }
    auto get_view(size_type const offset, size_type const count) -> View {
        return get_view().slice(offset, count);
    }
    auto get_view(size_type const offset, size_type const count) const -> ConstView {
        return get_view().slice(offset, count);
    }
    auto get_const_view(size_type const offset, size_type const count) const -> ConstView {
        return get_const_view().slice(offset, count);
    }
    auto slice(size_type const offset, size_type const count) -> View {
        return get_view(offset, count);
    }
    auto slice(size_type const offset, size_type const count) const -> ConstView {
        return get_const_view(offset, count);
    }
    auto left(size_type const count) -> View { return slice(0, count); }
    auto right(size_type const count) -> View { return slice(num() - count, count); }
    auto left(size_type const count) const -> ConstView { return slice(0, count); }
    auto right(size_type const count) const -> ConstView { return slice(num() - count, count); }
    template <typename Other>
    void copy_element(size_type const dst_index, Other const& other, size_type const src_index) {
        registry_indices[static_cast<std::size_t>(dst_index)] =
            other.registry_indices[static_cast<std::size_t>(src_index)];
        generations[static_cast<std::size_t>(dst_index)] =
            other.generations[static_cast<std::size_t>(src_index)];
    }
    template <typename Other>
    void copy_elements(size_type const dst_index,
                       Other const& other,
                       size_type const src_index,
                       size_type const count) {
        for (size_type i{}; i < count; ++i) {
            copy_element(dst_index + i, other, src_index + i);
        }
    }
    void apply_permutation(std::span<std::int32_t> const indices) {
        validate_array_sizes();
        ml::native_soa::require(indices.size() == static_cast<std::size_t>(num()));
        each_column([indices](auto& column) { ml::apply_permutation(std::span{column}, indices); });
    }
    template <typename Compare>
    void sort(Compare&& compare, std::span<std::int32_t> const scratch_indices) {
        validate_array_sizes();
        ml::native_soa::require(scratch_indices.size() == static_cast<std::size_t>(num()));
        for (size_type i{}; i < num(); ++i) {
            scratch_indices[static_cast<std::size_t>(i)] = i;
        }
        std::sort(scratch_indices.begin(),
                  scratch_indices.end(),
                  [this, &compare](size_type const lhs, size_type const rhs) {
                      return compare(*this, lhs, rhs);
                  });
        apply_permutation(scratch_indices);
    }
};
