// clang-format off
// This file is autogenerated. Do not edit by hand.
// Edit lispb/schema and regenerate it instead.

#pragma once

#include "CoreMinimal.h"

#include "TestMissionState.generated.h"

UENUM()
enum class ETestMissionState : uint8 {
    NotStarted,
    Running,
    Succeeded,
    Failed,
    Disabled,
};

SPACEGAMESIMULATION_API auto LexToSerializedString(ETestMissionState const value) -> TCHAR const*;

namespace ml {
SPACEGAMESIMULATION_API auto try_parse_serialized(FStringView const value, ETestMissionState& result) -> bool;


} // namespace ml
// clang-format on
