// clang-format off
// This file is autogenerated. Do not edit by hand.
// Edit Codegen/manifests and regenerate it instead.

#pragma once

#include "SpaceGame/combat/lasers/TestLasersSimulation.h"

namespace ml::test_lasers {
class SPACEGAME_API PhaseInterface {
    private:
    void bind(ml::test_lasers::Simulation& new_target);

    void clear_runtime_state();

    void begin_play();

    void begin_tick();

    void simulate(float const dt);

    void commit_spawns();

    void end_tick();

    friend class ATestBatchOrchestrator;
    ml::test_lasers::Simulation* simulation{nullptr};
};
} // namespace ml::test_lasers
// clang-format on
