#include "MockSaveGameSummarySource.h"

namespace ml::ioj::detail {
auto discover_mock_save_game_summaries() -> TArray<FSaveGameSummary> {
#if UE_BUILD_SHIPPING
    return {};
#else
    return {
        {.save_id = TEXT("battle_at_vega"),
         .display_name = TEXT("Battle at Vega"),
         .created_at = FDateTime{2026, 8, 20, 18, 10},
         .last_played_at = FDateTime{2026, 8, 27, 20, 30},
         .total_simulation_duration_seconds = 12480.f,
         .aggregate_score = 22800,
         .outcomes = {{.outcome_id = TEXT("vega_patrol"),
                       .display_name = TEXT("Vega Patrol"),
                       .completed_at = FDateTime{2026, 8, 20, 19, 5},
                       .simulation_duration_seconds = 3180.f,
                       .score = 6100,
                       .result = TEXT("Victory"),
                       .statistics = {{TEXT("Enemy ships destroyed"), TEXT("18")},
                                      {TEXT("Friendly ships lost"), TEXT("2")},
                                      {TEXT("Accuracy"), TEXT("73%")}}},
                      {.outcome_id = TEXT("convoy_escort"),
                       .display_name = TEXT("Convoy Escort"),
                       .completed_at = FDateTime{2026, 8, 24, 21, 15},
                       .simulation_duration_seconds = 4946.f,
                       .score = 8250,
                       .result = TEXT("Victory"),
                       .statistics = {{TEXT("Transports survived"), TEXT("5 / 6")},
                                      {TEXT("Enemy ships destroyed"), TEXT("24")},
                                      {TEXT("Hull integrity"), TEXT("61%")}}},
                      {.outcome_id = TEXT("vega_defence"),
                       .display_name = TEXT("Vega Defence"),
                       .completed_at = FDateTime{2026, 8, 27, 20, 30},
                       .simulation_duration_seconds = 4354.f,
                       .score = 8450,
                       .result = TEXT("Victory"),
                       .statistics = {{TEXT("Defence platforms remaining"), TEXT("4 / 5")},
                                      {TEXT("Capital ships destroyed"), TEXT("2")},
                                      {TEXT("Damage taken"), TEXT("38%")}}}}},
        {.save_id = TEXT("test_run_12"),
         .display_name = TEXT("Test Run 12"),
         .created_at = FDateTime{2026, 8, 26, 13, 30},
         .last_played_at = FDateTime{2026, 8, 26, 14, 12},
         .total_simulation_duration_seconds = 972.f,
         .aggregate_score = 3200,
         .outcomes = {{.outcome_id = TEXT("fleet_interception"),
                       .display_name = TEXT("Fleet Interception"),
                       .completed_at = FDateTime{2026, 8, 26, 14, 12},
                       .simulation_duration_seconds = 972.f,
                       .score = 3200,
                       .result = TEXT("Defeat"),
                       .statistics = {{TEXT("Enemy ships destroyed"), TEXT("7")},
                                      {TEXT("Friendly ships lost"), TEXT("11")}}}}},
        {.save_id = TEXT("fleet_benchmark"),
         .display_name = TEXT("Fleet Benchmark"),
         .created_at = FDateTime{2026, 8, 25, 8, 30},
         .last_played_at = FDateTime{2026, 8, 25, 9, 5},
         .total_simulation_duration_seconds = 1800.f,
         .aggregate_score = 12750,
         .outcomes = {{.outcome_id = TEXT("capital_fleet_benchmark"),
                       .display_name = TEXT("Capital Fleet Benchmark"),
                       .completed_at = FDateTime{2026, 8, 25, 9, 5},
                       .simulation_duration_seconds = 1800.f,
                       .score = 12750,
                       .result = TEXT("Complete"),
                       .statistics = {{TEXT("Simulation ticks"), TEXT("108000")},
                                      {TEXT("Peak active ships"), TEXT("384")},
                                      {TEXT("Average frame time"), TEXT("8.4 ms")}}}}},
    };
#endif
}
}
