// This file is autogenerated. Do not edit by hand.
// Edit lispb/schema and regenerate it instead.

#pragma once

namespace ioj::sim {
struct AttackDistanceBand {
    float minimum_ratio{0.4f};

    float desired_ratio{0.5f};

    float maximum_ratio{0.6f};

    [[nodiscard]] bool values_are_valid() const noexcept;
};
} // namespace ioj::sim
