// This file is autogenerated. Do not edit by hand.
// Edit lispb/schema and regenerate it instead.

#pragma once

#include "ioj/sim/entity_unique_id.h"

#include "sandbox/core/native_soa/storage.h"
#include "sandbox/core/native_soa/vector_storage_ops.h"

#include <cassert>
#include <utility>

namespace ioj::sim {
struct DirectDamageEventsSchema;

struct DirectDamageEventsView;
struct DirectDamageEventsConstView;
struct DirectDamageEventsConstView {
    using View = DirectDamageEventsView;
    using ConstView = DirectDamageEventsConstView;
    using size_type = std::uint32_t;
    std::span<EntityUniqueId const> damaged_entities;
    std::span<std::int32_t const> damage_amounts;
    std::span<EntityUniqueId const> instigators;
    auto num() const noexcept -> size_type {
        return static_cast<size_type>(damaged_entities.size());
    }
    auto is_empty() const noexcept -> bool { return num() == 0; }
    template <typename Fn>
    void each_column(Fn&& fn) const {
        fn(damaged_entities);
        fn(damage_amounts);
        fn(instigators);
    }
    void validate_array_sizes() const {
        ml::native_soa::vector_storage_ops::validate_array_sizes(*this);
    }
    auto slice(size_type const offset, size_type const count) const -> DirectDamageEventsConstView {
        assert(offset <= num() && count <= num() - offset);
        return {
            damaged_entities.subspan(static_cast<std::size_t>(offset),
                                     static_cast<std::size_t>(count)),
            damage_amounts.subspan(static_cast<std::size_t>(offset),
                                   static_cast<std::size_t>(count)),
            instigators.subspan(static_cast<std::size_t>(offset), static_cast<std::size_t>(count)),
        };
    }
    auto get_view() const -> DirectDamageEventsConstView { return *this; }
    auto get_view(size_type const offset, size_type const count) const
        -> DirectDamageEventsConstView {
        return slice(offset, count);
    }
    auto get_const_view() const -> ConstView {
        return {
            damaged_entities,
            damage_amounts,
            instigators,
        };
    }
    auto get_const_view(size_type const offset, size_type const count) const -> ConstView {
        return get_const_view().slice(offset, count);
    }
    auto left(size_type const count) const -> DirectDamageEventsConstView {
        return slice(0, count);
    }
    auto right(size_type const count) const -> DirectDamageEventsConstView {
        assert(count <= num());
        return slice(num() - count, count);
    }
};
struct DirectDamageEventsView {
    using View = DirectDamageEventsView;
    using ConstView = DirectDamageEventsConstView;
    using size_type = std::uint32_t;
    std::span<EntityUniqueId> damaged_entities;
    std::span<std::int32_t> damage_amounts;
    std::span<EntityUniqueId> instigators;
    auto num() const noexcept -> size_type {
        return static_cast<size_type>(damaged_entities.size());
    }
    auto is_empty() const noexcept -> bool { return num() == 0; }
    template <typename Fn>
    void each_column(Fn&& fn) const {
        fn(damaged_entities);
        fn(damage_amounts);
        fn(instigators);
    }
    void validate_array_sizes() const {
        ml::native_soa::vector_storage_ops::validate_array_sizes(*this);
    }
    auto slice(size_type const offset, size_type const count) const -> DirectDamageEventsView {
        assert(offset <= num() && count <= num() - offset);
        return {
            damaged_entities.subspan(static_cast<std::size_t>(offset),
                                     static_cast<std::size_t>(count)),
            damage_amounts.subspan(static_cast<std::size_t>(offset),
                                   static_cast<std::size_t>(count)),
            instigators.subspan(static_cast<std::size_t>(offset), static_cast<std::size_t>(count)),
        };
    }
    auto get_view() const -> DirectDamageEventsView { return *this; }
    auto get_view(size_type const offset, size_type const count) const -> DirectDamageEventsView {
        return slice(offset, count);
    }
    auto get_const_view() const -> ConstView {
        return {
            damaged_entities,
            damage_amounts,
            instigators,
        };
    }
    auto get_const_view(size_type const offset, size_type const count) const -> ConstView {
        return get_const_view().slice(offset, count);
    }
    auto left(size_type const count) const -> DirectDamageEventsView { return slice(0, count); }
    auto right(size_type const count) const -> DirectDamageEventsView {
        assert(count <= num());
        return slice(num() - count, count);
    }
    void set(size_type const index,
             EntityUniqueId const new_damaged_entities,
             std::int32_t const new_damage_amounts,
             EntityUniqueId const new_instigators) const {
        assert(index < num());
        damaged_entities[static_cast<std::size_t>(index)] = new_damaged_entities;
        damage_amounts[static_cast<std::size_t>(index)] = new_damage_amounts;
        instigators[static_cast<std::size_t>(index)] = new_instigators;
    }
};
struct DirectDamageEvents {
    using View = DirectDamageEventsView;
    using ConstView = DirectDamageEventsConstView;
    using size_type = std::uint32_t;
    ml::native_soa::Vector<EntityUniqueId> damaged_entities;
    ml::native_soa::Vector<std::int32_t> damage_amounts;
    ml::native_soa::Vector<EntityUniqueId> instigators;
    auto num() const noexcept -> size_type {
        return static_cast<size_type>(damaged_entities.size());
    }
    auto is_empty() const noexcept -> bool { return num() == 0; }
    template <typename Fn>
    void each_column(Fn&& fn) {
        fn(damaged_entities);
        fn(damage_amounts);
        fn(instigators);
    }
    template <typename Fn>
    void each_column(Fn&& fn) const {
        fn(damaged_entities);
        fn(damage_amounts);
        fn(instigators);
    }
    void validate_array_sizes() const { get_const_view().validate_array_sizes(); }
    void reset() { ml::native_soa::vector_storage_ops::reset(*this); }
    void reserve(size_type const count) {
        ml::native_soa::vector_storage_ops::reserve(*this, count);
    }
    void add_uninitialised(size_type const count) {
        ml::native_soa::vector_storage_ops::add_uninitialised(*this, count);
    }
    void add_defaulted(size_type const count) {
        ml::native_soa::vector_storage_ops::add_defaulted(*this, count);
    }
    void remove_at_swap(size_type const index, size_type const count) {
        ml::native_soa::vector_storage_ops::remove_at_swap(*this, index, count);
    }
    void set_num(size_type const count) {
        ml::native_soa::vector_storage_ops::set_num(*this, count);
    }
    void apply_permutation(std::span<std::int32_t> const indices) {
        ml::native_soa::vector_storage_ops::apply_permutation(*this, indices);
    }
    template <typename Compare>
    void sort(Compare&& compare, std::span<std::int32_t> const scratch_indices) {
        ml::native_soa::vector_storage_ops::sort(
            *this, std::forward<Compare>(compare), scratch_indices);
    }
    void set(size_type const index,
             EntityUniqueId const new_damaged_entities,
             std::int32_t const new_damage_amounts,
             EntityUniqueId const new_instigators) {
        get_view().set(index, new_damaged_entities, new_damage_amounts, new_instigators);
    }
    auto add(EntityUniqueId const new_damaged_entities,
             std::int32_t const new_damage_amounts,
             EntityUniqueId const new_instigators) -> size_type {
        return ml::native_soa::vector_storage_ops::append_rows(*this, 1, [&] {
            damaged_entities.emplace_back(new_damaged_entities);
            damage_amounts.emplace_back(new_damage_amounts);
            instigators.emplace_back(new_instigators);
        });
    }
    void append_from(ConstView source) {
        auto const count{source.num()};
        assert(count <= std::numeric_limits<size_type>::max() - num());
        source.validate_array_sizes();
        if (count == 0) {
            return;
        }
        assert(ml::native_soa::is_external_source(damaged_entities, source.damaged_entities));
        assert(ml::native_soa::is_external_source(damage_amounts, source.damage_amounts));
        assert(ml::native_soa::is_external_source(instigators, source.instigators));
        ml::native_soa::vector_storage_ops::append_rows(*this, count, [&] {
            damaged_entities.insert(damaged_entities.end(),
                                    source.damaged_entities.data(),
                                    source.damaged_entities.data() + count);
            damage_amounts.insert(damage_amounts.end(),
                                  source.damage_amounts.data(),
                                  source.damage_amounts.data() + count);
            instigators.insert(
                instigators.end(), source.instigators.data(), source.instigators.data() + count);
        });
    }
    auto get_view() -> View {
        return {
            damaged_entities,
            damage_amounts,
            instigators,
        };
    }
    auto get_view() const -> ConstView {
        return {
            damaged_entities,
            damage_amounts,
            instigators,
        };
    }
    auto get_const_view() const -> ConstView { return get_view(); }
    auto get_view(size_type const offset, size_type const count) -> View {
        return get_view().slice(offset, count);
    }
    auto get_view(size_type const offset, size_type const count) const -> ConstView {
        return get_view().slice(offset, count);
    }
    auto get_const_view(size_type const offset, size_type const count) const -> ConstView {
        return get_const_view().slice(offset, count);
    }
    auto slice(size_type const offset, size_type const count) -> View {
        return get_view(offset, count);
    }
    auto slice(size_type const offset, size_type const count) const -> ConstView {
        return get_const_view(offset, count);
    }
    auto left(size_type const count) -> View { return slice(0, count); }
    auto right(size_type const count) -> View {
        assert(count <= num());
        return slice(num() - count, count);
    }
    auto left(size_type const count) const -> ConstView { return slice(0, count); }
    auto right(size_type const count) const -> ConstView {
        assert(count <= num());
        return slice(num() - count, count);
    }
    template <typename Other>
    void copy_element(size_type const dst_index, Other const& other, size_type const src_index) {
        auto const destination_index{static_cast<std::size_t>(dst_index)};
        auto const source_index{static_cast<std::size_t>(src_index)};
        damaged_entities[destination_index] = other.damaged_entities[source_index];
        damage_amounts[destination_index] = other.damage_amounts[source_index];
        instigators[destination_index] = other.instigators[source_index];
    }
    template <typename Other>
    void copy_elements(size_type const dst_index,
                       Other const& other,
                       size_type const src_index,
                       size_type const count) {
        for (size_type i{}; i < count; ++i) {
            copy_element(dst_index + i, other, src_index + i);
        }
    }
};

} // namespace ioj::sim
