// This file is autogenerated. Do not edit by hand.
// Edit lispb/schema and regenerate it instead.

#pragma once

#include "ioj/sim/entity_life_state.h"
#include "ioj/sim/entity_unique_id.h"

#include "sandbox/core/native_soa/storage.h"

#include <cassert>
#include <memory_resource>

namespace ioj::sim {
struct EntityDeathInfoSchema;

struct EntityDeathInfoSingleView;
struct EntityDeathInfoSingleConstView;
struct EntityDeathInfoSingleLayout {
    using size_type = std::uint32_t;
    using byte_size_type = std::size_t;

    inline static constexpr size_type capacity_granularity{
        ml::native_soa::LayoutPolicy::capacity_granularity};
    inline static constexpr byte_size_type column_gap{ml::native_soa::LayoutPolicy::column_gap};

    template <typename T>
    using ColLayout = ml::native_soa::ColumnLayout<T>;
    inline static constexpr ml::native_soa::ColumnLayoutStart LayoutStart{};

    inline static constexpr ColLayout<DeathReason> ReasonsColumn{LayoutStart};
    inline static constexpr ColLayout<EntityUniqueId> VictimsColumn{ReasonsColumn};
    inline static constexpr ColLayout<EntityUniqueId> KillersColumn{VictimsColumn};

    inline static constexpr byte_size_type allocation_alignment{KillersColumn.allocation_alignment};

    // Conservative per-block bound for checked capacity arithmetic; gaps do not scale with
    // capacity.
    inline static constexpr byte_size_type capacity_block_bound{
        ml::native_soa::capacity_block_bound(KillersColumn)};
    inline static constexpr size_type max_capacity{
        ml::native_soa::maximum_capacity(capacity_block_bound)};
    static constexpr auto layout_bytes(byte_size_type blocks) noexcept -> byte_size_type {
        return blocks == 0 ? 0 : KillersColumn.data_end(blocks);
    }
    static_assert(max_capacity >= capacity_granularity);
};

template <bool Const>
struct EntityDeathInfoSingleViewImpl : ml::soa_storage_detail::CompactViewOperations {
    using soa_schema = EntityDeathInfoSchema;
    using size_type = std::uint32_t;
    using Layout = EntityDeathInfoSingleLayout;
    using Storage = ml::native_soa::StorageState;
    using State = std::conditional_t<Const, Storage const, Storage>;
    template <typename T>
    using Element = std::conditional_t<Const, T const, T>;
    using View = EntityDeathInfoSingleView;
    using ConstView = EntityDeathInfoSingleConstView;
    EntityDeathInfoSingleViewImpl() = default;
    EntityDeathInfoSingleViewImpl(State* state, size_type offset, size_type count)
        : state_{state}
        , offset_{offset}
        , count_{count} {}
    template <bool Enabled = Const>
    EntityDeathInfoSingleViewImpl(EntityDeathInfoSingleViewImpl<false> const& other)
        requires Enabled
        : state_{other.state_}
        , offset_{other.offset_}
        , count_{other.count_} {}
    auto reasons() const {
        return ml::soa_storage_detail::column_view<std::span<Element<DeathReason>>>(
            state_, offset_, count_, Layout::ReasonsColumn);
    }
    auto victims() const {
        return ml::soa_storage_detail::column_view<std::span<Element<EntityUniqueId>>>(
            state_, offset_, count_, Layout::VictimsColumn);
    }
    auto killers() const {
        return ml::soa_storage_detail::column_view<std::span<Element<EntityUniqueId>>>(
            state_, offset_, count_, Layout::KillersColumn);
    }
    template <typename Func>
    void each_column(Func&& func) const {
        func(reasons());
        func(victims());
        func(killers());
    }
  private:
    friend ml::soa_storage_detail::CompactViewOperations;
    template <bool>
    friend struct EntityDeathInfoSingleViewImpl;
    State* state_{};
    size_type offset_{};
    size_type count_{};
};
struct EntityDeathInfoSingleConstView : EntityDeathInfoSingleViewImpl<true> {
    using Base = EntityDeathInfoSingleViewImpl<true>;
    using Base::Base;
};
static_assert(ml::soa_storage_detail::validate_compact_view<EntityDeathInfoSingleConstView>());
struct EntityDeathInfoSingleView : EntityDeathInfoSingleViewImpl<false> {
    using Base = EntityDeathInfoSingleViewImpl<false>;
    using Base::Base;
};
static_assert(ml::soa_storage_detail::validate_compact_view<EntityDeathInfoSingleView>());
struct EntityDeathInfo
    : protected ml::native_soa::StorageState
    , ml::native_soa::StorageOperations {
    using soa_schema = EntityDeathInfoSchema;
    using Operations = ml::native_soa::StorageOperations;
    using Layout = EntityDeathInfoSingleLayout;
    using size_type = Layout::size_type;
    using byte_size_type = Layout::byte_size_type;
    inline static constexpr auto capacity_granularity = Layout::capacity_granularity;
    inline static constexpr auto allocation_alignment = Layout::allocation_alignment;
    inline static constexpr auto capacity_block_bound = Layout::capacity_block_bound;
    inline static constexpr auto max_capacity = Layout::max_capacity;
    static constexpr auto layout_bytes(byte_size_type blocks) noexcept -> byte_size_type {
        return Layout::layout_bytes(blocks);
    }
    using View = EntityDeathInfoSingleView;
    using ConstView = EntityDeathInfoSingleConstView;
    /* **************************************** */
    // Lifetime
    /* **************************************** */
    EntityDeathInfo() noexcept
        : EntityDeathInfo{std::pmr::get_default_resource()} {}
    explicit EntityDeathInfo(std::pmr::memory_resource* resource) noexcept
        : resource_{resource} {
        assert(resource != nullptr);
    }
    auto get_memory_resource() const noexcept -> std::pmr::memory_resource* { return resource_; }
    ~EntityDeathInfo() { Operations::release_storage(*this); }
    EntityDeathInfo(EntityDeathInfo const&) = delete;
    auto operator=(EntityDeathInfo const&) -> EntityDeathInfo& = delete;
    EntityDeathInfo(EntityDeathInfo&& other) noexcept
        : resource_{other.resource_} {
        Operations::take_storage(*this, other);
    }
    auto operator=(EntityDeathInfo&& other) -> EntityDeathInfo& {
        return Operations::move_assign(*this, other);
    }
  protected:
    template <typename Byte>
    struct DataPointers {
        template <typename T>
        using Element = std::conditional_t<std::is_const_v<Byte>, T const, T>;
        Element<DeathReason>* reasons{};
        Element<EntityUniqueId>* victims{};
        Element<EntityUniqueId>* killers{};
        auto operator+(size_type const offset) const noexcept -> DataPointers {
            if (reasons == nullptr) {
                return {};
            }
            return {reasons + offset, victims + offset, killers + offset};
        }
    };
    template <typename Self>
    auto get_data(this Self& self) noexcept {
        using Byte = std::conditional_t<std::is_const_v<Self>, std::byte const, std::byte>;
        if (self.data_ == nullptr) {
            return DataPointers<Byte>{};
        }
        return make_data_unchecked(static_cast<Byte*>(self.data_), self.capacity_blocks());
    }
    template <typename Self>
    auto get_data(this Self& self, size_type const offset) noexcept {
        return self.get_data() + offset;
    }
  private:
    std::pmr::memory_resource* resource_{};
    friend Operations;
    friend ::ml::soa_storage_detail::StorageRequirements;
    /* **************************************** */
    // Column pointers
    /* **************************************** */
    template <typename Byte>
    static auto make_data_unchecked(Byte* const data, byte_size_type const blocks) noexcept
        -> DataPointers<Byte> {
        ml::native_soa::LayoutCursor cursor{blocks};
        return {cursor.column_pointer(data, Layout::ReasonsColumn),
                cursor.column_pointer(data, Layout::VictimsColumn),
                cursor.column_pointer(data, Layout::KillersColumn)};
    }
    auto capacity_blocks() const noexcept -> byte_size_type {
        return static_cast<byte_size_type>(capacity_ / capacity_granularity);
    }

    /* **************************************** */
    // Typed mutations and growth
    /* **************************************** */
    void default_construct_columns(size_type const first, size_type const count) {
        auto const columns{make_data_unchecked(data_, capacity_blocks()) + first};
        ml::native_soa::default_construct_n(columns.reasons, count);
        ml::native_soa::default_construct_n(columns.victims, count);
        ml::native_soa::default_construct_n(columns.killers, count);
    }
    template <bool Overlapping, typename Byte>
    static void transfer_columns(DataPointers<std::byte> const& destination,
                                 DataPointers<Byte> const& source,
                                 size_type count) {
        auto transfer = [count](auto* dst, auto const* src) {
            ml::native_soa::transfer_n<Overlapping>(dst, src, count);
        };
        transfer(destination.reasons, source.reasons);
        transfer(destination.victims, source.victims);
        transfer(destination.killers, source.killers);
    }
    void swap_remove_columns(size_type const index,
                             size_type const source,
                             size_type const move_count) {
        copy_columns(get_data(), index, source, move_count);
    }
    static void copy_columns(DataPointers<std::byte> const& columns,
                             size_type index,
                             size_type source,
                             size_type move_count) {
        transfer_columns<false>(columns + index, columns + source, move_count);
    }
    void swap_remove_indices(std::span<size_type const> indices) {
        auto const columns{get_data()};
        ml::soa_storage_detail::for_each_removal_run(
            num_, indices, [&](size_type index, size_type source, size_type count) {
                copy_columns(columns, index, source, count);
            });
    }
    template <typename Columns>
    static auto source_pointers(Columns const& source) -> DataPointers<std::byte const>
        requires ml::soa_storage_detail::SoaSourceFor<Columns, EntityDeathInfo, size_type>
    {
        return {ml::native_soa::source_data(source.reasons()),
                ml::native_soa::source_data(source.victims()),
                ml::native_soa::source_data(source.killers())};
    }
    template <typename Columns>
    void append_columns(Columns const& source,
                        size_type source_first,
                        size_type first,
                        size_type count)
        requires ml::soa_storage_detail::SoaSourceFor<Columns, EntityDeathInfo, size_type>
    {
        transfer_columns<false>(get_data(first), source_pointers(source) + source_first, count);
    }
    template <typename Columns>
    void copy_columns_from(Columns const& source,
                           size_type source_first,
                           size_type first,
                           size_type count)
        requires ml::soa_storage_detail::SoaSourceFor<Columns, EntityDeathInfo, size_type>
    {
        transfer_columns<true>(get_data(first), source_pointers(source) + source_first, count);
    }
    void copy_live_columns(std::byte* const new_data, size_type const new_capacity) noexcept {
        auto const old_blocks{capacity_blocks()};
        auto const new_blocks{static_cast<byte_size_type>(new_capacity / capacity_granularity)};
        auto const source{make_data_unchecked(static_cast<std::byte const*>(data_), old_blocks)};
        auto const destination{make_data_unchecked(new_data, new_blocks)};
        transfer_columns<false>(destination, source, num_);
    }
  public:
};
} // namespace ioj::sim
