// This file is autogenerated. Do not edit by hand.
// Edit lispb/schema and regenerate it instead.

#pragma once

#include "ioj/sim/entity_unique_id.h"

#include "sandbox/core/native_soa/storage.h"

#include <cassert>
#include <memory_resource>

namespace ioj::sim {
struct Vectors3fSchema;

struct Rotators3fSchema;

struct SpinnerEntityDataSchema;

struct SpinnerEntityDataSingleView;
struct SpinnerEntityDataSingleConstView;
struct SpinnerEntityDataSingleLayout {
    using size_type = std::uint32_t;
    using byte_size_type = std::size_t;

    inline static constexpr size_type capacity_granularity{
        ml::native_soa::LayoutPolicy::capacity_granularity};
    inline static constexpr byte_size_type column_gap{ml::native_soa::LayoutPolicy::column_gap};

    template <typename T>
    using ColLayout = ml::native_soa::ColumnLayout<T>;
    inline static constexpr ml::native_soa::ColumnLayoutStart LayoutStart{};

    inline static constexpr ColLayout<EntityUniqueId> EntityIdsColumn{LayoutStart};
    inline static constexpr ColLayout<float> LocationsXsColumn{EntityIdsColumn};
    inline static constexpr ColLayout<float> LocationsYsColumn{LocationsXsColumn};
    inline static constexpr ColLayout<float> LocationsZsColumn{LocationsYsColumn};
    inline static constexpr ColLayout<float> YawsColumn{LocationsZsColumn};
    inline static constexpr ColLayout<std::int16_t> LaserCooldownsColumn{YawsColumn};
    inline static constexpr ColLayout<std::int32_t> NextFirePointIndicesColumn{
        LaserCooldownsColumn};

    inline static constexpr byte_size_type allocation_alignment{
        NextFirePointIndicesColumn.allocation_alignment};

    // Conservative per-block bound for checked capacity arithmetic; gaps do not scale with
    // capacity.
    inline static constexpr byte_size_type capacity_block_bound{
        ml::native_soa::capacity_block_bound(NextFirePointIndicesColumn)};
    inline static constexpr size_type max_capacity{
        ml::native_soa::maximum_capacity(capacity_block_bound)};
    static constexpr auto layout_bytes(byte_size_type blocks) noexcept -> byte_size_type {
        return blocks == 0 ? 0 : NextFirePointIndicesColumn.data_end(blocks);
    }
    static_assert(max_capacity >= capacity_granularity);
};

template <bool Const>
struct SpinnerEntityDataSingleViewImpl {
    using soa_schema = SpinnerEntityDataSchema;
    using size_type = std::uint32_t;
    using Storage = ml::native_soa::StorageState;
    using State = std::conditional_t<Const, Storage const, Storage>;
    template <typename T>
    using Element = std::conditional_t<Const, T const, T>;
    using View = SpinnerEntityDataSingleView;
    using ConstView = SpinnerEntityDataSingleConstView;
    SpinnerEntityDataSingleViewImpl() = default;
    SpinnerEntityDataSingleViewImpl(State* state, size_type offset, size_type count)
        : state_{state}
        , offset_{offset}
        , count_{count} {
        validate();
    }
    template <bool Enabled = Const>
    SpinnerEntityDataSingleViewImpl(SpinnerEntityDataSingleViewImpl<false> const& other)
        requires Enabled
        : state_{other.state_}
        , offset_{other.offset_}
        , count_{other.count_} {}
    void validate() const { ml::soa_storage_detail::validate_view(state_, offset_, count_); }
    auto num() const noexcept -> size_type { return count_; }
    auto is_empty() const noexcept -> bool { return count_ == 0; }
    auto get_view(this auto const& self) { return self; }
    auto get_view(this auto const& self, size_type offset, size_type count) {
        return self.slice(offset, count);
    }
    auto slice(this auto const& self, size_type offset, size_type count) {
        return ml::soa_storage_detail::slice_view<decltype(self)>(
            self.state_, self.offset_, self.count_, offset, count);
    }
    auto left(this auto const& self, size_type count) { return self.slice(0, count); }
    auto right(this auto const& self, size_type count) {
        assert(count >= 0 && count <= self.count_);
        return self.slice(self.count_ - count, count);
    }
    auto entity_ids() const -> std::span<Element<EntityUniqueId>> {
        return {ml::soa_storage_detail::view_column_data<EntityUniqueId>(
                    state_,
                    offset_,
                    count_,
                    SpinnerEntityDataSingleLayout::EntityIdsColumn.offset(
                        ml::soa_storage_detail::view_capacity_blocks(state_))),
                static_cast<std::size_t>(count_)};
    }
    auto view_locations() const -> std::conditional_t<Const,
                                                      ml::native_soa::Vector3ConstView<float>,
                                                      ml::native_soa::Vector3View<float>> {
        validate();
        if (!state_ || !state_->data_) {
            return {};
        }
        auto const blocks{ml::soa_storage_detail::view_capacity_blocks(state_)};
        auto const first{SpinnerEntityDataSingleLayout::LocationsXsColumn.offset(blocks)};
        auto const stride{SpinnerEntityDataSingleLayout::LocationsYsColumn.offset(blocks) - first};
        return {ml::soa_storage_detail::view_column_data_unchecked<float>(state_, offset_, first),
                stride,
                count_};
    }
    auto yaws() const -> std::span<Element<float>> {
        return {ml::soa_storage_detail::view_column_data<float>(
                    state_,
                    offset_,
                    count_,
                    SpinnerEntityDataSingleLayout::YawsColumn.offset(
                        ml::soa_storage_detail::view_capacity_blocks(state_))),
                static_cast<std::size_t>(count_)};
    }
    auto laser_cooldowns() const -> std::span<Element<std::int16_t>> {
        return {ml::soa_storage_detail::view_column_data<std::int16_t>(
                    state_,
                    offset_,
                    count_,
                    SpinnerEntityDataSingleLayout::LaserCooldownsColumn.offset(
                        ml::soa_storage_detail::view_capacity_blocks(state_))),
                static_cast<std::size_t>(count_)};
    }
    auto next_fire_point_indices() const -> std::span<Element<std::int32_t>> {
        return {ml::soa_storage_detail::view_column_data<std::int32_t>(
                    state_,
                    offset_,
                    count_,
                    SpinnerEntityDataSingleLayout::NextFirePointIndicesColumn.offset(
                        ml::soa_storage_detail::view_capacity_blocks(state_))),
                static_cast<std::size_t>(count_)};
    }
    template <typename Func>
    void each_column(Func&& func) const {
        func(entity_ids());
        func(view_locations().xs());
        func(view_locations().ys());
        func(view_locations().zs());
        func(yaws());
        func(laser_cooldowns());
        func(next_fire_point_indices());
    }
  private:
    template <bool>
    friend struct SpinnerEntityDataSingleViewImpl;
    State* state_{};
    size_type offset_{};
    size_type count_{};
};
struct SpinnerEntityDataSingleConstView : SpinnerEntityDataSingleViewImpl<true> {
    using Base = SpinnerEntityDataSingleViewImpl<true>;
    using Base::Base;
    using View = SpinnerEntityDataSingleView;
    using ConstView = SpinnerEntityDataSingleConstView;
    SpinnerEntityDataSingleConstView() = default;
    SpinnerEntityDataSingleConstView(SpinnerEntityDataSingleView const& other);
    auto get_const_view() const -> ConstView { return *this; }
    auto get_const_view(size_type offset, size_type count) const -> ConstView {
        return slice(offset, count);
    }
};
static_assert(ml::soa_storage_detail::validate_compact_view<SpinnerEntityDataSingleConstView>());
struct SpinnerEntityDataSingleView : SpinnerEntityDataSingleViewImpl<false> {
    using Base = SpinnerEntityDataSingleViewImpl<false>;
    using Base::Base;
    using View = SpinnerEntityDataSingleView;
    using ConstView = SpinnerEntityDataSingleConstView;
    SpinnerEntityDataSingleView() = default;
    auto get_const_view() const -> ConstView { return *this; }
    auto get_const_view(size_type offset, size_type count) const -> ConstView {
        return slice(offset, count);
    }
};
static_assert(ml::soa_storage_detail::validate_compact_view<SpinnerEntityDataSingleView>());
inline SpinnerEntityDataSingleConstView::SpinnerEntityDataSingleConstView(
    SpinnerEntityDataSingleView const& other)
    : Base{other} {}
struct SpinnerEntityData
    : protected ml::native_soa::StorageState
    , ml::native_soa::StorageOperations {
    using soa_schema = SpinnerEntityDataSchema;
    using Operations = ml::native_soa::StorageOperations;
    using Layout = SpinnerEntityDataSingleLayout;
    using size_type = Layout::size_type;
    using byte_size_type = Layout::byte_size_type;
    inline static constexpr auto capacity_granularity = Layout::capacity_granularity;
    inline static constexpr auto allocation_alignment = Layout::allocation_alignment;
    inline static constexpr auto capacity_block_bound = Layout::capacity_block_bound;
    inline static constexpr auto max_capacity = Layout::max_capacity;
    static constexpr auto layout_bytes(byte_size_type blocks) noexcept -> byte_size_type {
        return Layout::layout_bytes(blocks);
    }
    using View = SpinnerEntityDataSingleView;
    using ConstView = SpinnerEntityDataSingleConstView;
    /* **************************************** */
    // Lifetime
    /* **************************************** */
    SpinnerEntityData() noexcept
        : SpinnerEntityData{std::pmr::get_default_resource()} {}
    explicit SpinnerEntityData(std::pmr::memory_resource* resource) noexcept
        : resource_{resource} {
        assert(resource != nullptr);
    }
    auto get_memory_resource() const noexcept -> std::pmr::memory_resource* { return resource_; }
    ~SpinnerEntityData() { Operations::release_storage(*this); }
    SpinnerEntityData(SpinnerEntityData const&) = delete;
    auto operator=(SpinnerEntityData const&) -> SpinnerEntityData& = delete;
    SpinnerEntityData(SpinnerEntityData&& other) noexcept
        : resource_{other.resource_} {
        Operations::take_storage(*this, other);
    }
    auto operator=(SpinnerEntityData&& other) -> SpinnerEntityData& {
        return Operations::move_assign(*this, other);
    }
  protected:
    template <typename Byte>
    struct DataPointers {
        template <typename T>
        using Element = std::conditional_t<std::is_const_v<Byte>, T const, T>;
        Element<EntityUniqueId>* entity_ids{};
        Element<float>* locations_xs{};
        Element<float>* locations_ys{};
        Element<float>* locations_zs{};
        Element<float>* yaws{};
        Element<std::int16_t>* laser_cooldowns{};
        Element<std::int32_t>* next_fire_point_indices{};
        auto operator+(size_type const offset) const noexcept -> DataPointers {
            if (entity_ids == nullptr) {
                return {};
            }
            return {entity_ids + offset,
                    locations_xs + offset,
                    locations_ys + offset,
                    locations_zs + offset,
                    yaws + offset,
                    laser_cooldowns + offset,
                    next_fire_point_indices + offset};
        }
    };
    template <typename Self>
    auto get_data(this Self& self) noexcept {
        using Byte = std::conditional_t<std::is_const_v<Self>, std::byte const, std::byte>;
        if (self.data_ == nullptr) {
            return DataPointers<Byte>{};
        }
        return make_data_unchecked(static_cast<Byte*>(self.data_), self.capacity_blocks());
    }
    template <typename Self>
    auto get_data(this Self& self, size_type const offset) noexcept {
        return self.get_data() + offset;
    }
  private:
    std::pmr::memory_resource* resource_{};
    friend Operations;
    friend ::ml::soa_storage_detail::StorageRequirements;
    /* **************************************** */
    // Column pointers
    /* **************************************** */
    template <typename Byte>
    static auto make_data_unchecked(Byte* const data, byte_size_type const blocks) noexcept
        -> DataPointers<Byte> {
        ml::native_soa::LayoutCursor cursor{blocks};
        return {cursor.column_pointer(data, Layout::EntityIdsColumn),
                cursor.column_pointer(data, Layout::LocationsXsColumn),
                cursor.column_pointer(data, Layout::LocationsYsColumn),
                cursor.column_pointer(data, Layout::LocationsZsColumn),
                cursor.column_pointer(data, Layout::YawsColumn),
                cursor.column_pointer(data, Layout::LaserCooldownsColumn),
                cursor.column_pointer(data, Layout::NextFirePointIndicesColumn)};
    }
    auto capacity_blocks() const noexcept -> byte_size_type {
        return static_cast<byte_size_type>(capacity_ / capacity_granularity);
    }

    /* **************************************** */
    // Typed mutations and growth
    /* **************************************** */
    void default_construct_columns(size_type const first, size_type const count) {
        auto const columns{make_data_unchecked(data_, capacity_blocks()) + first};
        ml::native_soa::default_construct_n(columns.entity_ids, count);
        ml::native_soa::default_construct_n(columns.locations_xs, count);
        ml::native_soa::default_construct_n(columns.locations_ys, count);
        ml::native_soa::default_construct_n(columns.locations_zs, count);
        ml::native_soa::default_construct_n(columns.yaws, count);
        ml::native_soa::default_construct_n(columns.laser_cooldowns, count);
        ml::native_soa::default_construct_n(columns.next_fire_point_indices, count);
    }
    void swap_remove_columns(size_type const index,
                             size_type const source,
                             size_type const move_count) {
        copy_columns(get_data(), index, source, move_count);
    }
    static void copy_columns(DataPointers<std::byte> const& columns,
                             size_type index,
                             size_type source,
                             size_type move_count) {
        ml::native_soa::copy_n(columns.entity_ids + index, columns.entity_ids + source, move_count);
        ml::native_soa::copy_n(
            columns.locations_xs + index, columns.locations_xs + source, move_count);
        ml::native_soa::copy_n(
            columns.locations_ys + index, columns.locations_ys + source, move_count);
        ml::native_soa::copy_n(
            columns.locations_zs + index, columns.locations_zs + source, move_count);
        ml::native_soa::copy_n(columns.yaws + index, columns.yaws + source, move_count);
        ml::native_soa::copy_n(
            columns.laser_cooldowns + index, columns.laser_cooldowns + source, move_count);
        ml::native_soa::copy_n(columns.next_fire_point_indices + index,
                               columns.next_fire_point_indices + source,
                               move_count);
    }
    void swap_remove_indices(std::span<size_type const> indices) {
        auto const columns{get_data()};
        ml::soa_storage_detail::for_each_removal_run(
            num_, indices, [&](size_type index, size_type source, size_type count) {
                copy_columns(columns, index, source, count);
            });
    }
    template <typename Columns>
    void append_columns(Columns const& source,
                        size_type source_first,
                        size_type first,
                        size_type count)
        requires ml::soa_storage_detail::SoaSourceFor<Columns, SpinnerEntityData, size_type>
    {
        auto const destination{get_data(first)};
        ml::native_soa::copy_n(destination.entity_ids,
                               ml::native_soa::source_data(source.entity_ids()) + source_first,
                               count);
        ml::native_soa::copy_n(destination.locations_xs,
                               ml::native_soa::source_data(source.view_locations().xs()) +
                                   source_first,
                               count);
        ml::native_soa::copy_n(destination.locations_ys,
                               ml::native_soa::source_data(source.view_locations().ys()) +
                                   source_first,
                               count);
        ml::native_soa::copy_n(destination.locations_zs,
                               ml::native_soa::source_data(source.view_locations().zs()) +
                                   source_first,
                               count);
        ml::native_soa::copy_n(
            destination.yaws, ml::native_soa::source_data(source.yaws()) + source_first, count);
        ml::native_soa::copy_n(destination.laser_cooldowns,
                               ml::native_soa::source_data(source.laser_cooldowns()) + source_first,
                               count);
        ml::native_soa::copy_n(destination.next_fire_point_indices,
                               ml::native_soa::source_data(source.next_fire_point_indices()) +
                                   source_first,
                               count);
    }
    template <typename Columns>
    void copy_columns_from(Columns const& source,
                           size_type source_first,
                           size_type first,
                           size_type count)
        requires ml::soa_storage_detail::SoaSourceFor<Columns, SpinnerEntityData, size_type>
    {
        auto const destination{get_data(first)};
        ml::native_soa::move_n(destination.entity_ids,
                               ml::native_soa::source_data(source.entity_ids()) + source_first,
                               count);
        ml::native_soa::move_n(destination.locations_xs,
                               ml::native_soa::source_data(source.view_locations().xs()) +
                                   source_first,
                               count);
        ml::native_soa::move_n(destination.locations_ys,
                               ml::native_soa::source_data(source.view_locations().ys()) +
                                   source_first,
                               count);
        ml::native_soa::move_n(destination.locations_zs,
                               ml::native_soa::source_data(source.view_locations().zs()) +
                                   source_first,
                               count);
        ml::native_soa::move_n(
            destination.yaws, ml::native_soa::source_data(source.yaws()) + source_first, count);
        ml::native_soa::move_n(destination.laser_cooldowns,
                               ml::native_soa::source_data(source.laser_cooldowns()) + source_first,
                               count);
        ml::native_soa::move_n(destination.next_fire_point_indices,
                               ml::native_soa::source_data(source.next_fire_point_indices()) +
                                   source_first,
                               count);
    }
    void copy_live_columns(std::byte* const new_data, size_type const new_capacity) noexcept {
        auto const old_blocks{capacity_blocks()};
        auto const new_blocks{static_cast<byte_size_type>(new_capacity / capacity_granularity)};
        auto const source{make_data_unchecked(static_cast<std::byte const*>(data_), old_blocks)};
        auto const destination{make_data_unchecked(new_data, new_blocks)};
        ml::native_soa::copy_n(destination.entity_ids, source.entity_ids, num_);
        ml::native_soa::copy_n(destination.locations_xs, source.locations_xs, num_);
        ml::native_soa::copy_n(destination.locations_ys, source.locations_ys, num_);
        ml::native_soa::copy_n(destination.locations_zs, source.locations_zs, num_);
        ml::native_soa::copy_n(destination.yaws, source.yaws, num_);
        ml::native_soa::copy_n(destination.laser_cooldowns, source.laser_cooldowns, num_);
        ml::native_soa::copy_n(
            destination.next_fire_point_indices, source.next_fire_point_indices, num_);
    }
  public:
};
} // namespace ioj::sim
