// This file is autogenerated. Do not edit by hand.
// Edit lispb/schema and regenerate it instead.

#pragma once

#include "sandbox/core/native_soa/storage.h"

#include <utility>

namespace ioj::sim::collision {

struct WorldAABBsColumnsSingleView;
struct WorldAABBsColumnsSingleConstView;
struct WorldAABBsColumnsSingleLayout {
    using size_type = std::int32_t;
    using byte_size_type = std::size_t;

    inline static constexpr size_type capacity_granularity{
        ml::native_soa::LayoutPolicy::capacity_granularity};
    inline static constexpr byte_size_type column_gap{ml::native_soa::LayoutPolicy::column_gap};

    template <typename T>
    using ColLayout = ml::native_soa::ColumnLayout<T>;
    inline static constexpr ml::native_soa::ColumnLayoutStart LayoutStart{};

    inline static constexpr ColLayout<float> MinXsColumn{LayoutStart};
    inline static constexpr ColLayout<float> MinYsColumn{MinXsColumn};
    inline static constexpr ColLayout<float> MinZsColumn{MinYsColumn};
    inline static constexpr ColLayout<float> MaxXsColumn{MinZsColumn};
    inline static constexpr ColLayout<float> MaxYsColumn{MaxXsColumn};
    inline static constexpr ColLayout<float> MaxZsColumn{MaxYsColumn};

    inline static constexpr byte_size_type allocation_alignment{MaxZsColumn.allocation_alignment};

    // Conservative per-block bound for checked capacity arithmetic; gaps do not scale with
    // capacity.
    inline static constexpr byte_size_type capacity_block_bound{
        ml::native_soa::capacity_block_bound(MaxZsColumn)};
    inline static constexpr size_type max_capacity{
        ml::native_soa::maximum_capacity(capacity_block_bound)};
    static constexpr auto layout_bytes(byte_size_type blocks) noexcept -> byte_size_type {
        return blocks == 0 ? 0 : MaxZsColumn.data_end(blocks);
    }
    static_assert(
        allocation_alignment <= std::numeric_limits<std::uint32_t>::max(),
        "Single-allocation alignment must fit the allocator's 32-bit alignment argument.");
    static_assert(max_capacity >= capacity_granularity);
};

template <bool Const>
struct WorldAABBsColumnsSingleViewImpl : ml::native_soa::CompactViewState<Const> {
    using Base = ml::native_soa::CompactViewState<Const>;
    using Base::Base;
    using Base::validate;
    using size_type = typename Base::size_type;
    template <typename T>
    using Element = typename Base::template Element<T>;
    using View = WorldAABBsColumnsSingleView;
    using ConstView = WorldAABBsColumnsSingleConstView;
    WorldAABBsColumnsSingleViewImpl() = default;
    template <bool Enabled = Const>
    WorldAABBsColumnsSingleViewImpl(WorldAABBsColumnsSingleViewImpl<false> const& other)
        requires Enabled
        : Base{other} {}
  protected:
    using Base::capacity_blocks;
    using Base::column_data;
    using Base::column_data_unchecked;
    using Base::count_;
    using Base::offset_;
    using Base::state_;
  public:
    auto min_xs() const -> std::span<Element<float>> {
        return {this->template column_data<float>(
                    WorldAABBsColumnsSingleLayout::MinXsColumn.offset(capacity_blocks())),
                static_cast<std::size_t>(count_)};
    }
    auto min_ys() const -> std::span<Element<float>> {
        return {this->template column_data<float>(
                    WorldAABBsColumnsSingleLayout::MinYsColumn.offset(capacity_blocks())),
                static_cast<std::size_t>(count_)};
    }
    auto min_zs() const -> std::span<Element<float>> {
        return {this->template column_data<float>(
                    WorldAABBsColumnsSingleLayout::MinZsColumn.offset(capacity_blocks())),
                static_cast<std::size_t>(count_)};
    }
    auto max_xs() const -> std::span<Element<float>> {
        return {this->template column_data<float>(
                    WorldAABBsColumnsSingleLayout::MaxXsColumn.offset(capacity_blocks())),
                static_cast<std::size_t>(count_)};
    }
    auto max_ys() const -> std::span<Element<float>> {
        return {this->template column_data<float>(
                    WorldAABBsColumnsSingleLayout::MaxYsColumn.offset(capacity_blocks())),
                static_cast<std::size_t>(count_)};
    }
    auto max_zs() const -> std::span<Element<float>> {
        return {this->template column_data<float>(
                    WorldAABBsColumnsSingleLayout::MaxZsColumn.offset(capacity_blocks())),
                static_cast<std::size_t>(count_)};
    }
    template <typename Func>
    void each_column(Func&& func) const {
        func(min_xs());
        func(min_ys());
        func(min_zs());
        func(max_xs());
        func(max_ys());
        func(max_zs());
    }
};
struct WorldAABBsColumnsSingleConstView : WorldAABBsColumnsSingleViewImpl<true> {
    using Base = WorldAABBsColumnsSingleViewImpl<true>;
    using Base::Base;
    using View = WorldAABBsColumnsSingleView;
    using ConstView = WorldAABBsColumnsSingleConstView;
    WorldAABBsColumnsSingleConstView() = default;
    WorldAABBsColumnsSingleConstView(WorldAABBsColumnsSingleView const& other);
    auto get_const_view() const -> ConstView { return *this; }
    auto get_const_view(size_type offset, size_type count) const -> ConstView {
        return slice(offset, count);
    }
};
static_assert(ml::soa_storage_detail::validate_compact_view<WorldAABBsColumnsSingleConstView>());
struct WorldAABBsColumnsSingleView : WorldAABBsColumnsSingleViewImpl<false> {
    using Base = WorldAABBsColumnsSingleViewImpl<false>;
    using Base::Base;
    using View = WorldAABBsColumnsSingleView;
    using ConstView = WorldAABBsColumnsSingleConstView;
    WorldAABBsColumnsSingleView() = default;
    auto get_const_view() const -> ConstView { return *this; }
    auto get_const_view(size_type offset, size_type count) const -> ConstView {
        return slice(offset, count);
    }
};
static_assert(ml::soa_storage_detail::validate_compact_view<WorldAABBsColumnsSingleView>());
inline WorldAABBsColumnsSingleConstView::WorldAABBsColumnsSingleConstView(
    WorldAABBsColumnsSingleView const& other)
    : Base{other} {}
struct WorldAABBs
    : protected ml::native_soa::StorageState
    , private ml::native_soa::StorageOperations {
    using Operations = ml::native_soa::StorageOperations;
    using Operations::add_defaulted;
    using Operations::add_uninitialised;
    using Operations::allocated_bytes;
    using Operations::append_from;
    using Operations::capacity;
    using Operations::copy_element;
    using Operations::copy_elements;
    using Operations::is_empty;
    using Operations::num;
    using Operations::remove_at_swap;
    using Operations::reserve;
    using Operations::reset;
    using Operations::set_num;
    using Layout = WorldAABBsColumnsSingleLayout;
    using size_type = Layout::size_type;
    using byte_size_type = Layout::byte_size_type;
    inline static constexpr auto capacity_granularity = Layout::capacity_granularity;
    inline static constexpr auto allocation_alignment = Layout::allocation_alignment;
    inline static constexpr auto capacity_block_bound = Layout::capacity_block_bound;
    inline static constexpr auto max_capacity = Layout::max_capacity;
    static constexpr auto layout_bytes(byte_size_type blocks) noexcept -> byte_size_type {
        return Layout::layout_bytes(blocks);
    }
    using View = WorldAABBsColumnsSingleView;
    using ConstView = WorldAABBsColumnsSingleConstView;
    template <typename Source>
    inline static constexpr bool accepts_source = requires(Source const& source) {
        { source.num() } -> std::convertible_to<size_type>;
        source.validate();
        { ml::native_soa::source_data(source.min_xs()) } -> std::convertible_to<float const*>;
        { ml::native_soa::source_data(source.min_ys()) } -> std::convertible_to<float const*>;
        { ml::native_soa::source_data(source.min_zs()) } -> std::convertible_to<float const*>;
        { ml::native_soa::source_data(source.max_xs()) } -> std::convertible_to<float const*>;
        { ml::native_soa::source_data(source.max_ys()) } -> std::convertible_to<float const*>;
        { ml::native_soa::source_data(source.max_zs()) } -> std::convertible_to<float const*>;
    };
    /* **************************************** */
    // Lifetime
    /* **************************************** */
    WorldAABBs() noexcept = default;
    ~WorldAABBs() { ml::native_soa::free(data_, allocation_alignment); }
    WorldAABBs(WorldAABBs const&) = delete;
    auto operator=(WorldAABBs const&) -> WorldAABBs& = delete;
    WorldAABBs(WorldAABBs&& other) noexcept
        : StorageState{std::exchange(other.data_, nullptr),
                       std::exchange(other.num_, 0),
                       std::exchange(other.capacity_, 0)} {}
    auto operator=(WorldAABBs&& other) noexcept -> WorldAABBs& {
        if (this != &other) {
            ml::native_soa::free(data_, allocation_alignment);
            data_ = std::exchange(other.data_, nullptr);
            num_ = std::exchange(other.num_, 0);
            capacity_ = std::exchange(other.capacity_, 0);
        }
        return *this;
    }
  protected:
    template <typename Byte>
    struct DataPointers {
        template <typename T>
        using Element = std::conditional_t<std::is_const_v<Byte>, T const, T>;
        Element<float>* min_xs{};
        Element<float>* min_ys{};
        Element<float>* min_zs{};
        Element<float>* max_xs{};
        Element<float>* max_ys{};
        Element<float>* max_zs{};
        auto operator+(size_type const offset) const noexcept -> DataPointers {
            if (min_xs == nullptr) {
                return {};
            }
            return {min_xs + offset,
                    min_ys + offset,
                    min_zs + offset,
                    max_xs + offset,
                    max_ys + offset,
                    max_zs + offset};
        }
    };
    template <typename Self>
    auto get_data(this Self& self) noexcept {
        using Byte = std::conditional_t<std::is_const_v<Self>, std::byte const, std::byte>;
        if (self.data_ == nullptr) {
            return DataPointers<Byte>{};
        }
        return make_data_unchecked(static_cast<Byte*>(self.data_), self.capacity_blocks());
    }
    template <typename Self>
    auto get_data(this Self& self, size_type const offset) noexcept {
        return self.get_data() + offset;
    }
  private:
    friend struct ml::native_soa::StorageOperations;
    /* **************************************** */
    // Column pointers
    /* **************************************** */
    template <typename Byte>
    static auto make_data_unchecked(Byte* const data, byte_size_type const blocks) noexcept
        -> DataPointers<Byte> {
        ml::native_soa::LayoutCursor cursor{blocks};
        auto const pointer_at = [data](auto const& column, byte_size_type offset) noexcept {
            using Column = std::remove_cvref_t<decltype(column)>;
            using Pointer = std::conditional_t<std::is_const_v<Byte>,
                                               typename Column::const_pointer,
                                               typename Column::pointer>;
            return std::launder(reinterpret_cast<Pointer>(data + offset));
        };
        return {pointer_at(Layout::MinXsColumn, cursor.advance(Layout::MinXsColumn)),
                pointer_at(Layout::MinYsColumn, cursor.advance(Layout::MinYsColumn)),
                pointer_at(Layout::MinZsColumn, cursor.advance(Layout::MinZsColumn)),
                pointer_at(Layout::MaxXsColumn, cursor.advance(Layout::MaxXsColumn)),
                pointer_at(Layout::MaxYsColumn, cursor.advance(Layout::MaxYsColumn)),
                pointer_at(Layout::MaxZsColumn, cursor.advance(Layout::MaxZsColumn))};
    }
    auto capacity_blocks() const noexcept -> byte_size_type {
        return static_cast<byte_size_type>(capacity_ / capacity_granularity);
    }

    /* **************************************** */
    // Typed mutations and growth
    /* **************************************** */
    void default_construct_columns(size_type const first, size_type const count) {
        auto const columns{make_data_unchecked(data_, capacity_blocks()) + first};
        ml::native_soa::default_construct_n(columns.min_xs, count);
        ml::native_soa::default_construct_n(columns.min_ys, count);
        ml::native_soa::default_construct_n(columns.min_zs, count);
        ml::native_soa::default_construct_n(columns.max_xs, count);
        ml::native_soa::default_construct_n(columns.max_ys, count);
        ml::native_soa::default_construct_n(columns.max_zs, count);
    }
    void swap_remove_columns(size_type const index,
                             size_type const source,
                             size_type const move_count) {
        copy_columns(get_data(), index, source, move_count);
    }
    static void copy_columns(DataPointers<std::byte> const& columns,
                             size_type index,
                             size_type source,
                             size_type move_count) {
        ml::native_soa::copy_n(columns.min_xs + index, columns.min_xs + source, move_count);
        ml::native_soa::copy_n(columns.min_ys + index, columns.min_ys + source, move_count);
        ml::native_soa::copy_n(columns.min_zs + index, columns.min_zs + source, move_count);
        ml::native_soa::copy_n(columns.max_xs + index, columns.max_xs + source, move_count);
        ml::native_soa::copy_n(columns.max_ys + index, columns.max_ys + source, move_count);
        ml::native_soa::copy_n(columns.max_zs + index, columns.max_zs + source, move_count);
    }
    void swap_remove_indices(std::span<size_type const> indices) {
        auto const columns{get_data()};
        ml::soa_storage_detail::for_each_removal_run(
            num_,
            indices,
            ml::native_soa::require,
            [&](size_type index, size_type source, size_type count) {
                copy_columns(columns, index, source, count);
            });
    }
    template <typename Columns>
    void append_columns(Columns const& source,
                        size_type source_first,
                        size_type first,
                        size_type count) {
        auto const destination{get_data(first)};
        ml::native_soa::copy_n(
            destination.min_xs, ml::native_soa::source_data(source.min_xs()) + source_first, count);
        ml::native_soa::copy_n(
            destination.min_ys, ml::native_soa::source_data(source.min_ys()) + source_first, count);
        ml::native_soa::copy_n(
            destination.min_zs, ml::native_soa::source_data(source.min_zs()) + source_first, count);
        ml::native_soa::copy_n(
            destination.max_xs, ml::native_soa::source_data(source.max_xs()) + source_first, count);
        ml::native_soa::copy_n(
            destination.max_ys, ml::native_soa::source_data(source.max_ys()) + source_first, count);
        ml::native_soa::copy_n(
            destination.max_zs, ml::native_soa::source_data(source.max_zs()) + source_first, count);
    }
    void reallocate(size_type const new_capacity) {
        auto* const new_data{ml::native_soa::allocate(
            layout_bytes(static_cast<byte_size_type>(new_capacity / capacity_granularity)),
            static_cast<std::uint32_t>(allocation_alignment))};
        if (num_ > 0) {
            auto const old_blocks{capacity_blocks()};
            auto const new_blocks{static_cast<byte_size_type>(new_capacity / capacity_granularity)};
            auto const source{
                make_data_unchecked(static_cast<std::byte const*>(data_), old_blocks)};
            auto const destination{make_data_unchecked(new_data, new_blocks)};
            ml::native_soa::copy_n(destination.min_xs, source.min_xs, num_);
            ml::native_soa::copy_n(destination.min_ys, source.min_ys, num_);
            ml::native_soa::copy_n(destination.min_zs, source.min_zs, num_);
            ml::native_soa::copy_n(destination.max_xs, source.max_xs, num_);
            ml::native_soa::copy_n(destination.max_ys, source.max_ys, num_);
            ml::native_soa::copy_n(destination.max_zs, source.max_zs, num_);
        }
        ml::native_soa::free(data_, allocation_alignment);
        data_ = new_data;
        capacity_ = new_capacity;
    }
  public:
    template <typename Self>
    using ViewFor =
        std::conditional_t<std::is_const_v<std::remove_reference_t<Self>>, ConstView, View>;
    template <typename Self>
    auto get_view(this Self&& self) -> ViewFor<Self>
        requires std::is_lvalue_reference_v<Self>
    {
        return {&self, 0, self.num()};
    }
    template <typename Self>
    auto get_view(this Self&& self, size_type offset, size_type count) -> ViewFor<Self>
        requires std::is_lvalue_reference_v<Self>
    {
        return {&self, offset, count};
    }
    template <typename Self>
    auto slice(this Self&& self, size_type offset, size_type count) -> ViewFor<Self>
        requires std::is_lvalue_reference_v<Self>
    {
        return self.get_view(offset, count);
    }
    template <typename Self>
    auto left(this Self&& self, size_type count) -> ViewFor<Self>
        requires std::is_lvalue_reference_v<Self>
    {
        return self.get_view().left(count);
    }
    template <typename Self>
    auto right(this Self&& self, size_type count) -> ViewFor<Self>
        requires std::is_lvalue_reference_v<Self>
    {
        return self.get_view().right(count);
    }
    template <typename Self>
    auto get_const_view(this Self&& self) -> ConstView
        requires std::is_lvalue_reference_v<Self>
    {
        return {&self, 0, self.num()};
    }
    template <typename Self>
    auto get_const_view(this Self&& self, size_type offset, size_type count) -> ConstView
        requires std::is_lvalue_reference_v<Self>
    {
        return {&self, offset, count};
    }
};
} // namespace ioj::sim::collision
