#include "renderer.h"

#include <string_view>
#include <type_traits>
#include <utility>
#include <vector>

namespace slate_codegen::detail {
namespace {

auto split_qualified_name(std::string_view name) -> std::vector<std::string> {
    std::vector<std::string> result;
    while (true) {
        auto const separator{name.find("::")};
        result.emplace_back(name.substr(0, separator));
        if (separator == std::string_view::npos) {
            return result;
        }
        name.remove_prefix(separator + 2);
    }
}

class Renderer {
  public:
    explicit Renderer(std::string source_path) : source_path_{std::move(source_path)} {}

    auto render(WidgetClass const& widget_class) -> std::string {
        auto const owner_parts{split_qualified_name(widget_class.owner)};
        auto const builder_name{owner_parts.back() + "Builder"};

        append_line(0, "// This file is autogenerated. Do not edit by hand.");
        append_line(0, "// Source: " + source_path_);
        append_line(0, {});
        append_line(0, "#pragma once");
        if (has_callbacks(widget_class)) {
            append_line(0, {});
            append_line(0, "#include <utility>");
        }
        append_line(0, {});
        append_line(0, generated_namespace(owner_parts));
        append_line(0, {});
        append_line(0, "struct " + builder_name + " {");
        append_line(4, "using ThisClass = ::" + widget_class.owner + ";");
        append_line(0, {});
        append_line(4,
                    "explicit " + builder_name + "(ThisClass& self) : self_{self} {}");

        for (auto const& function : widget_class.functions) {
            append_line(0, {});
            render_function(function);
        }

        append_line(0, {});
        append_line(2, "private:");
        append_line(4, "ThisClass& self_;");
        append_line(0, "};");
        append_line(0, {});
        append_line(0, "}");
        return output_;
    }

  private:
    static auto has_callbacks(WidgetClass const& widget_class) -> bool {
        for (auto const& function : widget_class.functions) {
            if (!function.callbacks.empty()) {
                return true;
            }
        }
        return false;
    }

    static auto generated_namespace(std::vector<std::string> const& owner_parts) -> std::string {
        std::string result{"namespace SlateGenerated"};
        for (std::size_t index{}; index + 1 < owner_parts.size(); ++index) {
            result += "::" + owner_parts[index];
        }
        result += " {";
        return result;
    }

    void append_line(std::size_t const indent, std::string_view const text) {
        output_.append(indent, ' ');
        output_.append(text);
        output_ += '\n';
    }

    void append_source_line(SourceSpan const span) {
        append_line(0,
                    "#line " + std::to_string(span.line) + " \"" +
                        escape_cpp_string(source_path_) + "\"");
    }

    void render_function(SlateFunction const& function) {
        std::string declaration{"auto " + function.name + "("};
        for (std::size_t index{}; index < function.callbacks.size(); ++index) {
            if (index != 0) {
                declaration += ", ";
            }
            declaration += "auto&& " + function.callbacks[index];
        }
        declaration += ") {";
        append_line(4, declaration);
        append_line(8, "return");
        append_source_line(function.root.span);
        render_child(function.root, 12);
        output_.pop_back();
        output_ += ";\n";
        append_line(4, "}");
    }

    void render_child(Child const& child, std::size_t const indent) {
        std::visit(
            [&](auto const& value) {
                using T = std::decay_t<decltype(value)>;
                if constexpr (std::is_same_v<T, Widget>) {
                    render_widget(value, indent);
                } else {
                    render_vbox(value, indent);
                }
            },
            child.value);
    }

    void render_widget(Widget const& widget, std::size_t const indent) {
        append_line(indent, "SNew(" + widget.type + ")");
        for (auto const& argument : widget.arguments) {
            auto const invocation{render_argument(argument)};
            if (indent + 4 + invocation.size() <= 100) {
                append_line(indent + 4, invocation);
            } else {
                auto const opening_parenthesis{invocation.find('(')};
                append_line(indent + 4, invocation.substr(0, opening_parenthesis + 1));
                append_line(indent + 8, invocation.substr(opening_parenthesis + 1));
            }
        }
        if (widget.content) {
            append_line(indent + 4, "[");
            render_child(*widget.content, indent + 8);
            append_line(indent + 4, "]");
        }
        for (auto const& slot : widget.named_slots) {
            append_line(indent + 4, "." + slot.name + "()");
            append_line(indent + 4, "[");
            render_child(*slot.child, indent + 8);
            append_line(indent + 4, "]");
        }
    }

    void render_vbox(VBox const& box, std::size_t const indent) {
        append_line(indent, "SNew(SVerticalBox)");
        for (auto const& slot : box.slots) {
            append_line(indent + 4, "+ " + render_slot_helper(slot));
            if (slot.horizontal_alignment) {
                append_line(indent + 8,
                            ".HAlign(" + horizontal_alignment(*slot.horizontal_alignment) + ")");
            }
            if (slot.vertical_alignment) {
                append_line(indent + 8,
                            ".VAlign(" + vertical_alignment(*slot.vertical_alignment) + ")");
            }
            append_line(indent + 8, "[");
            render_child(*slot.child, indent + 12);
            append_line(indent + 8, "]");
        }
    }

    static auto render_value(Value const& value) -> std::string {
        if (value.kind == ValueKind::text) {
            return "FText::FromString(TEXT(\"" + escape_cpp_string(value.text) + "\"))";
        }
        return value.text;
    }

    static auto render_argument(Argument const& argument) -> std::string {
        auto const& value{argument.value};
        if (value.kind == ValueKind::callback) {
            return "." + argument.name + "_Lambda(std::forward<decltype(" + value.text + ")>(" +
                   value.text + "))";
        }
        if (value.kind == ValueKind::method) {
            return "." + argument.name + "(&self_, &ThisClass::" + value.text + ")";
        }
        if (value.kind == ValueKind::uobject) {
            return "." + argument.name + "_UObject(&self_, &ThisClass::" + value.text + ")";
        }
        return "." + argument.name + "(" + render_value(value) + ")";
    }

    static auto render_slot_helper(BoxSlot const& slot) -> std::string {
        auto const padding{render_padding(slot.padding)};
        if (!slot.fill) {
            return padding.empty() ? "SandboxUI::Slate::vbox_auto_slot()"
                                   : "SandboxUI::Slate::vbox_auto_slot(" + padding + ")";
        }
        if (slot.weight) {
            auto const weight{float_literal(*slot.weight)};
            return padding.empty() ? "SandboxUI::Slate::vbox_fill_slot(" + weight + ")"
                                   : "SandboxUI::Slate::vbox_fill_slot(" + weight + ", " +
                                         padding + ")";
        }
        return padding.empty() ? "SandboxUI::Slate::vbox_fill_slot()"
                               : "SandboxUI::Slate::vbox_fill_slot(1.0f, " + padding + ")";
    }

    static auto render_padding(std::vector<std::string> const& values) -> std::string {
        if (values.empty()) {
            return {};
        }
        std::string result{"FMargin{"};
        for (std::size_t index{}; index < values.size(); ++index) {
            if (index != 0) {
                result += ", ";
            }
            result += float_literal(values[index]);
        }
        result += '}';
        return result;
    }

    static auto float_literal(std::string value) -> std::string {
        if (value.find('.') == std::string::npos) {
            value += ".0";
        }
        value += 'f';
        return value;
    }

    static auto horizontal_alignment(std::string_view const value) -> std::string {
        if (value == "left") {
            return "HAlign_Left";
        }
        if (value == "center") {
            return "HAlign_Center";
        }
        if (value == "right") {
            return "HAlign_Right";
        }
        return "HAlign_Fill";
    }

    static auto vertical_alignment(std::string_view const value) -> std::string {
        if (value == "top") {
            return "VAlign_Top";
        }
        if (value == "center") {
            return "VAlign_Center";
        }
        if (value == "bottom") {
            return "VAlign_Bottom";
        }
        return "VAlign_Fill";
    }

    static auto escape_cpp_string(std::string_view const value) -> std::string {
        std::string result;
        for (auto const character : value) {
            switch (character) {
            case '\\':
                result += "\\\\";
                break;
            case '"':
                result += "\\\"";
                break;
            case '\n':
                result += "\\n";
                break;
            case '\r':
                result += "\\r";
                break;
            case '\t':
                result += "\\t";
                break;
            default:
                result += character;
                break;
            }
        }
        return result;
    }

    std::string source_path_;
    std::string output_;
};

}

auto render(std::string source_path, WidgetClass const& widget_class) -> std::string {
    return Renderer{std::move(source_path)}.render(widget_class);
}

}
