// This file is autogenerated. Do not edit by hand.
// Edit lispb/schema and regenerate it instead.

#include "ioj/sim/fighters/phase_interface.h"

#include "ioj/sim/fighters/sim.h"

namespace ioj::sim::fighters {
PhaseInterface::PhaseInterface(Sim& new_target)
    : simulation{new_target} {}

void PhaseInterface::begin_play() {
    simulation.begin_play();
}

void PhaseInterface::commit_orders() {
    simulation.commit_orders();
}

void PhaseInterface::prepare_tick(float const dt) {
    simulation.prepare_tick(dt);
}

void PhaseInterface::think(float const dt, ml::FrameScratch& scratch) {
    simulation.think(dt, scratch);
}

void PhaseInterface::apply_movement(ml::FrameScratch& scratch) {
    simulation.apply_movement(scratch);
}

void PhaseInterface::generate_fire_commands(ml::FrameScratch& scratch) {
    simulation.generate_fire_commands(scratch);
}

void PhaseInterface::commit_spawns() {
    simulation.commit_spawns();
}

void PhaseInterface::resolve_damage_events() {
    simulation.resolve_damage_events();
}

void PhaseInterface::publish_deaths() {
    simulation.publish_deaths();
}

void PhaseInterface::remove_components() {
    simulation.remove_components();
}

void PhaseInterface::remove_entities() {
    simulation.remove_entities();
}

void PhaseInterface::finish_action() {
    simulation.finish_action();
}
} // namespace ioj::sim::fighters
