// clang-format off
// This file is autogenerated. Do not edit by hand.
// Edit Codegen/manifests and regenerate it instead.

#include "SpaceGame/ships/fighters/TestCapitalShipFightersPhaseInterface.h"

#include "SpaceGame/ships/fighters/TestCapitalShipFightersSimulation.h"

namespace ml::test_capital_ship_fighters {
void PhaseInterface::bind(ml::test_capital_ship_fighters::Simulation& new_target) {
    simulation = &new_target;
}

void PhaseInterface::clear_runtime_state() {
    simulation->clear_runtime_state();
}

void PhaseInterface::begin_play() {
    simulation->begin_play();
}

void PhaseInterface::begin_tick() {
    simulation->begin_tick();
}

void PhaseInterface::update_timers(float const dt) {
    simulation->update_timers(dt);
}

void PhaseInterface::make_decisions() {
    simulation->make_decisions();
}

void PhaseInterface::move(float const dt) {
    simulation->move(dt);
}

void PhaseInterface::queue_commands() {
    simulation->queue_commands();
}

void PhaseInterface::resolve_damage_events() {
    simulation->resolve_damage_events();
}

void PhaseInterface::update_entity_registry() {
    simulation->update_entity_registry();
}

void PhaseInterface::sync_from_registry() {
    simulation->sync_from_registry();
}

void PhaseInterface::end_tick() {
    simulation->end_tick();
}
} // namespace ml::test_capital_ship_fighters
// clang-format on
