// clang-format off
// This file is autogenerated. Do not edit by hand.
// Edit Codegen/manifests and regenerate it instead.

#pragma once

#include "SandboxCore/array_utils.h"

#include "Components/PrimitiveComponent.h"
#include "Containers/Array.h"
#include "Containers/ArrayView.h"
#include "CoreMinimal.h"
#include "Engine/EngineTypes.h"
#include "GameFramework/Actor.h"
#include "Math/Transform.h"

#include <utility>

namespace ml::ioj {
struct FStaticCollisionSourcesView;
struct FStaticCollisionSourcesConstView;

struct SPACEGAME_API FStaticCollisionSourcesConstView {
    using View = FStaticCollisionSourcesView;
    using ConstView = FStaticCollisionSourcesConstView;

    template <typename TFunc>
    auto apply_arrays(this auto&& self, TFunc&& func) -> decltype(auto) {
        return std::forward<TFunc>(func)(
            self.actors,
            self.components,
            self.harvested_transforms,
            self.original_collision_modes
        );
    }

    auto get_view() const -> ConstView;
    auto get_view(int32 const offset, int32 const count) const -> ConstView;
    auto get_const_view() const -> ConstView;
    auto get_const_view(int32 const offset, int32 const count) const -> ConstView;
    auto num() const noexcept -> int32;
    auto is_empty() const noexcept -> bool;
    void validate_array_sizes() const;
    auto slice(int32 const offset, int32 const count) const -> ConstView;
    auto left(int32 const count) const -> ConstView;
    auto right(int32 const count) const -> ConstView;

    TConstArrayView<TWeakObjectPtr<AActor>> actors;
    TConstArrayView<TWeakObjectPtr<UPrimitiveComponent>> components;
    TConstArrayView<FTransform> harvested_transforms;
    TConstArrayView<ECollisionEnabled::Type> original_collision_modes;
};

struct SPACEGAME_API FStaticCollisionSourcesView {
    using View = FStaticCollisionSourcesView;
    using ConstView = FStaticCollisionSourcesConstView;

    template <typename TFunc>
    auto apply_arrays(this auto&& self, TFunc&& func) -> decltype(auto) {
        return std::forward<TFunc>(func)(
            self.actors,
            self.components,
            self.harvested_transforms,
            self.original_collision_modes
        );
    }

    auto get_view() -> View;
    auto get_view(int32 const offset, int32 const count) -> View;
    auto get_view() const -> ConstView;
    auto get_view(int32 const offset, int32 const count) const -> ConstView;
    auto get_const_view() const -> ConstView;
    auto get_const_view(int32 const offset, int32 const count) const -> ConstView;
    auto num() const noexcept -> int32;
    auto is_empty() const noexcept -> bool;
    void validate_array_sizes() const;
    auto slice(int32 const offset, int32 const count) -> View;
    auto left(int32 const count) -> View;
    auto right(int32 const count) -> View;
    auto slice(int32 const offset, int32 const count) const -> ConstView;
    auto left(int32 const count) const -> ConstView;
    auto right(int32 const count) const -> ConstView;

    TArrayView<TWeakObjectPtr<AActor>> actors;
    TArrayView<TWeakObjectPtr<UPrimitiveComponent>> components;
    TArrayView<FTransform> harvested_transforms;
    TArrayView<ECollisionEnabled::Type> original_collision_modes;
};

struct SPACEGAME_API FStaticCollisionSources {
    using View = FStaticCollisionSourcesView;
    using ConstView = FStaticCollisionSourcesConstView;

    void add(AActor* actor, UPrimitiveComponent* component, FTransform const& harvested_transform, ECollisionEnabled::Type const original_collision_mode);

    void reset();

    void apply_permutation(TArrayView<int32> indices);

    template <typename Compare>
    void sort(Compare&& compare, TArrayView<int32> scratch_indices) {
        validate_array_sizes();
        auto const n{num()};
        check(scratch_indices.Num() == n);
        ml::fill_indices(scratch_indices);
        // indices[new_index] is the old row index that belongs at new_index.
        scratch_indices.Sort([this, &compare](int32 const lhs, int32 const rhs) {
            return compare(*this, lhs, rhs);
        });
        apply_permutation(scratch_indices);
    }

    template <auto Compare>
    void sort(TArrayView<int32> scratch_indices) {
        validate_array_sizes();
        auto const n{num()};
        check(scratch_indices.Num() == n);
        ml::fill_indices(scratch_indices);
        // indices[new_index] is the old row index that belongs at new_index.
        scratch_indices.Sort([this](int32 const lhs, int32 const rhs) {
            return Compare(*this, lhs, rhs);
        });
        apply_permutation(scratch_indices);
    }

    template <typename TFunc>
    auto apply_arrays(this auto&& self, TFunc&& func) -> decltype(auto) {
        return std::forward<TFunc>(func)(
            self.actors,
            self.components,
            self.harvested_transforms,
            self.original_collision_modes
        );
    }

    template <typename Self, typename Other, typename TFunc>
    auto apply_array_pairs(this Self&& self, Other&& other, TFunc&& func)
        -> decltype(auto) {
        return std::forward<TFunc>(func)(
            self.actors, other.actors,
            self.components, other.components,
            self.harvested_transforms, other.harvested_transforms,
            self.original_collision_modes, other.original_collision_modes
        );
    }

    auto get_view() -> View;
    auto get_view(int32 const offset, int32 const count) -> View;
    auto get_view() const -> ConstView;
    auto get_view(int32 const offset, int32 const count) const -> ConstView;
    auto get_const_view() const -> ConstView;
    auto get_const_view(int32 const offset, int32 const count) const -> ConstView;
    auto num() const noexcept -> int32;
    auto is_empty() const noexcept -> bool;
    void validate_array_sizes() const;
    auto slice(int32 const offset, int32 const count) -> View;
    auto left(int32 const count) -> View;
    auto right(int32 const count) -> View;
    auto slice(int32 const offset, int32 const count) const -> ConstView;
    auto left(int32 const count) const -> ConstView;
    auto right(int32 const count) const -> ConstView;

    TArray<TWeakObjectPtr<AActor>> actors;
    TArray<TWeakObjectPtr<UPrimitiveComponent>> components;
    TArray<FTransform> harvested_transforms;
    TArray<ECollisionEnabled::Type> original_collision_modes;
};
} // namespace ml::ioj
// clang-format on
