// clang-format off
// This file is autogenerated. Do not edit by hand.
// Edit Codegen/manifest.py and regenerate it instead.

#pragma once

#include "Sandbox/batch_game/TestCapitalShipFighterOrder.h"
#include "Sandbox/batch_game/TestCapitalShipFightersTask.h"
#include "Sandbox/batch_game/test_entity_registry/RegistryEntityHandle.h"

#include "SandboxCore/array_utils.h"
#include "SandboxCore/container_ops.h"
#include "SandboxCore/soa_concepts.h"

#include "Containers/AllowShrinking.h"
#include "Containers/Array.h"
#include "Containers/ArrayView.h"
#include "CoreMinimal.h"

#include <utility>

struct TestCapitalShipFighterOrderQueueView;
struct TestCapitalShipFighterOrderQueueConstView;

struct SANDBOX_API TestCapitalShipFighterOrderQueueConstView {
    using View = TestCapitalShipFighterOrderQueueView;
    using ConstView = TestCapitalShipFighterOrderQueueConstView;

    template <typename TFunc>
    auto apply_arrays(this auto&& self, TFunc&& func) -> decltype(auto) {
        return std::forward<TFunc>(func)(
            self.handles,
            self.orders,
            self.tasks,
            self.targets
        );
    }

    auto get_view() const -> ConstView;
    auto get_view(int32 const offset, int32 const count) const -> ConstView;
    auto get_const_view() const -> ConstView;
    auto get_const_view(int32 const offset, int32 const count) const -> ConstView;
    auto num() const noexcept -> int32;
    void validate_array_sizes() const;
    auto slice(int32 const offset, int32 const count) const -> ConstView;
    auto left(int32 const count) const -> ConstView;
    auto right(int32 const count) const -> ConstView;

    TConstArrayView<FRegistryEntityHandle> handles;
    TConstArrayView<TestCapitalShipFighterOrder> orders;
    TConstArrayView<ETestCapitalShipFightersTask> tasks;
    TConstArrayView<FRegistryEntityHandle> targets;
};

struct SANDBOX_API TestCapitalShipFighterOrderQueueView {
    using View = TestCapitalShipFighterOrderQueueView;
    using ConstView = TestCapitalShipFighterOrderQueueConstView;

    template <typename TFunc>
    auto apply_arrays(this auto&& self, TFunc&& func) -> decltype(auto) {
        return std::forward<TFunc>(func)(
            self.handles,
            self.orders,
            self.tasks,
            self.targets
        );
    }

    auto get_view() -> View;
    auto get_view(int32 const offset, int32 const count) -> View;
    auto get_view() const -> ConstView;
    auto get_view(int32 const offset, int32 const count) const -> ConstView;
    auto get_const_view() const -> ConstView;
    auto get_const_view(int32 const offset, int32 const count) const -> ConstView;
    auto num() const noexcept -> int32;
    void validate_array_sizes() const;
    auto slice(int32 const offset, int32 const count) -> View;
    auto left(int32 const count) -> View;
    auto right(int32 const count) -> View;
    auto slice(int32 const offset, int32 const count) const -> ConstView;
    auto left(int32 const count) const -> ConstView;
    auto right(int32 const count) const -> ConstView;

    TArrayView<FRegistryEntityHandle> handles;
    TArrayView<TestCapitalShipFighterOrder> orders;
    TArrayView<ETestCapitalShipFightersTask> tasks;
    TArrayView<FRegistryEntityHandle> targets;
};

struct SANDBOX_API TestCapitalShipFighterOrderQueue {
    using View = TestCapitalShipFighterOrderQueueView;
    using ConstView = TestCapitalShipFighterOrderQueueConstView;

    using Task = ETestCapitalShipFightersTask;
    using Order = TestCapitalShipFighterOrder;

    void add(FRegistryEntityHandle const handle, Order const order, Task const task, FRegistryEntityHandle const target) {
        handles.Add(handle);
        orders.Add(order);
        tasks.Add(task);
        targets.Add(target);
    }

    void reset();

    void reserve(int32 const count);

    void add_uninitialised(int32 const count);

    void add_defaulted(int32 const count);

    void remove_at_swap(int32 const index, int32 const count, EAllowShrinking const allow_shrinking) {
        handles.RemoveAtSwap(index, count, allow_shrinking);
        orders.RemoveAtSwap(index, count, allow_shrinking);
        tasks.RemoveAtSwap(index, count, allow_shrinking);
        targets.RemoveAtSwap(index, count, allow_shrinking);
    }

    void set_num(int32 const count, EAllowShrinking const allow_shrinking);

    template <typename Other>
    void copy_element(int32 const dst_i, Other const& other, int32 const src_i) {
        ml::copy_element(handles, dst_i, other.handles, src_i);
        ml::copy_element(orders, dst_i, other.orders, src_i);
        ml::copy_element(tasks, dst_i, other.tasks, src_i);
        ml::copy_element(targets, dst_i, other.targets, src_i);
    }

    template <typename Other>
    void copy_elements(int32 const dst_i, Other const& other, int32 const src_i, int32 const count) {
        ml::copy_elements(handles, dst_i, other.handles, src_i, count);
        ml::copy_elements(orders, dst_i, other.orders, src_i, count);
        ml::copy_elements(tasks, dst_i, other.tasks, src_i, count);
        ml::copy_elements(targets, dst_i, other.targets, src_i, count);
    }

    template <typename Other>
    void copy_to_tail(Other const& other) {
        auto const count{other.num()};
        check(num() >= count);
        copy_elements(num() - count, other, 0, count);
    }

    template <typename Other>
    requires ml::SupportsApplyArrayPairsWith<TestCapitalShipFighterOrderQueue, Other>
    void append_from(Other const& other) {
        ml::append_from(handles, other.handles);
        ml::append_from(orders, other.orders);
        ml::append_from(tasks, other.tasks);
        ml::append_from(targets, other.targets);
    }

    void apply_permutation(TArrayView<int32> indices);

    template <typename Compare>
    void sort(Compare&& compare, TArrayView<int32> scratch_indices) {
        validate_array_sizes();
        auto const n{num()};
        check(scratch_indices.Num() == n);
        ml::fill_indices(scratch_indices);
        // indices[new_index] is the old row index that belongs at new_index.
        scratch_indices.Sort([this, &compare](int32 const lhs, int32 const rhs) {
            return compare(*this, lhs, rhs);
        });
        apply_permutation(scratch_indices);
    }

    template <auto Compare>
    void sort(TArrayView<int32> scratch_indices) {
        validate_array_sizes();
        auto const n{num()};
        check(scratch_indices.Num() == n);
        ml::fill_indices(scratch_indices);
        // indices[new_index] is the old row index that belongs at new_index.
        scratch_indices.Sort([this](int32 const lhs, int32 const rhs) {
            return Compare(*this, lhs, rhs);
        });
        apply_permutation(scratch_indices);
    }

    template <typename TFunc>
    auto apply_arrays(this auto&& self, TFunc&& func) -> decltype(auto) {
        return std::forward<TFunc>(func)(
            self.handles,
            self.orders,
            self.tasks,
            self.targets
        );
    }

    template <typename Self, typename Other, typename TFunc>
    auto apply_array_pairs(this Self&& self, Other&& other, TFunc&& func)
        -> decltype(auto) {
        return std::forward<TFunc>(func)(
            self.handles, other.handles,
            self.orders, other.orders,
            self.tasks, other.tasks,
            self.targets, other.targets
        );
    }

    auto get_view() -> View;
    auto get_view(int32 const offset, int32 const count) -> View;
    auto get_view() const -> ConstView;
    auto get_view(int32 const offset, int32 const count) const -> ConstView;
    auto get_const_view() const -> ConstView;
    auto get_const_view(int32 const offset, int32 const count) const -> ConstView;
    auto num() const noexcept -> int32;
    void validate_array_sizes() const;
    auto slice(int32 const offset, int32 const count) -> View;
    auto left(int32 const count) -> View;
    auto right(int32 const count) -> View;
    auto slice(int32 const offset, int32 const count) const -> ConstView;
    auto left(int32 const count) const -> ConstView;
    auto right(int32 const count) const -> ConstView;

    TArray<FRegistryEntityHandle> handles;
    TArray<TestCapitalShipFighterOrder> orders;
    TArray<ETestCapitalShipFightersTask> tasks;
    TArray<FRegistryEntityHandle> targets;
};
// clang-format on
