// clang-format off
// This file is autogenerated. Do not edit by hand.
// Edit Codegen/manifest.py and regenerate it instead.

#pragma once

#include "SandboxCore/array_utils.h"
#include "SandboxCore/container_ops.h"
#include "SandboxCore/soa_concepts.h"
#include "SandboxCore/soa_rotators.h"
#include "SandboxCore/soa_vectors_3f.h"

#include "Components/InstancedStaticMeshComponent.h"
#include "Containers/AllowShrinking.h"
#include "Containers/Array.h"
#include "Containers/ArrayView.h"
#include "CoreMinimal.h"
#include "Math/Color.h"
#include "SandboxNative/RegistryEntityHandle.h"

#include <utility>

namespace ml::test_lasers {
struct SpawnRequestsView;
struct SpawnRequestsConstView;

struct SANDBOX_API SpawnRequestsConstView {
    using View = SpawnRequestsView;
    using ConstView = SpawnRequestsConstView;

    template <typename TFunc>
    auto apply_arrays(this auto&& self, TFunc&& func) -> decltype(auto) {
        return std::forward<TFunc>(func)(
            self.locations,
            self.rotations,
            self.base_velocities,
            self.damages,
            self.speeds,
            self.max_distances,
            self.instigator_handles,
            self.colours
        );
    }

    auto get_view() const -> ConstView;
    auto get_view(int32 const offset, int32 const count) const -> ConstView;
    auto get_const_view() const -> ConstView;
    auto get_const_view(int32 const offset, int32 const count) const -> ConstView;
    auto num() const noexcept -> int32;
    auto is_empty() const noexcept -> bool;
    void validate_array_sizes() const;
    auto slice(int32 const offset, int32 const count) const -> ConstView;
    auto left(int32 const count) const -> ConstView;
    auto right(int32 const count) const -> ConstView;

    FVectors3f::ConstView locations;
    FRotatorsf::ConstView rotations;
    FVectors3f::ConstView base_velocities;
    TConstArrayView<int32> damages;
    TConstArrayView<float> speeds;
    TConstArrayView<float> max_distances;
    TConstArrayView<FRegistryEntityHandle> instigator_handles;
    TConstArrayView<FLinearColor> colours;
};

struct SANDBOX_API SpawnRequestsView {
    using View = SpawnRequestsView;
    using ConstView = SpawnRequestsConstView;

    template <typename TFunc>
    auto apply_arrays(this auto&& self, TFunc&& func) -> decltype(auto) {
        return std::forward<TFunc>(func)(
            self.locations,
            self.rotations,
            self.base_velocities,
            self.damages,
            self.speeds,
            self.max_distances,
            self.instigator_handles,
            self.colours
        );
    }

    auto get_view() -> View;
    auto get_view(int32 const offset, int32 const count) -> View;
    auto get_view() const -> ConstView;
    auto get_view(int32 const offset, int32 const count) const -> ConstView;
    auto get_const_view() const -> ConstView;
    auto get_const_view(int32 const offset, int32 const count) const -> ConstView;
    auto num() const noexcept -> int32;
    auto is_empty() const noexcept -> bool;
    void validate_array_sizes() const;
    auto slice(int32 const offset, int32 const count) -> View;
    auto left(int32 const count) -> View;
    auto right(int32 const count) -> View;
    auto slice(int32 const offset, int32 const count) const -> ConstView;
    auto left(int32 const count) const -> ConstView;
    auto right(int32 const count) const -> ConstView;

    FVectors3f::View locations;
    FRotatorsf::View rotations;
    FVectors3f::View base_velocities;
    TArrayView<int32> damages;
    TArrayView<float> speeds;
    TArrayView<float> max_distances;
    TArrayView<FRegistryEntityHandle> instigator_handles;
    TArrayView<FLinearColor> colours;
};

struct SANDBOX_API SpawnRequests {
    using View = SpawnRequestsView;
    using ConstView = SpawnRequestsConstView;

    void set_damages(int32 const value);
    void set_speeds(float const value);
    void set_max_distances(float const value);
    void set_colours(FLinearColor const value);

    void reset();

    void reserve(int32 const count);

    void add_uninitialised(int32 const count);

    void add_defaulted(int32 const count);

    void remove_at_swap(int32 const index, int32 const count, EAllowShrinking const allow_shrinking) {
        locations.remove_at_swap(index, count, allow_shrinking);
        rotations.remove_at_swap(index, count, allow_shrinking);
        base_velocities.remove_at_swap(index, count, allow_shrinking);
        damages.RemoveAtSwap(index, count, allow_shrinking);
        speeds.RemoveAtSwap(index, count, allow_shrinking);
        max_distances.RemoveAtSwap(index, count, allow_shrinking);
        instigator_handles.RemoveAtSwap(index, count, allow_shrinking);
        colours.RemoveAtSwap(index, count, allow_shrinking);
    }

    void set_num(int32 const count, EAllowShrinking const allow_shrinking);

    template <typename Other>
    void copy_element(int32 const dst_i, Other const& other, int32 const src_i) {
        ml::copy_element(locations, dst_i, other.locations, src_i);
        ml::copy_element(rotations, dst_i, other.rotations, src_i);
        ml::copy_element(base_velocities, dst_i, other.base_velocities, src_i);
        ml::copy_element(damages, dst_i, other.damages, src_i);
        ml::copy_element(speeds, dst_i, other.speeds, src_i);
        ml::copy_element(max_distances, dst_i, other.max_distances, src_i);
        ml::copy_element(instigator_handles, dst_i, other.instigator_handles, src_i);
        ml::copy_element(colours, dst_i, other.colours, src_i);
    }

    template <typename Other>
    void copy_elements(int32 const dst_i, Other const& other, int32 const src_i, int32 const count) {
        ml::copy_elements(locations, dst_i, other.locations, src_i, count);
        ml::copy_elements(rotations, dst_i, other.rotations, src_i, count);
        ml::copy_elements(base_velocities, dst_i, other.base_velocities, src_i, count);
        ml::copy_elements(damages, dst_i, other.damages, src_i, count);
        ml::copy_elements(speeds, dst_i, other.speeds, src_i, count);
        ml::copy_elements(max_distances, dst_i, other.max_distances, src_i, count);
        ml::copy_elements(instigator_handles, dst_i, other.instigator_handles, src_i, count);
        ml::copy_elements(colours, dst_i, other.colours, src_i, count);
    }

    template <typename Other>
    void copy_to_tail(Other const& other) {
        auto const count{other.num()};
        check(num() >= count);
        copy_elements(num() - count, other, 0, count);
    }

    template <typename Other>
    requires ml::SupportsApplyArrayPairsWith<SpawnRequests, Other>
    void append_from(Other const& other) {
        ml::append_from(locations, other.locations);
        ml::append_from(rotations, other.rotations);
        ml::append_from(base_velocities, other.base_velocities);
        ml::append_from(damages, other.damages);
        ml::append_from(speeds, other.speeds);
        ml::append_from(max_distances, other.max_distances);
        ml::append_from(instigator_handles, other.instigator_handles);
        ml::append_from(colours, other.colours);
    }

    void apply_permutation(TArrayView<int32> indices);

    template <typename Compare>
    void sort(Compare&& compare, TArrayView<int32> scratch_indices) {
        validate_array_sizes();
        auto const n{num()};
        check(scratch_indices.Num() == n);
        ml::fill_indices(scratch_indices);
        // indices[new_index] is the old row index that belongs at new_index.
        scratch_indices.Sort([this, &compare](int32 const lhs, int32 const rhs) {
            return compare(*this, lhs, rhs);
        });
        apply_permutation(scratch_indices);
    }

    template <auto Compare>
    void sort(TArrayView<int32> scratch_indices) {
        validate_array_sizes();
        auto const n{num()};
        check(scratch_indices.Num() == n);
        ml::fill_indices(scratch_indices);
        // indices[new_index] is the old row index that belongs at new_index.
        scratch_indices.Sort([this](int32 const lhs, int32 const rhs) {
            return Compare(*this, lhs, rhs);
        });
        apply_permutation(scratch_indices);
    }

    template <typename TFunc>
    auto apply_arrays(this auto&& self, TFunc&& func) -> decltype(auto) {
        return std::forward<TFunc>(func)(
            self.locations,
            self.rotations,
            self.base_velocities,
            self.damages,
            self.speeds,
            self.max_distances,
            self.instigator_handles,
            self.colours
        );
    }

    template <typename Self, typename Other, typename TFunc>
    auto apply_array_pairs(this Self&& self, Other&& other, TFunc&& func)
        -> decltype(auto) {
        return std::forward<TFunc>(func)(
            self.locations, other.locations,
            self.rotations, other.rotations,
            self.base_velocities, other.base_velocities,
            self.damages, other.damages,
            self.speeds, other.speeds,
            self.max_distances, other.max_distances,
            self.instigator_handles, other.instigator_handles,
            self.colours, other.colours
        );
    }

    auto get_view() -> View;
    auto get_view(int32 const offset, int32 const count) -> View;
    auto get_view() const -> ConstView;
    auto get_view(int32 const offset, int32 const count) const -> ConstView;
    auto get_const_view() const -> ConstView;
    auto get_const_view(int32 const offset, int32 const count) const -> ConstView;
    auto num() const noexcept -> int32;
    auto is_empty() const noexcept -> bool;
    void validate_array_sizes() const;
    auto slice(int32 const offset, int32 const count) -> View;
    auto left(int32 const count) -> View;
    auto right(int32 const count) -> View;
    auto slice(int32 const offset, int32 const count) const -> ConstView;
    auto left(int32 const count) const -> ConstView;
    auto right(int32 const count) const -> ConstView;

    FVectors3f locations;
    FRotatorsf rotations;
    FVectors3f base_velocities;
    TArray<int32> damages;
    TArray<float> speeds;
    TArray<float> max_distances;
    TArray<FRegistryEntityHandle> instigator_handles;
    TArray<FLinearColor> colours;
};

struct EntitiesView;
struct EntitiesConstView;

struct SANDBOX_API EntitiesConstView {
    using View = EntitiesView;
    using ConstView = EntitiesConstView;

    template <typename TFunc>
    auto apply_arrays(this auto&& self, TFunc&& func) -> decltype(auto) {
        return std::forward<TFunc>(func)(
            self.ismc_data,
            self.colours,
            self.locations,
            self.rotations,
            self.velocities,
            self.damages,
            self.lifetimes_remaining,
            self.instigator_handles
        );
    }

    auto get_view() const -> ConstView;
    auto get_view(int32 const offset, int32 const count) const -> ConstView;
    auto get_const_view() const -> ConstView;
    auto get_const_view(int32 const offset, int32 const count) const -> ConstView;
    auto num() const noexcept -> int32;
    auto is_empty() const noexcept -> bool;
    void validate_array_sizes() const;
    auto slice(int32 const offset, int32 const count) const -> ConstView;
    auto left(int32 const count) const -> ConstView;
    auto right(int32 const count) const -> ConstView;

    TConstArrayView<FInstancedStaticMeshInstanceData> ismc_data;
    TConstArrayView<FLinearColor> colours;
    FVectors3f::ConstView locations;
    FRotatorsf::ConstView rotations;
    FVectors3f::ConstView velocities;
    TConstArrayView<int32> damages;
    TConstArrayView<float> lifetimes_remaining;
    TConstArrayView<FRegistryEntityHandle> instigator_handles;
};

struct SANDBOX_API EntitiesView {
    using View = EntitiesView;
    using ConstView = EntitiesConstView;

    template <typename TFunc>
    auto apply_arrays(this auto&& self, TFunc&& func) -> decltype(auto) {
        return std::forward<TFunc>(func)(
            self.ismc_data,
            self.colours,
            self.locations,
            self.rotations,
            self.velocities,
            self.damages,
            self.lifetimes_remaining,
            self.instigator_handles
        );
    }

    auto get_view() -> View;
    auto get_view(int32 const offset, int32 const count) -> View;
    auto get_view() const -> ConstView;
    auto get_view(int32 const offset, int32 const count) const -> ConstView;
    auto get_const_view() const -> ConstView;
    auto get_const_view(int32 const offset, int32 const count) const -> ConstView;
    auto num() const noexcept -> int32;
    auto is_empty() const noexcept -> bool;
    void validate_array_sizes() const;
    auto slice(int32 const offset, int32 const count) -> View;
    auto left(int32 const count) -> View;
    auto right(int32 const count) -> View;
    auto slice(int32 const offset, int32 const count) const -> ConstView;
    auto left(int32 const count) const -> ConstView;
    auto right(int32 const count) const -> ConstView;

    TArrayView<FInstancedStaticMeshInstanceData> ismc_data;
    TArrayView<FLinearColor> colours;
    FVectors3f::View locations;
    FRotatorsf::View rotations;
    FVectors3f::View velocities;
    TArrayView<int32> damages;
    TArrayView<float> lifetimes_remaining;
    TArrayView<FRegistryEntityHandle> instigator_handles;
};

struct SANDBOX_API Entities {
    using View = EntitiesView;
    using ConstView = EntitiesConstView;

    void reset();

    void reserve(int32 const count);

    void add_uninitialised(int32 const count);

    void add_defaulted(int32 const count);

    void remove_at_swap(int32 const index, int32 const count, EAllowShrinking const allow_shrinking) {
        ismc_data.RemoveAtSwap(index, count, allow_shrinking);
        colours.RemoveAtSwap(index, count, allow_shrinking);
        locations.remove_at_swap(index, count, allow_shrinking);
        rotations.remove_at_swap(index, count, allow_shrinking);
        velocities.remove_at_swap(index, count, allow_shrinking);
        damages.RemoveAtSwap(index, count, allow_shrinking);
        lifetimes_remaining.RemoveAtSwap(index, count, allow_shrinking);
        instigator_handles.RemoveAtSwap(index, count, allow_shrinking);
    }

    void set_num(int32 const count, EAllowShrinking const allow_shrinking);

    template <typename Other>
    void copy_element(int32 const dst_i, Other const& other, int32 const src_i) {
        ml::copy_element(ismc_data, dst_i, other.ismc_data, src_i);
        ml::copy_element(colours, dst_i, other.colours, src_i);
        ml::copy_element(locations, dst_i, other.locations, src_i);
        ml::copy_element(rotations, dst_i, other.rotations, src_i);
        ml::copy_element(velocities, dst_i, other.velocities, src_i);
        ml::copy_element(damages, dst_i, other.damages, src_i);
        ml::copy_element(lifetimes_remaining, dst_i, other.lifetimes_remaining, src_i);
        ml::copy_element(instigator_handles, dst_i, other.instigator_handles, src_i);
    }

    template <typename Other>
    void copy_elements(int32 const dst_i, Other const& other, int32 const src_i, int32 const count) {
        ml::copy_elements(ismc_data, dst_i, other.ismc_data, src_i, count);
        ml::copy_elements(colours, dst_i, other.colours, src_i, count);
        ml::copy_elements(locations, dst_i, other.locations, src_i, count);
        ml::copy_elements(rotations, dst_i, other.rotations, src_i, count);
        ml::copy_elements(velocities, dst_i, other.velocities, src_i, count);
        ml::copy_elements(damages, dst_i, other.damages, src_i, count);
        ml::copy_elements(lifetimes_remaining, dst_i, other.lifetimes_remaining, src_i, count);
        ml::copy_elements(instigator_handles, dst_i, other.instigator_handles, src_i, count);
    }

    template <typename Other>
    void copy_to_tail(Other const& other) {
        auto const count{other.num()};
        check(num() >= count);
        copy_elements(num() - count, other, 0, count);
    }

    template <typename Other>
    requires ml::SupportsApplyArrayPairsWith<Entities, Other>
    void append_from(Other const& other) {
        ml::append_from(ismc_data, other.ismc_data);
        ml::append_from(colours, other.colours);
        ml::append_from(locations, other.locations);
        ml::append_from(rotations, other.rotations);
        ml::append_from(velocities, other.velocities);
        ml::append_from(damages, other.damages);
        ml::append_from(lifetimes_remaining, other.lifetimes_remaining);
        ml::append_from(instigator_handles, other.instigator_handles);
    }

    void apply_permutation(TArrayView<int32> indices);

    template <typename Compare>
    void sort(Compare&& compare, TArrayView<int32> scratch_indices) {
        validate_array_sizes();
        auto const n{num()};
        check(scratch_indices.Num() == n);
        ml::fill_indices(scratch_indices);
        // indices[new_index] is the old row index that belongs at new_index.
        scratch_indices.Sort([this, &compare](int32 const lhs, int32 const rhs) {
            return compare(*this, lhs, rhs);
        });
        apply_permutation(scratch_indices);
    }

    template <auto Compare>
    void sort(TArrayView<int32> scratch_indices) {
        validate_array_sizes();
        auto const n{num()};
        check(scratch_indices.Num() == n);
        ml::fill_indices(scratch_indices);
        // indices[new_index] is the old row index that belongs at new_index.
        scratch_indices.Sort([this](int32 const lhs, int32 const rhs) {
            return Compare(*this, lhs, rhs);
        });
        apply_permutation(scratch_indices);
    }

    template <typename TFunc>
    auto apply_arrays(this auto&& self, TFunc&& func) -> decltype(auto) {
        return std::forward<TFunc>(func)(
            self.ismc_data,
            self.colours,
            self.locations,
            self.rotations,
            self.velocities,
            self.damages,
            self.lifetimes_remaining,
            self.instigator_handles
        );
    }

    template <typename Self, typename Other, typename TFunc>
    auto apply_array_pairs(this Self&& self, Other&& other, TFunc&& func)
        -> decltype(auto) {
        return std::forward<TFunc>(func)(
            self.ismc_data, other.ismc_data,
            self.colours, other.colours,
            self.locations, other.locations,
            self.rotations, other.rotations,
            self.velocities, other.velocities,
            self.damages, other.damages,
            self.lifetimes_remaining, other.lifetimes_remaining,
            self.instigator_handles, other.instigator_handles
        );
    }

    auto get_view() -> View;
    auto get_view(int32 const offset, int32 const count) -> View;
    auto get_view() const -> ConstView;
    auto get_view(int32 const offset, int32 const count) const -> ConstView;
    auto get_const_view() const -> ConstView;
    auto get_const_view(int32 const offset, int32 const count) const -> ConstView;
    auto num() const noexcept -> int32;
    auto is_empty() const noexcept -> bool;
    void validate_array_sizes() const;
    auto slice(int32 const offset, int32 const count) -> View;
    auto left(int32 const count) -> View;
    auto right(int32 const count) -> View;
    auto slice(int32 const offset, int32 const count) const -> ConstView;
    auto left(int32 const count) const -> ConstView;
    auto right(int32 const count) const -> ConstView;

    TArray<FInstancedStaticMeshInstanceData> ismc_data;
    TArray<FLinearColor> colours;
    FVectors3f locations;
    FRotatorsf rotations;
    FVectors3f velocities;
    TArray<int32> damages;
    TArray<float> lifetimes_remaining;
    TArray<FRegistryEntityHandle> instigator_handles;
};

struct HitDetailsView;
struct HitDetailsConstView;

struct SANDBOX_API HitDetailsConstView {
    using View = HitDetailsView;
    using ConstView = HitDetailsConstView;

    template <typename TFunc>
    auto apply_arrays(this auto&& self, TFunc&& func) -> decltype(auto) {
        return std::forward<TFunc>(func)(
            self.locations,
            self.colours
        );
    }

    auto get_view() const -> ConstView;
    auto get_view(int32 const offset, int32 const count) const -> ConstView;
    auto get_const_view() const -> ConstView;
    auto get_const_view(int32 const offset, int32 const count) const -> ConstView;
    auto num() const noexcept -> int32;
    auto is_empty() const noexcept -> bool;
    void validate_array_sizes() const;
    auto slice(int32 const offset, int32 const count) const -> ConstView;
    auto left(int32 const count) const -> ConstView;
    auto right(int32 const count) const -> ConstView;

    FVectors3f::ConstView locations;
    TConstArrayView<FLinearColor> colours;
};

struct SANDBOX_API HitDetailsView {
    using View = HitDetailsView;
    using ConstView = HitDetailsConstView;

    template <typename TFunc>
    auto apply_arrays(this auto&& self, TFunc&& func) -> decltype(auto) {
        return std::forward<TFunc>(func)(
            self.locations,
            self.colours
        );
    }

    auto get_view() -> View;
    auto get_view(int32 const offset, int32 const count) -> View;
    auto get_view() const -> ConstView;
    auto get_view(int32 const offset, int32 const count) const -> ConstView;
    auto get_const_view() const -> ConstView;
    auto get_const_view(int32 const offset, int32 const count) const -> ConstView;
    auto num() const noexcept -> int32;
    auto is_empty() const noexcept -> bool;
    void validate_array_sizes() const;
    auto slice(int32 const offset, int32 const count) -> View;
    auto left(int32 const count) -> View;
    auto right(int32 const count) -> View;
    auto slice(int32 const offset, int32 const count) const -> ConstView;
    auto left(int32 const count) const -> ConstView;
    auto right(int32 const count) const -> ConstView;

    FVectors3f::View locations;
    TArrayView<FLinearColor> colours;
};

struct SANDBOX_API HitDetails {
    using View = HitDetailsView;
    using ConstView = HitDetailsConstView;

    void reset();

    void reserve(int32 const count);

    void add_uninitialised(int32 const count);

    void add_defaulted(int32 const count);

    void remove_at_swap(int32 const index, int32 const count, EAllowShrinking const allow_shrinking) {
        locations.remove_at_swap(index, count, allow_shrinking);
        colours.RemoveAtSwap(index, count, allow_shrinking);
    }

    void set_num(int32 const count, EAllowShrinking const allow_shrinking);

    template <typename Other>
    void copy_element(int32 const dst_i, Other const& other, int32 const src_i) {
        ml::copy_element(locations, dst_i, other.locations, src_i);
        ml::copy_element(colours, dst_i, other.colours, src_i);
    }

    template <typename Other>
    void copy_elements(int32 const dst_i, Other const& other, int32 const src_i, int32 const count) {
        ml::copy_elements(locations, dst_i, other.locations, src_i, count);
        ml::copy_elements(colours, dst_i, other.colours, src_i, count);
    }

    template <typename Other>
    void copy_to_tail(Other const& other) {
        auto const count{other.num()};
        check(num() >= count);
        copy_elements(num() - count, other, 0, count);
    }

    template <typename Other>
    requires ml::SupportsApplyArrayPairsWith<HitDetails, Other>
    void append_from(Other const& other) {
        ml::append_from(locations, other.locations);
        ml::append_from(colours, other.colours);
    }

    void apply_permutation(TArrayView<int32> indices);

    template <typename Compare>
    void sort(Compare&& compare, TArrayView<int32> scratch_indices) {
        validate_array_sizes();
        auto const n{num()};
        check(scratch_indices.Num() == n);
        ml::fill_indices(scratch_indices);
        // indices[new_index] is the old row index that belongs at new_index.
        scratch_indices.Sort([this, &compare](int32 const lhs, int32 const rhs) {
            return compare(*this, lhs, rhs);
        });
        apply_permutation(scratch_indices);
    }

    template <auto Compare>
    void sort(TArrayView<int32> scratch_indices) {
        validate_array_sizes();
        auto const n{num()};
        check(scratch_indices.Num() == n);
        ml::fill_indices(scratch_indices);
        // indices[new_index] is the old row index that belongs at new_index.
        scratch_indices.Sort([this](int32 const lhs, int32 const rhs) {
            return Compare(*this, lhs, rhs);
        });
        apply_permutation(scratch_indices);
    }

    template <typename TFunc>
    auto apply_arrays(this auto&& self, TFunc&& func) -> decltype(auto) {
        return std::forward<TFunc>(func)(
            self.locations,
            self.colours
        );
    }

    template <typename Self, typename Other, typename TFunc>
    auto apply_array_pairs(this Self&& self, Other&& other, TFunc&& func)
        -> decltype(auto) {
        return std::forward<TFunc>(func)(
            self.locations, other.locations,
            self.colours, other.colours
        );
    }

    auto get_view() -> View;
    auto get_view(int32 const offset, int32 const count) -> View;
    auto get_view() const -> ConstView;
    auto get_view(int32 const offset, int32 const count) const -> ConstView;
    auto get_const_view() const -> ConstView;
    auto get_const_view(int32 const offset, int32 const count) const -> ConstView;
    auto num() const noexcept -> int32;
    auto is_empty() const noexcept -> bool;
    void validate_array_sizes() const;
    auto slice(int32 const offset, int32 const count) -> View;
    auto left(int32 const count) -> View;
    auto right(int32 const count) -> View;
    auto slice(int32 const offset, int32 const count) const -> ConstView;
    auto left(int32 const count) const -> ConstView;
    auto right(int32 const count) const -> ConstView;

    FVectors3f locations;
    TArray<FLinearColor> colours;
};
} // namespace ml::test_lasers
// clang-format on
