// clang-format off
// This file is autogenerated. Do not edit by hand.
// Edit Codegen/manifest.py and regenerate it instead.

#pragma once

#include <Sandbox/batch_game/test_entity_registry/RegistryEntityHandle.h>
#include <Sandbox/batch_game/TestTeam.h>

#include <SandboxCore/soa_array_mixin.h>
#include <SandboxCore/soa_vectors.h>
#include <SandboxCore/tick_countdown.h>

#include "CoreMinimal.h"

#include <type_traits>
#include <utility>

namespace ml::test_static_turrets {
struct EntityDataConstView;

struct EntityDataView : public ml::FSoAViewMixin {
    using View = EntityDataView;
    using ConstView = EntityDataConstView;

    TArrayView<FRegistryEntityHandle> handles;
    FVectors3f::View locations;
    TArrayView<ETestTeam> teams;
    FTickCountdown16::View laser_cooldowns;
    TArrayView<FRegistryEntityHandle> target_handles;
    FVectors3f::View target_locations;
    FVectors3f::View target_velocities;
    TArrayView<int32> healths;

    template <typename TFunc>
    auto apply_arrays(this auto&& self, TFunc&& func) -> decltype(auto) {
        return std::forward<TFunc>(func)(
            self.handles,
            self.locations,
            self.teams,
            self.laser_cooldowns,
            self.target_handles,
            self.target_locations,
            self.target_velocities,
            self.healths
        );
    }
};

struct EntityDataConstView : public ml::FSoAViewMixin {
    using View = EntityDataView;
    using ConstView = EntityDataConstView;

    TConstArrayView<FRegistryEntityHandle> handles;
    FVectors3f::ConstView locations;
    TConstArrayView<ETestTeam> teams;
    FTickCountdown16::ConstView laser_cooldowns;
    TConstArrayView<FRegistryEntityHandle> target_handles;
    FVectors3f::ConstView target_locations;
    FVectors3f::ConstView target_velocities;
    TConstArrayView<int32> healths;

    template <typename TFunc>
    auto apply_arrays(this auto&& self, TFunc&& func) -> decltype(auto) {
        return std::forward<TFunc>(func)(
            self.handles,
            self.locations,
            self.teams,
            self.laser_cooldowns,
            self.target_handles,
            self.target_locations,
            self.target_velocities,
            self.healths
        );
    }
};

struct EntityData : public ml::FSoAArrayMixin {
    using View = EntityDataView;
    using ConstView = EntityDataConstView;

    TArray<FRegistryEntityHandle> handles;
    FVectors3f locations;
    TArray<ETestTeam> teams;
    FTickCountdown16 laser_cooldowns;
    TArray<FRegistryEntityHandle> target_handles;
    FVectors3f target_locations;
    FVectors3f target_velocities;
    TArray<int32> healths;

    template <typename TFunc>
    auto apply_arrays(this auto&& self, TFunc&& func) -> decltype(auto) {
        return std::forward<TFunc>(func)(
            self.handles,
            self.locations,
            self.teams,
            self.laser_cooldowns,
            self.target_handles,
            self.target_locations,
            self.target_velocities,
            self.healths
        );
    }

    template <typename Self, typename Other, typename TFunc>
    auto apply_array_pairs(this Self&& self, Other&& other, TFunc&& func)
        -> decltype(auto) {
        return std::forward<TFunc>(func)(
            self.handles, other.handles,
            self.locations, other.locations,
            self.teams, other.teams,
            self.laser_cooldowns, other.laser_cooldowns,
            self.target_handles, other.target_handles,
            self.target_locations, other.target_locations,
            self.target_velocities, other.target_velocities,
            self.healths, other.healths
        );
    }
};
} // namespace ml::test_static_turrets
// clang-format on
