// clang-format off
// This file is autogenerated. Do not edit by hand.
// Edit Codegen/manifest.py and regenerate it instead.

#pragma once

#include "Sandbox/batch_game/TestTeam.h"
#include "Sandbox/batch_game/test_entity_registry/RegistryEntityHandle.h"

#include "SandboxCore/soa_array_mixin.h"
#include "SandboxCore/soa_rotators.h"
#include "SandboxCore/soa_vectors.h"

#include "Containers/AllowShrinking.h"
#include "Containers/Array.h"
#include "Containers/ArrayView.h"

#include <utility>

struct TestCapitalShipFighterSpawnQueueConstView;

struct TestCapitalShipFighterSpawnQueueView : public ml::FSoAViewMixin {
    using View = TestCapitalShipFighterSpawnQueueView;
    using ConstView = TestCapitalShipFighterSpawnQueueConstView;

    template <typename TFunc>
    auto apply_arrays(this auto&& self, TFunc&& func) -> decltype(auto) {
        return std::forward<TFunc>(func)(
            self.locations,
            self.rotations,
            self.teams,
            self.targets
        );
    }

    FVectors3f::View locations;
    FRotatorsf::View rotations;
    TArrayView<ETestTeam> teams;
    TArrayView<FRegistryEntityHandle> targets;
};

struct TestCapitalShipFighterSpawnQueueConstView : public ml::FSoAViewMixin {
    using View = TestCapitalShipFighterSpawnQueueView;
    using ConstView = TestCapitalShipFighterSpawnQueueConstView;

    template <typename TFunc>
    auto apply_arrays(this auto&& self, TFunc&& func) -> decltype(auto) {
        return std::forward<TFunc>(func)(
            self.locations,
            self.rotations,
            self.teams,
            self.targets
        );
    }

    FVectors3f::ConstView locations;
    FRotatorsf::ConstView rotations;
    TConstArrayView<ETestTeam> teams;
    TConstArrayView<FRegistryEntityHandle> targets;
};

struct SANDBOX_API TestCapitalShipFighterSpawnQueue : public ml::FSoAArrayMixin {
    using View = TestCapitalShipFighterSpawnQueueView;
    using ConstView = TestCapitalShipFighterSpawnQueueConstView;

    void reset();

    void reserve(int32 const count);

    void add_uninitialised(int32 const count);

    void add_defaulted(int32 const count);

    void remove_at_swap(int32 const index, int32 const count, EAllowShrinking const allow_shrinking) {
        locations.remove_at_swap(index, count, allow_shrinking);
        rotations.remove_at_swap(index, count, allow_shrinking);
        teams.RemoveAtSwap(index, count, allow_shrinking);
        targets.RemoveAtSwap(index, count, allow_shrinking);
    }

    void set_num(int32 const count, EAllowShrinking const allow_shrinking);

    void copy_element(int32 const dst_i, TestCapitalShipFighterSpawnQueue const& other, int32 const src_i) {
        ml::copy_element(locations, dst_i, other.locations, src_i);
        ml::copy_element(rotations, dst_i, other.rotations, src_i);
        ml::copy_element(teams, dst_i, other.teams, src_i);
        ml::copy_element(targets, dst_i, other.targets, src_i);
    }

    template <typename Other>
    requires ml::SupportsApplyArrayPairsWith<TestCapitalShipFighterSpawnQueue, Other>
    void append_from(Other const& other) {
        ml::append_from(locations, other.locations);
        ml::append_from(rotations, other.rotations);
        ml::append_from(teams, other.teams);
        ml::append_from(targets, other.targets);
    }

    template <typename TFunc>
    auto apply_arrays(this auto&& self, TFunc&& func) -> decltype(auto) {
        return std::forward<TFunc>(func)(
            self.locations,
            self.rotations,
            self.teams,
            self.targets
        );
    }

    template <typename Self, typename Other, typename TFunc>
    auto apply_array_pairs(this Self&& self, Other&& other, TFunc&& func)
        -> decltype(auto) {
        return std::forward<TFunc>(func)(
            self.locations, other.locations,
            self.rotations, other.rotations,
            self.teams, other.teams,
            self.targets, other.targets
        );
    }

    FVectors3f locations;
    FRotatorsf rotations;
    TArray<ETestTeam> teams;
    TArray<FRegistryEntityHandle> targets;
};
// clang-format on
