// clang-format off
// This file is autogenerated. Do not edit by hand.
// Edit Codegen/manifest.py and regenerate it instead.

#include "TestCapitalShipFighterOrderQueue.h"

void TestCapitalShipFighterOrderQueue::reset() {
    ml::reset(handles);
    ml::reset(orders);
    ml::reset(tasks);
    ml::reset(targets);
}

void TestCapitalShipFighterOrderQueue::reserve(int32 const count) {
    ml::reserve(handles, count);
    ml::reserve(orders, count);
    ml::reserve(tasks, count);
    ml::reserve(targets, count);
}

void TestCapitalShipFighterOrderQueue::add_uninitialised(int32 const count) {
    ml::add_uninitialised(handles, count);
    ml::add_uninitialised(orders, count);
    ml::add_uninitialised(tasks, count);
    ml::add_uninitialised(targets, count);
}

void TestCapitalShipFighterOrderQueue::add_defaulted(int32 const count) {
    ml::add_defaulted(handles, count);
    ml::add_defaulted(orders, count);
    ml::add_defaulted(tasks, count);
    ml::add_defaulted(targets, count);
}

void TestCapitalShipFighterOrderQueue::set_num(int32 const count, EAllowShrinking const allow_shrinking) {
    ml::set_num(handles, count, allow_shrinking);
    ml::set_num(orders, count, allow_shrinking);
    ml::set_num(tasks, count, allow_shrinking);
    ml::set_num(targets, count, allow_shrinking);
}
// clang-format on
