// clang-format off
// This file is autogenerated. Do not edit by hand.
// Edit lispb/schema and regenerate it instead.

#include "SpaceGameSimulation/missions/TestMissionFailReason.h"

namespace {
auto get_test_mission_fail_reason_serialized_name(ETestMissionFailReason const value) -> TCHAR const* {
    switch (value) {
    case ETestMissionFailReason::None: {
        return TEXT("none");
    }
    case ETestMissionFailReason::PlayerKilled: {
        return TEXT("player_killed");
    }
    case ETestMissionFailReason::TimeElapsed: {
        return TEXT("time_elapsed");
    }
    case ETestMissionFailReason::DefenceObjectiveFailed: {
        return TEXT("defence_objective_failed");
    }
    }

    ensureMsgf(false,
               TEXT("Unhandled serialized ETestMissionFailReason value: %lld"),
               static_cast<int64>(value));
    return TEXT("<invalid ETestMissionFailReason>");
}


} // namespace

auto LexToSerializedString(ETestMissionFailReason const value) -> TCHAR const* {
    return get_test_mission_fail_reason_serialized_name(value);
}

namespace ml {
auto try_parse_serialized(FStringView const value, ETestMissionFailReason& result) -> bool {
    if (value == TEXT("none")) {
        result = ETestMissionFailReason::None;
        return true;
    }
    if (value == TEXT("player_killed")) {
        result = ETestMissionFailReason::PlayerKilled;
        return true;
    }
    if (value == TEXT("time_elapsed")) {
        result = ETestMissionFailReason::TimeElapsed;
        return true;
    }
    if (value == TEXT("defence_objective_failed")) {
        result = ETestMissionFailReason::DefenceObjectiveFailed;
        return true;
    }
    return false;
}


} // namespace ml
// clang-format on
