// This file is autogenerated. Do not edit by hand.
// Edit lispb/schema and regenerate it instead.

#pragma once

#include "ioj/enum_lookup.h"

#include "sandbox/core/enum_traits.h"

#include <array>
#include <cstddef>
#include <cstdint>
#include <optional>
#include <string_view>
#include <unordered_map>

namespace ioj::levels {
enum class TeamId : std::uint8_t {
    White,
    Red,
    Green,
    Blue,
    Orange,
    Yellow,
};

[[nodiscard]] constexpr auto to_string(TeamId const value) noexcept -> std::string_view {
    switch (value) {
        case TeamId::White: {
            return "White";
        }
        case TeamId::Red: {
            return "Red";
        }
        case TeamId::Green: {
            return "Green";
        }
        case TeamId::Blue: {
            return "Blue";
        }
        case TeamId::Orange: {
            return "Orange";
        }
        case TeamId::Yellow: {
            return "Yellow";
        }
    }

    return "<invalid TeamId>";
}

[[nodiscard]] constexpr auto try_parse_team_id(std::string_view const value) noexcept
    -> std::optional<TeamId> {
    if (value == "White") {
        return TeamId::White;
    }
    if (value == "Red") {
        return TeamId::Red;
    }
    if (value == "Green") {
        return TeamId::Green;
    }
    if (value == "Blue") {
        return TeamId::Blue;
    }
    if (value == "Orange") {
        return TeamId::Orange;
    }
    if (value == "Yellow") {
        return TeamId::Yellow;
    }

    return std::nullopt;
}

[[nodiscard]] constexpr auto to_serialized_string(TeamId const value) noexcept -> std::string_view {
    switch (value) {
        case TeamId::White: {
            return "white";
        }
        case TeamId::Red: {
            return "red";
        }
        case TeamId::Green: {
            return "green";
        }
        case TeamId::Blue: {
            return "blue";
        }
        case TeamId::Orange: {
            return "orange";
        }
        case TeamId::Yellow: {
            return "yellow";
        }
        default: {
            return "<invalid TeamId>";
        }
    }
}

[[nodiscard]] inline auto try_parse_serialized_team_id(std::string_view const value)
    -> std::optional<TeamId> {
    static std::unordered_map<std::string_view, TeamId> const values{
        {"white", TeamId::White},
        {"red", TeamId::Red},
        {"green", TeamId::Green},
        {"blue", TeamId::Blue},
        {"orange", TeamId::Orange},
        {"yellow", TeamId::Yellow},
    };
    return ioj::lookup_enum(values, value);
}

} // namespace ioj::levels
namespace ml {
template <>
struct EnumTraits<::ioj::levels::TeamId> {
    inline static constexpr std::array values{
        ::ioj::levels::TeamId::White,
        ::ioj::levels::TeamId::Red,
        ::ioj::levels::TeamId::Green,
        ::ioj::levels::TeamId::Blue,
        ::ioj::levels::TeamId::Orange,
        ::ioj::levels::TeamId::Yellow,
    };
    inline static constexpr std::array names{
        std::string_view{"White"},
        std::string_view{"Red"},
        std::string_view{"Green"},
        std::string_view{"Blue"},
        std::string_view{"Orange"},
        std::string_view{"Yellow"},
    };
};

} // namespace ml
