if(NOT CMAKE_HOST_WIN32)
  message(FATAL_ERROR "The clang-cl toolchain supports only Windows hosts.")
endif()

find_program(SANDBOX_CLANG_CL_EXECUTABLE NAMES clang-cl REQUIRED)

set(CMAKE_C_COMPILER "${SANDBOX_CLANG_CL_EXECUTABLE}" CACHE FILEPATH "" FORCE)
set(CMAKE_CXX_COMPILER "${SANDBOX_CLANG_CL_EXECUTABLE}" CACHE FILEPATH "" FORCE)
set(CMAKE_MSVC_RUNTIME_LIBRARY MultiThreadedDLL CACHE STRING "" FORCE)
set(SANDBOX_NATIVE_TOOLCHAIN clang-cl CACHE STRING "Native compiler toolchain" FORCE)
