"""Generate and verify the private mimalloc symbol-prefix integration."""

from __future__ import annotations

import argparse
import re
import subprocess
from pathlib import Path
from typing import Iterable


MIMALLOC_IDENTIFIER = re.compile(r"(?<![A-Za-z0-9_])(_*mi_[A-Za-z0-9_]+)")
INCLUDE_DIRECTIVE = re.compile(r"/INCLUDE:([^\s]+)", re.IGNORECASE)
MSVC_OPERATOR_NEW_DELETE = re.compile(r"^\?\?(?:[23]|_[UV])@")
FORBIDDEN_OVERRIDE_SYMBOLS = {
    "_aligned_free",
    "_aligned_malloc",
    "_aligned_realloc",
    "calloc",
    "free",
    "malloc",
    "realloc",
}


def prefixed(identifier: str) -> str:
    return f"sbx_{identifier}"


def allocator_identifiers(symbol_output: str) -> set[str]:
    return set(MIMALLOC_IDENTIFIER.findall(symbol_output))


def linker_includes(directive_output: str) -> set[str]:
    return set(INCLUDE_DIRECTIVE.findall(directive_output))


def without_msvc_string_literals(symbol_output: str) -> str:
    return "\n".join(
        line for line in symbol_output.splitlines() if not re.search(r"\s\?\?_C@", line)
    )


def run_tool(arguments: list[str]) -> str:
    result = subprocess.run(arguments, capture_output=True, text=True, check=False)
    if result.returncode != 0:
        raise RuntimeError(
            f"Command failed ({result.returncode}): {' '.join(arguments)}\n{result.stderr}"
        )
    return result.stdout


def nm_output(nm: Path, objects: Iterable[Path], *arguments: str) -> str:
    output: list[str] = []
    for object_path in objects:
        output.append(run_tool([str(nm), *arguments, str(object_path)]))
    return "\n".join(output)


def readobj_directives(readobj: Path, objects: Iterable[Path]) -> str:
    output: list[str] = []
    for object_path in objects:
        output.append(run_tool([str(readobj), "--coff-directives", str(object_path)]))
    return "\n".join(output)


def render_header(identifiers: set[str], includes: set[str]) -> str:
    lines = [
        "// Generated by Scripts/sbx_mimalloc_symbols.py. Do not edit.",
        "#pragma once",
        "",
    ]
    for identifier in sorted(identifiers):
        lines.append(f"#define {identifier} {prefixed(identifier)}")

    mimalloc_includes = sorted(
        symbol for symbol in includes if re.fullmatch(r"_+mi_[A-Za-z0-9_]+", symbol)
    )
    if mimalloc_includes:
        lines.extend(["", "#if defined(_MSC_VER)"])
        for symbol in mimalloc_includes:
            replacement = prefixed(symbol)
            lines.append(f'#pragma comment(linker, "/include:{replacement}")')
        lines.append("#endif")

    lines.append("")
    return "\n".join(lines)


def generate(args: argparse.Namespace) -> None:
    objects = [Path(value) for value in args.objects]
    symbols = nm_output(
        Path(args.nm), objects, "--defined-only", "--extern-only", "--demangle"
    )
    identifiers = allocator_identifiers(symbols)
    if not identifiers:
        raise RuntimeError("The mimalloc probe object exposed no allocator identifiers")

    directives = readobj_directives(Path(args.readobj), objects)
    output = Path(args.output)
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(
        render_header(identifiers, linker_includes(directives)), encoding="utf-8", newline="\n"
    )


def verify(args: argparse.Namespace) -> None:
    objects = [Path(value) for value in args.objects]
    nm = Path(args.nm)
    external_symbols = without_msvc_string_literals(
        nm_output(nm, objects, "--defined-only", "--extern-only")
    )
    remaining = sorted(allocator_identifiers(external_symbols))
    if remaining:
        raise RuntimeError(
            "Unprefixed externally visible mimalloc identifiers remain: " + ", ".join(remaining)
        )

    undefined_symbols = without_msvc_string_literals(
        nm_output(nm, objects, "--undefined-only", "--extern-only")
    )
    remaining_undefined = sorted(allocator_identifiers(undefined_symbols))
    if remaining_undefined:
        raise RuntimeError(
            "Unprefixed mimalloc references remain: " + ", ".join(remaining_undefined)
        )

    raw_definitions = set(
        nm_output(nm, objects, "-j", "--defined-only", "--extern-only").splitlines()
    )
    forbidden = sorted(raw_definitions & FORBIDDEN_OVERRIDE_SYMBOLS)
    forbidden.extend(
        sorted(symbol for symbol in raw_definitions if MSVC_OPERATOR_NEW_DELETE.match(symbol))
    )
    if forbidden:
        raise RuntimeError("Allocator override symbols are defined: " + ", ".join(forbidden))

    directives = readobj_directives(Path(args.readobj), objects)
    includes = linker_includes(directives)
    unprefixed_includes = {
        symbol for symbol in includes if re.fullmatch(r"_+mi_[A-Za-z0-9_]+", symbol)
    }
    if unprefixed_includes:
        raise RuntimeError(
            "Unprefixed mimalloc linker directives remain: "
            + ", ".join(sorted(unprefixed_includes))
        )


def parser() -> argparse.ArgumentParser:
    result = argparse.ArgumentParser(description=__doc__)
    subparsers = result.add_subparsers(dest="command", required=True)
    for name, function in (("generate", generate), ("verify", verify)):
        command = subparsers.add_parser(name)
        command.add_argument("--nm", required=True)
        command.add_argument("--readobj", required=True)
        if name == "generate":
            command.add_argument("--output", required=True)
        command.add_argument("objects", nargs="+")
        command.set_defaults(function=function)
    return result


def main() -> None:
    args = parser().parse_args()
    args.function(args)


if __name__ == "__main__":
    main()
