// This file is autogenerated. Do not edit by hand.
// Edit lispb/schema and regenerate it instead.

#pragma once

#include "sandbox/core/enum_traits.h"

#include "CoreMinimal.h"

#include "TestMissionState.generated.h"
UENUM()
enum class ETestMissionState : uint8 {
    NotStarted = 0 UMETA(DisplayName = "Not Started"),
    Running = 1 UMETA(DisplayName = "Running"),
    Succeeded = 2,
    Failed = 3 UMETA(DisplayName = "Failed"),
    Disabled = 4,
};

namespace ml {
template <>
[[nodiscard]] constexpr auto enum_count<::ETestMissionState>() noexcept -> std::size_t {
    return 5;
}
} // namespace ml
