// This file is autogenerated. Do not edit by hand.
// Edit lispb/schema and regenerate it instead.

#pragma once

#include <array>

#include <cstdint>

#include <cstddef>

#include <optional>

#include <string_view>

#include "sandbox/core/enum_traits.h"

namespace ioj::sim {
enum class MissionFailReason : std::uint8_t {
    None = 0,
    PlayerKilled = 1,
    TimeElapsed = 2,
    DefenceObjectiveFailed = 3,
};

[[nodiscard]] constexpr auto to_string(MissionFailReason const value) noexcept -> std::string_view {
    switch (value) {
        case MissionFailReason::None: {
            return "None";
        }
        case MissionFailReason::PlayerKilled: {
            return "PlayerKilled";
        }
        case MissionFailReason::TimeElapsed: {
            return "TimeElapsed";
        }
        case MissionFailReason::DefenceObjectiveFailed: {
            return "DefenceObjectiveFailed";
        }
    }

    return "<invalid MissionFailReason>";
}

[[nodiscard]] constexpr auto try_parse_mission_fail_reason(std::string_view const value) noexcept
    -> std::optional<MissionFailReason> {
    if (value == "None") {
        return MissionFailReason::None;
    }
    if (value == "PlayerKilled") {
        return MissionFailReason::PlayerKilled;
    }
    if (value == "TimeElapsed") {
        return MissionFailReason::TimeElapsed;
    }
    if (value == "DefenceObjectiveFailed") {
        return MissionFailReason::DefenceObjectiveFailed;
    }

    return std::nullopt;
}

[[nodiscard]] constexpr auto to_display_string(MissionFailReason const value) noexcept
    -> std::string_view {
    switch (value) {
        case MissionFailReason::None: {
            return "None";
        }
        case MissionFailReason::PlayerKilled: {
            return "PlayerKilled";
        }
        case MissionFailReason::TimeElapsed: {
            return "TimeElapsed";
        }
        case MissionFailReason::DefenceObjectiveFailed: {
            return "DefenceObjectiveFailed";
        }
    }

    return "<invalid MissionFailReason>";
}

[[nodiscard]] constexpr auto to_serialized_string(MissionFailReason const value) noexcept
    -> std::string_view {
    switch (value) {
        case MissionFailReason::None: {
            return "none";
        }
        case MissionFailReason::PlayerKilled: {
            return "player_killed";
        }
        case MissionFailReason::TimeElapsed: {
            return "time_elapsed";
        }
        case MissionFailReason::DefenceObjectiveFailed: {
            return "defence_objective_failed";
        }
        default: {
            return "<invalid MissionFailReason>";
        }
    }
}

[[nodiscard]] constexpr auto
    try_parse_serialized_mission_fail_reason(std::string_view const value) noexcept
    -> std::optional<MissionFailReason> {
    if (value == "none") {
        return MissionFailReason::None;
    }
    if (value == "player_killed") {
        return MissionFailReason::PlayerKilled;
    }
    if (value == "time_elapsed") {
        return MissionFailReason::TimeElapsed;
    }
    if (value == "defence_objective_failed") {
        return MissionFailReason::DefenceObjectiveFailed;
    }

    return std::nullopt;
}

} // namespace ioj::sim
namespace ml {
template <>
struct EnumTraits<::ioj::sim::MissionFailReason> {
    inline static constexpr std::array values{
        ::ioj::sim::MissionFailReason::None,
        ::ioj::sim::MissionFailReason::PlayerKilled,
        ::ioj::sim::MissionFailReason::TimeElapsed,
        ::ioj::sim::MissionFailReason::DefenceObjectiveFailed,
    };
    inline static constexpr std::array names{
        std::string_view{"None"},
        std::string_view{"PlayerKilled"},
        std::string_view{"TimeElapsed"},
        std::string_view{"DefenceObjectiveFailed"},
    };
    inline static constexpr std::size_t count{values.size()};
};

} // namespace ml
