// This file is autogenerated. Do not edit by hand.
// Edit lispb/schema and regenerate it instead.

#pragma once

#include "sandbox/core/enum_traits.h"

#include <array>
#include <cstddef>
#include <cstdint>
#include <optional>
#include <string_view>
#include <unordered_map>

namespace ioj::sim {
enum class MissionMode : std::uint8_t {
    None = 0,
    SurviveTime = 1,
    KillEnemies = 2,
    KillEnemiesWithinTime = 3,
};

[[nodiscard]] constexpr auto to_string(MissionMode const value) noexcept -> std::string_view {
    switch (value) {
        case MissionMode::None: {
            return "None";
        }
        case MissionMode::SurviveTime: {
            return "SurviveTime";
        }
        case MissionMode::KillEnemies: {
            return "KillEnemies";
        }
        case MissionMode::KillEnemiesWithinTime: {
            return "KillEnemiesWithinTime";
        }
    }

    return "<invalid MissionMode>";
}

[[nodiscard]] constexpr auto try_parse_mission_mode(std::string_view const value) noexcept
    -> std::optional<MissionMode> {
    if (value == "None") {
        return MissionMode::None;
    }
    if (value == "SurviveTime") {
        return MissionMode::SurviveTime;
    }
    if (value == "KillEnemies") {
        return MissionMode::KillEnemies;
    }
    if (value == "KillEnemiesWithinTime") {
        return MissionMode::KillEnemiesWithinTime;
    }

    return std::nullopt;
}

[[nodiscard]] constexpr auto to_display_string(MissionMode const value) noexcept
    -> std::string_view {
    switch (value) {
        case MissionMode::None: {
            return "None";
        }
        case MissionMode::SurviveTime: {
            return "Survive Time";
        }
        case MissionMode::KillEnemies: {
            return "Kill Enemies";
        }
        case MissionMode::KillEnemiesWithinTime: {
            return "Kill Enemies Within Time";
        }
    }

    return "<invalid MissionMode>";
}

[[nodiscard]] constexpr auto to_serialized_string(MissionMode const value) noexcept
    -> std::string_view {
    switch (value) {
        case MissionMode::None: {
            return "none";
        }
        case MissionMode::SurviveTime: {
            return "survive_time";
        }
        case MissionMode::KillEnemies: {
            return "kill_enemies";
        }
        case MissionMode::KillEnemiesWithinTime: {
            return "kill_enemies_within_time";
        }
        default: {
            return "<invalid MissionMode>";
        }
    }
}

[[nodiscard]] inline auto try_parse_serialized_mission_mode(std::string_view const value)
    -> std::optional<MissionMode> {
    static std::unordered_map<std::string_view, MissionMode> const values{
        {"none", MissionMode::None},
        {"survive_time", MissionMode::SurviveTime},
        {"kill_enemies", MissionMode::KillEnemies},
        {"kill_enemies_within_time", MissionMode::KillEnemiesWithinTime},
    };
    auto const found{values.find(value)};
    if (found == values.end()) {
        return std::nullopt;
    }
    return found->second;
}

} // namespace ioj::sim
namespace ml {
template <>
struct EnumTraits<::ioj::sim::MissionMode> {
    inline static constexpr std::array values{
        ::ioj::sim::MissionMode::None,
        ::ioj::sim::MissionMode::SurviveTime,
        ::ioj::sim::MissionMode::KillEnemies,
        ::ioj::sim::MissionMode::KillEnemiesWithinTime,
    };
    inline static constexpr std::array names{
        std::string_view{"None"},
        std::string_view{"SurviveTime"},
        std::string_view{"KillEnemies"},
        std::string_view{"KillEnemiesWithinTime"},
    };
};

template <>
[[nodiscard]] constexpr auto enum_count<::ioj::sim::MissionMode>() noexcept -> std::size_t {
    return 4;
}

} // namespace ml
