// This file is autogenerated. Do not edit by hand.
// Edit lispb/schema and regenerate it instead.

#pragma once

#include "ioj/sim/entity_types.h"
#include "ioj/sim/level_event_types.h"
#include "ioj/sim/rotators3f.h"
#include "ioj/sim/vectors3f.h"
#include "native_soa/storage.h"
#include "sandbox/core/soa_permutation.h"

namespace ioj::sim {
using ioj::sim::Rotators3f;
using ioj::sim::Rotators3fConstView;
using ioj::sim::Rotators3fView;
using ioj::sim::Vectors3f;
using ioj::sim::Vectors3fConstView;
using ioj::sim::Vectors3fView;
}

namespace ioj::sim {
struct LevelSpawnGroupsView;
struct LevelSpawnGroupsConstView;
struct LevelSpawnGroupsConstView {
    using View = LevelSpawnGroupsView;
    using ConstView = LevelSpawnGroupsConstView;
    using size_type = std::int32_t;
    std::span<ioj::sim::EntityType const> types;
    std::span<std::int32_t const> offsets;
    std::span<ioj::sim::LevelEventCount const> counts;
    auto num() const noexcept -> size_type { return static_cast<size_type>(types.size()); }
    auto is_empty() const noexcept -> bool { return num() == 0; }
    template <typename Fn>
    void each_column(Fn&& fn) const {
        fn(types);
        fn(offsets);
        fn(counts);
    }
    void validate_array_sizes() const {
        auto const count{num()};
        each_column([count](auto column) {
            ml::native_soa::require(column.size() == static_cast<std::size_t>(count));
        });
    }
    auto slice(size_type const offset, size_type const count) const -> LevelSpawnGroupsConstView {
        ml::native_soa::require(offset >= 0 && count >= 0 && offset <= num() &&
                                count <= num() - offset);
        return {
            types.subspan(static_cast<std::size_t>(offset), static_cast<std::size_t>(count)),
            offsets.subspan(static_cast<std::size_t>(offset), static_cast<std::size_t>(count)),
            counts.subspan(static_cast<std::size_t>(offset), static_cast<std::size_t>(count)),
        };
    }
    auto get_view() const -> LevelSpawnGroupsConstView { return *this; }
    auto get_view(size_type const offset, size_type const count) const
        -> LevelSpawnGroupsConstView {
        return slice(offset, count);
    }
    auto get_const_view() const -> ConstView {
        return {
            types,
            offsets,
            counts,
        };
    }
    auto get_const_view(size_type const offset, size_type const count) const -> ConstView {
        return get_const_view().slice(offset, count);
    }
    auto left(size_type const count) const -> LevelSpawnGroupsConstView { return slice(0, count); }
    auto right(size_type const count) const -> LevelSpawnGroupsConstView {
        return slice(num() - count, count);
    }
};
struct LevelSpawnGroupsView {
    using View = LevelSpawnGroupsView;
    using ConstView = LevelSpawnGroupsConstView;
    using size_type = std::int32_t;
    std::span<ioj::sim::EntityType> types;
    std::span<std::int32_t> offsets;
    std::span<ioj::sim::LevelEventCount> counts;
    auto num() const noexcept -> size_type { return static_cast<size_type>(types.size()); }
    auto is_empty() const noexcept -> bool { return num() == 0; }
    template <typename Fn>
    void each_column(Fn&& fn) const {
        fn(types);
        fn(offsets);
        fn(counts);
    }
    void validate_array_sizes() const {
        auto const count{num()};
        each_column([count](auto column) {
            ml::native_soa::require(column.size() == static_cast<std::size_t>(count));
        });
    }
    auto slice(size_type const offset, size_type const count) const -> LevelSpawnGroupsView {
        ml::native_soa::require(offset >= 0 && count >= 0 && offset <= num() &&
                                count <= num() - offset);
        return {
            types.subspan(static_cast<std::size_t>(offset), static_cast<std::size_t>(count)),
            offsets.subspan(static_cast<std::size_t>(offset), static_cast<std::size_t>(count)),
            counts.subspan(static_cast<std::size_t>(offset), static_cast<std::size_t>(count)),
        };
    }
    auto get_view() const -> LevelSpawnGroupsView { return *this; }
    auto get_view(size_type const offset, size_type const count) const -> LevelSpawnGroupsView {
        return slice(offset, count);
    }
    auto get_const_view() const -> ConstView {
        return {
            types,
            offsets,
            counts,
        };
    }
    auto get_const_view(size_type const offset, size_type const count) const -> ConstView {
        return get_const_view().slice(offset, count);
    }
    auto left(size_type const count) const -> LevelSpawnGroupsView { return slice(0, count); }
    auto right(size_type const count) const -> LevelSpawnGroupsView {
        return slice(num() - count, count);
    }
    void set(size_type const index,
             ioj::sim::EntityType const new_types,
             std::int32_t const new_offsets,
             ioj::sim::LevelEventCount const new_counts) const {
        ml::native_soa::require(index >= 0 && index < num());
        types[static_cast<std::size_t>(index)] = new_types;
        offsets[static_cast<std::size_t>(index)] = new_offsets;
        counts[static_cast<std::size_t>(index)] = new_counts;
    }
};
struct LevelSpawnGroups {
    using View = LevelSpawnGroupsView;
    using ConstView = LevelSpawnGroupsConstView;
    using size_type = std::int32_t;
    ml::native_soa::Vector<ioj::sim::EntityType> types;
    ml::native_soa::Vector<std::int32_t> offsets;
    ml::native_soa::Vector<ioj::sim::LevelEventCount> counts;
    auto num() const noexcept -> size_type { return static_cast<size_type>(types.size()); }
    auto is_empty() const noexcept -> bool { return num() == 0; }
    template <typename Fn>
    void each_column(Fn&& fn) {
        fn(types);
        fn(offsets);
        fn(counts);
    }
    template <typename Fn>
    void each_column(Fn&& fn) const {
        fn(types);
        fn(offsets);
        fn(counts);
    }
    void validate_array_sizes() const { get_const_view().validate_array_sizes(); }
    void reserve(size_type const count) {
        ml::native_soa::require(count >= 0);
        types.reserve(static_cast<std::size_t>(count));
        offsets.reserve(static_cast<std::size_t>(count));
        counts.reserve(static_cast<std::size_t>(count));
    }
    void reset() noexcept {
        types.clear();
        offsets.clear();
        counts.clear();
    }
    void set_num(size_type const count) {
        ml::native_soa::require(count >= 0);
        auto const size{static_cast<std::size_t>(count)};
        types.resize(size);
        offsets.resize(size);
        counts.resize(size);
    }
    void add_uninitialised(size_type const count) {
        auto const old_num{num()};
        ml::native_soa::require(count >= 0 &&
                                count <= std::numeric_limits<size_type>::max() - old_num);
        set_num(old_num + count);
    }
    void add_defaulted(size_type const count) { add_uninitialised(count); }
    void remove_at_swap(size_type const index, size_type const count) {
        auto const old_num{num()};
        ml::native_soa::require(index >= 0 && index <= old_num && count >= 0 &&
                                count <= old_num - index);
        auto const moved{std::min(count, old_num - index - count)};
        auto const source{old_num - moved};
        for (size_type i{}; i < moved; ++i) {
            types[index + i] = types[source + i];
        }
        for (size_type i{}; i < moved; ++i) {
            offsets[index + i] = offsets[source + i];
        }
        for (size_type i{}; i < moved; ++i) {
            counts[index + i] = counts[source + i];
        }
        set_num(old_num - count);
    }
    void set(size_type const index,
             ioj::sim::EntityType const new_types,
             std::int32_t const new_offsets,
             ioj::sim::LevelEventCount const new_counts) {
        get_view().set(index, new_types, new_offsets, new_counts);
    }
    auto add(ioj::sim::EntityType const new_types,
             std::int32_t const new_offsets,
             ioj::sim::LevelEventCount const new_counts) -> size_type {
        auto const index{num()};
        add_defaulted(1);
        set(index, new_types, new_offsets, new_counts);
        return index;
    }
    void append_from(ConstView source) {
        auto const count{source.num()};
        ml::native_soa::require(count <= std::numeric_limits<size_type>::max() - num());
        source.validate_array_sizes();
        if (count == 0) {
            return;
        }
        {
            auto const address{reinterpret_cast<std::uintptr_t>(source.types.data())};
            auto const begin{reinterpret_cast<std::uintptr_t>(types.data())};
            ml::native_soa::require(address < begin ||
                                    address >= begin + types.size() * sizeof(ioj::sim::EntityType));
        }
        {
            auto const address{reinterpret_cast<std::uintptr_t>(source.offsets.data())};
            auto const begin{reinterpret_cast<std::uintptr_t>(offsets.data())};
            ml::native_soa::require(address < begin ||
                                    address >= begin + offsets.size() * sizeof(std::int32_t));
        }
        {
            auto const address{reinterpret_cast<std::uintptr_t>(source.counts.data())};
            auto const begin{reinterpret_cast<std::uintptr_t>(counts.data())};
            ml::native_soa::require(address < begin ||
                                    address >=
                                        begin + counts.size() * sizeof(ioj::sim::LevelEventCount));
        }
        types.insert(types.end(), source.types.begin(), source.types.end());
        offsets.insert(offsets.end(), source.offsets.begin(), source.offsets.end());
        counts.insert(counts.end(), source.counts.begin(), source.counts.end());
    }
    auto get_view() -> View {
        return {
            types,
            offsets,
            counts,
        };
    }
    auto get_view() const -> ConstView {
        return {
            types,
            offsets,
            counts,
        };
    }
    auto get_const_view() const -> ConstView { return get_view(); }
    auto get_view(size_type const offset, size_type const count) -> View {
        return get_view().slice(offset, count);
    }
    auto get_view(size_type const offset, size_type const count) const -> ConstView {
        return get_view().slice(offset, count);
    }
    auto get_const_view(size_type const offset, size_type const count) const -> ConstView {
        return get_const_view().slice(offset, count);
    }
    auto slice(size_type const offset, size_type const count) -> View {
        return get_view(offset, count);
    }
    auto slice(size_type const offset, size_type const count) const -> ConstView {
        return get_const_view(offset, count);
    }
    auto left(size_type const count) -> View { return slice(0, count); }
    auto right(size_type const count) -> View { return slice(num() - count, count); }
    auto left(size_type const count) const -> ConstView { return slice(0, count); }
    auto right(size_type const count) const -> ConstView { return slice(num() - count, count); }
    template <typename Other>
    void copy_element(size_type const dst_index, Other const& other, size_type const src_index) {
        types[static_cast<std::size_t>(dst_index)] =
            other.types[static_cast<std::size_t>(src_index)];
        offsets[static_cast<std::size_t>(dst_index)] =
            other.offsets[static_cast<std::size_t>(src_index)];
        counts[static_cast<std::size_t>(dst_index)] =
            other.counts[static_cast<std::size_t>(src_index)];
    }
    template <typename Other>
    void copy_elements(size_type const dst_index,
                       Other const& other,
                       size_type const src_index,
                       size_type const count) {
        for (size_type i{}; i < count; ++i) {
            copy_element(dst_index + i, other, src_index + i);
        }
    }
    void apply_permutation(std::span<std::int32_t> const indices) {
        validate_array_sizes();
        ml::native_soa::require(indices.size() == static_cast<std::size_t>(num()));
        each_column([indices](auto& column) { ml::apply_permutation(std::span{column}, indices); });
    }
    template <typename Compare>
    void sort(Compare&& compare, std::span<std::int32_t> const scratch_indices) {
        validate_array_sizes();
        ml::native_soa::require(scratch_indices.size() == static_cast<std::size_t>(num()));
        for (size_type i{}; i < num(); ++i) {
            scratch_indices[static_cast<std::size_t>(i)] = i;
        }
        std::sort(scratch_indices.begin(),
                  scratch_indices.end(),
                  [this, &compare](size_type const lhs, size_type const rhs) {
                      return compare(*this, lhs, rhs);
                  });
        apply_permutation(scratch_indices);
    }
};

struct LevelCapitalSpawnEventsView;
struct LevelCapitalSpawnEventsConstView;
struct LevelCapitalSpawnEventsConstView {
    using View = LevelCapitalSpawnEventsView;
    using ConstView = LevelCapitalSpawnEventsConstView;
    using size_type = std::int32_t;
    std::span<std::int32_t const> entity_indices;
    std::span<std::int32_t const> target_entity_indices;
    Vectors3fConstView locations;
    Rotators3fConstView rotations;
    std::span<ioj::sim::Team const> teams;
    std::span<std::int32_t const> healths;
    std::span<float const> initial_fighter_spawn_delays;
    std::span<float const> fighter_spawn_cooldowns;
    auto num() const noexcept -> size_type { return static_cast<size_type>(entity_indices.size()); }
    auto is_empty() const noexcept -> bool { return num() == 0; }
    template <typename Fn>
    void each_column(Fn&& fn) const {
        fn(entity_indices);
        fn(target_entity_indices);
        fn(locations.xs);
        fn(locations.ys);
        fn(locations.zs);
        fn(rotations.pitches);
        fn(rotations.yaws);
        fn(rotations.rolls);
        fn(teams);
        fn(healths);
        fn(initial_fighter_spawn_delays);
        fn(fighter_spawn_cooldowns);
    }
    void validate_array_sizes() const {
        auto const count{num()};
        each_column([count](auto column) {
            ml::native_soa::require(column.size() == static_cast<std::size_t>(count));
        });
    }
    auto slice(size_type const offset, size_type const count) const
        -> LevelCapitalSpawnEventsConstView {
        ml::native_soa::require(offset >= 0 && count >= 0 && offset <= num() &&
                                count <= num() - offset);
        return {
            entity_indices.subspan(static_cast<std::size_t>(offset),
                                   static_cast<std::size_t>(count)),
            target_entity_indices.subspan(static_cast<std::size_t>(offset),
                                          static_cast<std::size_t>(count)),
            locations.slice(offset, count),
            rotations.slice(offset, count),
            teams.subspan(static_cast<std::size_t>(offset), static_cast<std::size_t>(count)),
            healths.subspan(static_cast<std::size_t>(offset), static_cast<std::size_t>(count)),
            initial_fighter_spawn_delays.subspan(static_cast<std::size_t>(offset),
                                                 static_cast<std::size_t>(count)),
            fighter_spawn_cooldowns.subspan(static_cast<std::size_t>(offset),
                                            static_cast<std::size_t>(count)),
        };
    }
    auto get_view() const -> LevelCapitalSpawnEventsConstView { return *this; }
    auto get_view(size_type const offset, size_type const count) const
        -> LevelCapitalSpawnEventsConstView {
        return slice(offset, count);
    }
    auto get_const_view() const -> ConstView {
        return {
            entity_indices,
            target_entity_indices,
            locations.get_const_view(),
            rotations.get_const_view(),
            teams,
            healths,
            initial_fighter_spawn_delays,
            fighter_spawn_cooldowns,
        };
    }
    auto get_const_view(size_type const offset, size_type const count) const -> ConstView {
        return get_const_view().slice(offset, count);
    }
    auto left(size_type const count) const -> LevelCapitalSpawnEventsConstView {
        return slice(0, count);
    }
    auto right(size_type const count) const -> LevelCapitalSpawnEventsConstView {
        return slice(num() - count, count);
    }
};
struct LevelCapitalSpawnEventsView {
    using View = LevelCapitalSpawnEventsView;
    using ConstView = LevelCapitalSpawnEventsConstView;
    using size_type = std::int32_t;
    std::span<std::int32_t> entity_indices;
    std::span<std::int32_t> target_entity_indices;
    Vectors3fView locations;
    Rotators3fView rotations;
    std::span<ioj::sim::Team> teams;
    std::span<std::int32_t> healths;
    std::span<float> initial_fighter_spawn_delays;
    std::span<float> fighter_spawn_cooldowns;
    auto num() const noexcept -> size_type { return static_cast<size_type>(entity_indices.size()); }
    auto is_empty() const noexcept -> bool { return num() == 0; }
    template <typename Fn>
    void each_column(Fn&& fn) const {
        fn(entity_indices);
        fn(target_entity_indices);
        fn(locations.xs);
        fn(locations.ys);
        fn(locations.zs);
        fn(rotations.pitches);
        fn(rotations.yaws);
        fn(rotations.rolls);
        fn(teams);
        fn(healths);
        fn(initial_fighter_spawn_delays);
        fn(fighter_spawn_cooldowns);
    }
    void validate_array_sizes() const {
        auto const count{num()};
        each_column([count](auto column) {
            ml::native_soa::require(column.size() == static_cast<std::size_t>(count));
        });
    }
    auto slice(size_type const offset, size_type const count) const -> LevelCapitalSpawnEventsView {
        ml::native_soa::require(offset >= 0 && count >= 0 && offset <= num() &&
                                count <= num() - offset);
        return {
            entity_indices.subspan(static_cast<std::size_t>(offset),
                                   static_cast<std::size_t>(count)),
            target_entity_indices.subspan(static_cast<std::size_t>(offset),
                                          static_cast<std::size_t>(count)),
            locations.slice(offset, count),
            rotations.slice(offset, count),
            teams.subspan(static_cast<std::size_t>(offset), static_cast<std::size_t>(count)),
            healths.subspan(static_cast<std::size_t>(offset), static_cast<std::size_t>(count)),
            initial_fighter_spawn_delays.subspan(static_cast<std::size_t>(offset),
                                                 static_cast<std::size_t>(count)),
            fighter_spawn_cooldowns.subspan(static_cast<std::size_t>(offset),
                                            static_cast<std::size_t>(count)),
        };
    }
    auto get_view() const -> LevelCapitalSpawnEventsView { return *this; }
    auto get_view(size_type const offset, size_type const count) const
        -> LevelCapitalSpawnEventsView {
        return slice(offset, count);
    }
    auto get_const_view() const -> ConstView {
        return {
            entity_indices,
            target_entity_indices,
            locations.get_const_view(),
            rotations.get_const_view(),
            teams,
            healths,
            initial_fighter_spawn_delays,
            fighter_spawn_cooldowns,
        };
    }
    auto get_const_view(size_type const offset, size_type const count) const -> ConstView {
        return get_const_view().slice(offset, count);
    }
    auto left(size_type const count) const -> LevelCapitalSpawnEventsView {
        return slice(0, count);
    }
    auto right(size_type const count) const -> LevelCapitalSpawnEventsView {
        return slice(num() - count, count);
    }
};
struct LevelCapitalSpawnEvents {
    using View = LevelCapitalSpawnEventsView;
    using ConstView = LevelCapitalSpawnEventsConstView;
    using size_type = std::int32_t;
    ml::native_soa::Vector<std::int32_t> entity_indices;
    ml::native_soa::Vector<std::int32_t> target_entity_indices;
    Vectors3f locations;
    Rotators3f rotations;
    ml::native_soa::Vector<ioj::sim::Team> teams;
    ml::native_soa::Vector<std::int32_t> healths;
    ml::native_soa::Vector<float> initial_fighter_spawn_delays;
    ml::native_soa::Vector<float> fighter_spawn_cooldowns;
    auto num() const noexcept -> size_type { return static_cast<size_type>(entity_indices.size()); }
    auto is_empty() const noexcept -> bool { return num() == 0; }
    template <typename Fn>
    void each_column(Fn&& fn) {
        fn(entity_indices);
        fn(target_entity_indices);
        fn(locations.xs);
        fn(locations.ys);
        fn(locations.zs);
        fn(rotations.pitches);
        fn(rotations.yaws);
        fn(rotations.rolls);
        fn(teams);
        fn(healths);
        fn(initial_fighter_spawn_delays);
        fn(fighter_spawn_cooldowns);
    }
    template <typename Fn>
    void each_column(Fn&& fn) const {
        fn(entity_indices);
        fn(target_entity_indices);
        fn(locations.xs);
        fn(locations.ys);
        fn(locations.zs);
        fn(rotations.pitches);
        fn(rotations.yaws);
        fn(rotations.rolls);
        fn(teams);
        fn(healths);
        fn(initial_fighter_spawn_delays);
        fn(fighter_spawn_cooldowns);
    }
    void validate_array_sizes() const { get_const_view().validate_array_sizes(); }
    void reserve(size_type const count) {
        ml::native_soa::require(count >= 0);
        entity_indices.reserve(static_cast<std::size_t>(count));
        target_entity_indices.reserve(static_cast<std::size_t>(count));
        locations.xs.reserve(static_cast<std::size_t>(count));
        locations.ys.reserve(static_cast<std::size_t>(count));
        locations.zs.reserve(static_cast<std::size_t>(count));
        rotations.pitches.reserve(static_cast<std::size_t>(count));
        rotations.yaws.reserve(static_cast<std::size_t>(count));
        rotations.rolls.reserve(static_cast<std::size_t>(count));
        teams.reserve(static_cast<std::size_t>(count));
        healths.reserve(static_cast<std::size_t>(count));
        initial_fighter_spawn_delays.reserve(static_cast<std::size_t>(count));
        fighter_spawn_cooldowns.reserve(static_cast<std::size_t>(count));
    }
    void reset() noexcept {
        entity_indices.clear();
        target_entity_indices.clear();
        locations.xs.clear();
        locations.ys.clear();
        locations.zs.clear();
        rotations.pitches.clear();
        rotations.yaws.clear();
        rotations.rolls.clear();
        teams.clear();
        healths.clear();
        initial_fighter_spawn_delays.clear();
        fighter_spawn_cooldowns.clear();
    }
    void set_num(size_type const count) {
        ml::native_soa::require(count >= 0);
        auto const size{static_cast<std::size_t>(count)};
        entity_indices.resize(size);
        target_entity_indices.resize(size);
        locations.xs.resize(size);
        locations.ys.resize(size);
        locations.zs.resize(size);
        rotations.pitches.resize(size);
        rotations.yaws.resize(size);
        rotations.rolls.resize(size);
        teams.resize(size);
        healths.resize(size);
        initial_fighter_spawn_delays.resize(size);
        fighter_spawn_cooldowns.resize(size);
    }
    void add_uninitialised(size_type const count) {
        auto const old_num{num()};
        ml::native_soa::require(count >= 0 &&
                                count <= std::numeric_limits<size_type>::max() - old_num);
        set_num(old_num + count);
    }
    void add_defaulted(size_type const count) { add_uninitialised(count); }
    void remove_at_swap(size_type const index, size_type const count) {
        auto const old_num{num()};
        ml::native_soa::require(index >= 0 && index <= old_num && count >= 0 &&
                                count <= old_num - index);
        auto const moved{std::min(count, old_num - index - count)};
        auto const source{old_num - moved};
        for (size_type i{}; i < moved; ++i) {
            entity_indices[index + i] = entity_indices[source + i];
        }
        for (size_type i{}; i < moved; ++i) {
            target_entity_indices[index + i] = target_entity_indices[source + i];
        }
        for (size_type i{}; i < moved; ++i) {
            locations.xs[index + i] = locations.xs[source + i];
        }
        for (size_type i{}; i < moved; ++i) {
            locations.ys[index + i] = locations.ys[source + i];
        }
        for (size_type i{}; i < moved; ++i) {
            locations.zs[index + i] = locations.zs[source + i];
        }
        for (size_type i{}; i < moved; ++i) {
            rotations.pitches[index + i] = rotations.pitches[source + i];
        }
        for (size_type i{}; i < moved; ++i) {
            rotations.yaws[index + i] = rotations.yaws[source + i];
        }
        for (size_type i{}; i < moved; ++i) {
            rotations.rolls[index + i] = rotations.rolls[source + i];
        }
        for (size_type i{}; i < moved; ++i) {
            teams[index + i] = teams[source + i];
        }
        for (size_type i{}; i < moved; ++i) {
            healths[index + i] = healths[source + i];
        }
        for (size_type i{}; i < moved; ++i) {
            initial_fighter_spawn_delays[index + i] = initial_fighter_spawn_delays[source + i];
        }
        for (size_type i{}; i < moved; ++i) {
            fighter_spawn_cooldowns[index + i] = fighter_spawn_cooldowns[source + i];
        }
        set_num(old_num - count);
    }
    void append_from(ConstView source) {
        auto const count{source.num()};
        ml::native_soa::require(count <= std::numeric_limits<size_type>::max() - num());
        source.validate_array_sizes();
        if (count == 0) {
            return;
        }
        {
            auto const address{reinterpret_cast<std::uintptr_t>(source.entity_indices.data())};
            auto const begin{reinterpret_cast<std::uintptr_t>(entity_indices.data())};
            ml::native_soa::require(address < begin || address >= begin + entity_indices.size() *
                                                                              sizeof(std::int32_t));
        }
        {
            auto const address{
                reinterpret_cast<std::uintptr_t>(source.target_entity_indices.data())};
            auto const begin{reinterpret_cast<std::uintptr_t>(target_entity_indices.data())};
            ml::native_soa::require(address < begin ||
                                    address >= begin + target_entity_indices.size() *
                                                           sizeof(std::int32_t));
        }
        {
            auto const address{reinterpret_cast<std::uintptr_t>(source.locations.xs.data())};
            auto const begin{reinterpret_cast<std::uintptr_t>(locations.xs.data())};
            ml::native_soa::require(address < begin ||
                                    address >= begin + locations.xs.size() * sizeof(float));
        }
        {
            auto const address{reinterpret_cast<std::uintptr_t>(source.locations.ys.data())};
            auto const begin{reinterpret_cast<std::uintptr_t>(locations.ys.data())};
            ml::native_soa::require(address < begin ||
                                    address >= begin + locations.ys.size() * sizeof(float));
        }
        {
            auto const address{reinterpret_cast<std::uintptr_t>(source.locations.zs.data())};
            auto const begin{reinterpret_cast<std::uintptr_t>(locations.zs.data())};
            ml::native_soa::require(address < begin ||
                                    address >= begin + locations.zs.size() * sizeof(float));
        }
        {
            auto const address{reinterpret_cast<std::uintptr_t>(source.rotations.pitches.data())};
            auto const begin{reinterpret_cast<std::uintptr_t>(rotations.pitches.data())};
            ml::native_soa::require(address < begin ||
                                    address >= begin + rotations.pitches.size() * sizeof(float));
        }
        {
            auto const address{reinterpret_cast<std::uintptr_t>(source.rotations.yaws.data())};
            auto const begin{reinterpret_cast<std::uintptr_t>(rotations.yaws.data())};
            ml::native_soa::require(address < begin ||
                                    address >= begin + rotations.yaws.size() * sizeof(float));
        }
        {
            auto const address{reinterpret_cast<std::uintptr_t>(source.rotations.rolls.data())};
            auto const begin{reinterpret_cast<std::uintptr_t>(rotations.rolls.data())};
            ml::native_soa::require(address < begin ||
                                    address >= begin + rotations.rolls.size() * sizeof(float));
        }
        {
            auto const address{reinterpret_cast<std::uintptr_t>(source.teams.data())};
            auto const begin{reinterpret_cast<std::uintptr_t>(teams.data())};
            ml::native_soa::require(address < begin ||
                                    address >= begin + teams.size() * sizeof(ioj::sim::Team));
        }
        {
            auto const address{reinterpret_cast<std::uintptr_t>(source.healths.data())};
            auto const begin{reinterpret_cast<std::uintptr_t>(healths.data())};
            ml::native_soa::require(address < begin ||
                                    address >= begin + healths.size() * sizeof(std::int32_t));
        }
        {
            auto const address{
                reinterpret_cast<std::uintptr_t>(source.initial_fighter_spawn_delays.data())};
            auto const begin{reinterpret_cast<std::uintptr_t>(initial_fighter_spawn_delays.data())};
            ml::native_soa::require(address < begin ||
                                    address >= begin + initial_fighter_spawn_delays.size() *
                                                           sizeof(float));
        }
        {
            auto const address{
                reinterpret_cast<std::uintptr_t>(source.fighter_spawn_cooldowns.data())};
            auto const begin{reinterpret_cast<std::uintptr_t>(fighter_spawn_cooldowns.data())};
            ml::native_soa::require(address < begin ||
                                    address >=
                                        begin + fighter_spawn_cooldowns.size() * sizeof(float));
        }
        entity_indices.insert(
            entity_indices.end(), source.entity_indices.begin(), source.entity_indices.end());
        target_entity_indices.insert(target_entity_indices.end(),
                                     source.target_entity_indices.begin(),
                                     source.target_entity_indices.end());
        locations.xs.insert(
            locations.xs.end(), source.locations.xs.begin(), source.locations.xs.end());
        locations.ys.insert(
            locations.ys.end(), source.locations.ys.begin(), source.locations.ys.end());
        locations.zs.insert(
            locations.zs.end(), source.locations.zs.begin(), source.locations.zs.end());
        rotations.pitches.insert(rotations.pitches.end(),
                                 source.rotations.pitches.begin(),
                                 source.rotations.pitches.end());
        rotations.yaws.insert(
            rotations.yaws.end(), source.rotations.yaws.begin(), source.rotations.yaws.end());
        rotations.rolls.insert(
            rotations.rolls.end(), source.rotations.rolls.begin(), source.rotations.rolls.end());
        teams.insert(teams.end(), source.teams.begin(), source.teams.end());
        healths.insert(healths.end(), source.healths.begin(), source.healths.end());
        initial_fighter_spawn_delays.insert(initial_fighter_spawn_delays.end(),
                                            source.initial_fighter_spawn_delays.begin(),
                                            source.initial_fighter_spawn_delays.end());
        fighter_spawn_cooldowns.insert(fighter_spawn_cooldowns.end(),
                                       source.fighter_spawn_cooldowns.begin(),
                                       source.fighter_spawn_cooldowns.end());
    }
    auto get_view() -> View {
        return {
            entity_indices,
            target_entity_indices,
            locations.get_view(),
            rotations.get_view(),
            teams,
            healths,
            initial_fighter_spawn_delays,
            fighter_spawn_cooldowns,
        };
    }
    auto get_view() const -> ConstView {
        return {
            entity_indices,
            target_entity_indices,
            locations.get_view(),
            rotations.get_view(),
            teams,
            healths,
            initial_fighter_spawn_delays,
            fighter_spawn_cooldowns,
        };
    }
    auto get_const_view() const -> ConstView { return get_view(); }
    auto get_view(size_type const offset, size_type const count) -> View {
        return get_view().slice(offset, count);
    }
    auto get_view(size_type const offset, size_type const count) const -> ConstView {
        return get_view().slice(offset, count);
    }
    auto get_const_view(size_type const offset, size_type const count) const -> ConstView {
        return get_const_view().slice(offset, count);
    }
    auto slice(size_type const offset, size_type const count) -> View {
        return get_view(offset, count);
    }
    auto slice(size_type const offset, size_type const count) const -> ConstView {
        return get_const_view(offset, count);
    }
    auto left(size_type const count) -> View { return slice(0, count); }
    auto right(size_type const count) -> View { return slice(num() - count, count); }
    auto left(size_type const count) const -> ConstView { return slice(0, count); }
    auto right(size_type const count) const -> ConstView { return slice(num() - count, count); }
    template <typename Other>
    void copy_element(size_type const dst_index, Other const& other, size_type const src_index) {
        entity_indices[static_cast<std::size_t>(dst_index)] =
            other.entity_indices[static_cast<std::size_t>(src_index)];
        target_entity_indices[static_cast<std::size_t>(dst_index)] =
            other.target_entity_indices[static_cast<std::size_t>(src_index)];
        locations.copy_element(dst_index, other.locations, src_index);
        rotations.copy_element(dst_index, other.rotations, src_index);
        teams[static_cast<std::size_t>(dst_index)] =
            other.teams[static_cast<std::size_t>(src_index)];
        healths[static_cast<std::size_t>(dst_index)] =
            other.healths[static_cast<std::size_t>(src_index)];
        initial_fighter_spawn_delays[static_cast<std::size_t>(dst_index)] =
            other.initial_fighter_spawn_delays[static_cast<std::size_t>(src_index)];
        fighter_spawn_cooldowns[static_cast<std::size_t>(dst_index)] =
            other.fighter_spawn_cooldowns[static_cast<std::size_t>(src_index)];
    }
    template <typename Other>
    void copy_elements(size_type const dst_index,
                       Other const& other,
                       size_type const src_index,
                       size_type const count) {
        for (size_type i{}; i < count; ++i) {
            copy_element(dst_index + i, other, src_index + i);
        }
    }
    void apply_permutation(std::span<std::int32_t> const indices) {
        validate_array_sizes();
        ml::native_soa::require(indices.size() == static_cast<std::size_t>(num()));
        each_column([indices](auto& column) { ml::apply_permutation(std::span{column}, indices); });
    }
    template <typename Compare>
    void sort(Compare&& compare, std::span<std::int32_t> const scratch_indices) {
        validate_array_sizes();
        ml::native_soa::require(scratch_indices.size() == static_cast<std::size_t>(num()));
        for (size_type i{}; i < num(); ++i) {
            scratch_indices[static_cast<std::size_t>(i)] = i;
        }
        std::sort(scratch_indices.begin(),
                  scratch_indices.end(),
                  [this, &compare](size_type const lhs, size_type const rhs) {
                      return compare(*this, lhs, rhs);
                  });
        apply_permutation(scratch_indices);
    }
};

struct LevelTurretSpawnEventsView;
struct LevelTurretSpawnEventsConstView;
struct LevelTurretSpawnEventsConstView {
    using View = LevelTurretSpawnEventsView;
    using ConstView = LevelTurretSpawnEventsConstView;
    using size_type = std::int32_t;
    std::span<std::int32_t const> entity_indices;
    Vectors3fConstView locations;
    Rotators3fConstView rotations;
    std::span<ioj::sim::Team const> teams;
    std::span<std::int32_t const> healths;
    std::span<std::int32_t const> laser_damages;
    auto num() const noexcept -> size_type { return static_cast<size_type>(entity_indices.size()); }
    auto is_empty() const noexcept -> bool { return num() == 0; }
    template <typename Fn>
    void each_column(Fn&& fn) const {
        fn(entity_indices);
        fn(locations.xs);
        fn(locations.ys);
        fn(locations.zs);
        fn(rotations.pitches);
        fn(rotations.yaws);
        fn(rotations.rolls);
        fn(teams);
        fn(healths);
        fn(laser_damages);
    }
    void validate_array_sizes() const {
        auto const count{num()};
        each_column([count](auto column) {
            ml::native_soa::require(column.size() == static_cast<std::size_t>(count));
        });
    }
    auto slice(size_type const offset, size_type const count) const
        -> LevelTurretSpawnEventsConstView {
        ml::native_soa::require(offset >= 0 && count >= 0 && offset <= num() &&
                                count <= num() - offset);
        return {
            entity_indices.subspan(static_cast<std::size_t>(offset),
                                   static_cast<std::size_t>(count)),
            locations.slice(offset, count),
            rotations.slice(offset, count),
            teams.subspan(static_cast<std::size_t>(offset), static_cast<std::size_t>(count)),
            healths.subspan(static_cast<std::size_t>(offset), static_cast<std::size_t>(count)),
            laser_damages.subspan(static_cast<std::size_t>(offset),
                                  static_cast<std::size_t>(count)),
        };
    }
    auto get_view() const -> LevelTurretSpawnEventsConstView { return *this; }
    auto get_view(size_type const offset, size_type const count) const
        -> LevelTurretSpawnEventsConstView {
        return slice(offset, count);
    }
    auto get_const_view() const -> ConstView {
        return {
            entity_indices,
            locations.get_const_view(),
            rotations.get_const_view(),
            teams,
            healths,
            laser_damages,
        };
    }
    auto get_const_view(size_type const offset, size_type const count) const -> ConstView {
        return get_const_view().slice(offset, count);
    }
    auto left(size_type const count) const -> LevelTurretSpawnEventsConstView {
        return slice(0, count);
    }
    auto right(size_type const count) const -> LevelTurretSpawnEventsConstView {
        return slice(num() - count, count);
    }
};
struct LevelTurretSpawnEventsView {
    using View = LevelTurretSpawnEventsView;
    using ConstView = LevelTurretSpawnEventsConstView;
    using size_type = std::int32_t;
    std::span<std::int32_t> entity_indices;
    Vectors3fView locations;
    Rotators3fView rotations;
    std::span<ioj::sim::Team> teams;
    std::span<std::int32_t> healths;
    std::span<std::int32_t> laser_damages;
    auto num() const noexcept -> size_type { return static_cast<size_type>(entity_indices.size()); }
    auto is_empty() const noexcept -> bool { return num() == 0; }
    template <typename Fn>
    void each_column(Fn&& fn) const {
        fn(entity_indices);
        fn(locations.xs);
        fn(locations.ys);
        fn(locations.zs);
        fn(rotations.pitches);
        fn(rotations.yaws);
        fn(rotations.rolls);
        fn(teams);
        fn(healths);
        fn(laser_damages);
    }
    void validate_array_sizes() const {
        auto const count{num()};
        each_column([count](auto column) {
            ml::native_soa::require(column.size() == static_cast<std::size_t>(count));
        });
    }
    auto slice(size_type const offset, size_type const count) const -> LevelTurretSpawnEventsView {
        ml::native_soa::require(offset >= 0 && count >= 0 && offset <= num() &&
                                count <= num() - offset);
        return {
            entity_indices.subspan(static_cast<std::size_t>(offset),
                                   static_cast<std::size_t>(count)),
            locations.slice(offset, count),
            rotations.slice(offset, count),
            teams.subspan(static_cast<std::size_t>(offset), static_cast<std::size_t>(count)),
            healths.subspan(static_cast<std::size_t>(offset), static_cast<std::size_t>(count)),
            laser_damages.subspan(static_cast<std::size_t>(offset),
                                  static_cast<std::size_t>(count)),
        };
    }
    auto get_view() const -> LevelTurretSpawnEventsView { return *this; }
    auto get_view(size_type const offset, size_type const count) const
        -> LevelTurretSpawnEventsView {
        return slice(offset, count);
    }
    auto get_const_view() const -> ConstView {
        return {
            entity_indices,
            locations.get_const_view(),
            rotations.get_const_view(),
            teams,
            healths,
            laser_damages,
        };
    }
    auto get_const_view(size_type const offset, size_type const count) const -> ConstView {
        return get_const_view().slice(offset, count);
    }
    auto left(size_type const count) const -> LevelTurretSpawnEventsView { return slice(0, count); }
    auto right(size_type const count) const -> LevelTurretSpawnEventsView {
        return slice(num() - count, count);
    }
};
struct LevelTurretSpawnEvents {
    using View = LevelTurretSpawnEventsView;
    using ConstView = LevelTurretSpawnEventsConstView;
    using size_type = std::int32_t;
    ml::native_soa::Vector<std::int32_t> entity_indices;
    Vectors3f locations;
    Rotators3f rotations;
    ml::native_soa::Vector<ioj::sim::Team> teams;
    ml::native_soa::Vector<std::int32_t> healths;
    ml::native_soa::Vector<std::int32_t> laser_damages;
    auto num() const noexcept -> size_type { return static_cast<size_type>(entity_indices.size()); }
    auto is_empty() const noexcept -> bool { return num() == 0; }
    template <typename Fn>
    void each_column(Fn&& fn) {
        fn(entity_indices);
        fn(locations.xs);
        fn(locations.ys);
        fn(locations.zs);
        fn(rotations.pitches);
        fn(rotations.yaws);
        fn(rotations.rolls);
        fn(teams);
        fn(healths);
        fn(laser_damages);
    }
    template <typename Fn>
    void each_column(Fn&& fn) const {
        fn(entity_indices);
        fn(locations.xs);
        fn(locations.ys);
        fn(locations.zs);
        fn(rotations.pitches);
        fn(rotations.yaws);
        fn(rotations.rolls);
        fn(teams);
        fn(healths);
        fn(laser_damages);
    }
    void validate_array_sizes() const { get_const_view().validate_array_sizes(); }
    void reserve(size_type const count) {
        ml::native_soa::require(count >= 0);
        entity_indices.reserve(static_cast<std::size_t>(count));
        locations.xs.reserve(static_cast<std::size_t>(count));
        locations.ys.reserve(static_cast<std::size_t>(count));
        locations.zs.reserve(static_cast<std::size_t>(count));
        rotations.pitches.reserve(static_cast<std::size_t>(count));
        rotations.yaws.reserve(static_cast<std::size_t>(count));
        rotations.rolls.reserve(static_cast<std::size_t>(count));
        teams.reserve(static_cast<std::size_t>(count));
        healths.reserve(static_cast<std::size_t>(count));
        laser_damages.reserve(static_cast<std::size_t>(count));
    }
    void reset() noexcept {
        entity_indices.clear();
        locations.xs.clear();
        locations.ys.clear();
        locations.zs.clear();
        rotations.pitches.clear();
        rotations.yaws.clear();
        rotations.rolls.clear();
        teams.clear();
        healths.clear();
        laser_damages.clear();
    }
    void set_num(size_type const count) {
        ml::native_soa::require(count >= 0);
        auto const size{static_cast<std::size_t>(count)};
        entity_indices.resize(size);
        locations.xs.resize(size);
        locations.ys.resize(size);
        locations.zs.resize(size);
        rotations.pitches.resize(size);
        rotations.yaws.resize(size);
        rotations.rolls.resize(size);
        teams.resize(size);
        healths.resize(size);
        laser_damages.resize(size);
    }
    void add_uninitialised(size_type const count) {
        auto const old_num{num()};
        ml::native_soa::require(count >= 0 &&
                                count <= std::numeric_limits<size_type>::max() - old_num);
        set_num(old_num + count);
    }
    void add_defaulted(size_type const count) { add_uninitialised(count); }
    void remove_at_swap(size_type const index, size_type const count) {
        auto const old_num{num()};
        ml::native_soa::require(index >= 0 && index <= old_num && count >= 0 &&
                                count <= old_num - index);
        auto const moved{std::min(count, old_num - index - count)};
        auto const source{old_num - moved};
        for (size_type i{}; i < moved; ++i) {
            entity_indices[index + i] = entity_indices[source + i];
        }
        for (size_type i{}; i < moved; ++i) {
            locations.xs[index + i] = locations.xs[source + i];
        }
        for (size_type i{}; i < moved; ++i) {
            locations.ys[index + i] = locations.ys[source + i];
        }
        for (size_type i{}; i < moved; ++i) {
            locations.zs[index + i] = locations.zs[source + i];
        }
        for (size_type i{}; i < moved; ++i) {
            rotations.pitches[index + i] = rotations.pitches[source + i];
        }
        for (size_type i{}; i < moved; ++i) {
            rotations.yaws[index + i] = rotations.yaws[source + i];
        }
        for (size_type i{}; i < moved; ++i) {
            rotations.rolls[index + i] = rotations.rolls[source + i];
        }
        for (size_type i{}; i < moved; ++i) {
            teams[index + i] = teams[source + i];
        }
        for (size_type i{}; i < moved; ++i) {
            healths[index + i] = healths[source + i];
        }
        for (size_type i{}; i < moved; ++i) {
            laser_damages[index + i] = laser_damages[source + i];
        }
        set_num(old_num - count);
    }
    void append_from(ConstView source) {
        auto const count{source.num()};
        ml::native_soa::require(count <= std::numeric_limits<size_type>::max() - num());
        source.validate_array_sizes();
        if (count == 0) {
            return;
        }
        {
            auto const address{reinterpret_cast<std::uintptr_t>(source.entity_indices.data())};
            auto const begin{reinterpret_cast<std::uintptr_t>(entity_indices.data())};
            ml::native_soa::require(address < begin || address >= begin + entity_indices.size() *
                                                                              sizeof(std::int32_t));
        }
        {
            auto const address{reinterpret_cast<std::uintptr_t>(source.locations.xs.data())};
            auto const begin{reinterpret_cast<std::uintptr_t>(locations.xs.data())};
            ml::native_soa::require(address < begin ||
                                    address >= begin + locations.xs.size() * sizeof(float));
        }
        {
            auto const address{reinterpret_cast<std::uintptr_t>(source.locations.ys.data())};
            auto const begin{reinterpret_cast<std::uintptr_t>(locations.ys.data())};
            ml::native_soa::require(address < begin ||
                                    address >= begin + locations.ys.size() * sizeof(float));
        }
        {
            auto const address{reinterpret_cast<std::uintptr_t>(source.locations.zs.data())};
            auto const begin{reinterpret_cast<std::uintptr_t>(locations.zs.data())};
            ml::native_soa::require(address < begin ||
                                    address >= begin + locations.zs.size() * sizeof(float));
        }
        {
            auto const address{reinterpret_cast<std::uintptr_t>(source.rotations.pitches.data())};
            auto const begin{reinterpret_cast<std::uintptr_t>(rotations.pitches.data())};
            ml::native_soa::require(address < begin ||
                                    address >= begin + rotations.pitches.size() * sizeof(float));
        }
        {
            auto const address{reinterpret_cast<std::uintptr_t>(source.rotations.yaws.data())};
            auto const begin{reinterpret_cast<std::uintptr_t>(rotations.yaws.data())};
            ml::native_soa::require(address < begin ||
                                    address >= begin + rotations.yaws.size() * sizeof(float));
        }
        {
            auto const address{reinterpret_cast<std::uintptr_t>(source.rotations.rolls.data())};
            auto const begin{reinterpret_cast<std::uintptr_t>(rotations.rolls.data())};
            ml::native_soa::require(address < begin ||
                                    address >= begin + rotations.rolls.size() * sizeof(float));
        }
        {
            auto const address{reinterpret_cast<std::uintptr_t>(source.teams.data())};
            auto const begin{reinterpret_cast<std::uintptr_t>(teams.data())};
            ml::native_soa::require(address < begin ||
                                    address >= begin + teams.size() * sizeof(ioj::sim::Team));
        }
        {
            auto const address{reinterpret_cast<std::uintptr_t>(source.healths.data())};
            auto const begin{reinterpret_cast<std::uintptr_t>(healths.data())};
            ml::native_soa::require(address < begin ||
                                    address >= begin + healths.size() * sizeof(std::int32_t));
        }
        {
            auto const address{reinterpret_cast<std::uintptr_t>(source.laser_damages.data())};
            auto const begin{reinterpret_cast<std::uintptr_t>(laser_damages.data())};
            ml::native_soa::require(address < begin ||
                                    address >= begin + laser_damages.size() * sizeof(std::int32_t));
        }
        entity_indices.insert(
            entity_indices.end(), source.entity_indices.begin(), source.entity_indices.end());
        locations.xs.insert(
            locations.xs.end(), source.locations.xs.begin(), source.locations.xs.end());
        locations.ys.insert(
            locations.ys.end(), source.locations.ys.begin(), source.locations.ys.end());
        locations.zs.insert(
            locations.zs.end(), source.locations.zs.begin(), source.locations.zs.end());
        rotations.pitches.insert(rotations.pitches.end(),
                                 source.rotations.pitches.begin(),
                                 source.rotations.pitches.end());
        rotations.yaws.insert(
            rotations.yaws.end(), source.rotations.yaws.begin(), source.rotations.yaws.end());
        rotations.rolls.insert(
            rotations.rolls.end(), source.rotations.rolls.begin(), source.rotations.rolls.end());
        teams.insert(teams.end(), source.teams.begin(), source.teams.end());
        healths.insert(healths.end(), source.healths.begin(), source.healths.end());
        laser_damages.insert(
            laser_damages.end(), source.laser_damages.begin(), source.laser_damages.end());
    }
    auto get_view() -> View {
        return {
            entity_indices,
            locations.get_view(),
            rotations.get_view(),
            teams,
            healths,
            laser_damages,
        };
    }
    auto get_view() const -> ConstView {
        return {
            entity_indices,
            locations.get_view(),
            rotations.get_view(),
            teams,
            healths,
            laser_damages,
        };
    }
    auto get_const_view() const -> ConstView { return get_view(); }
    auto get_view(size_type const offset, size_type const count) -> View {
        return get_view().slice(offset, count);
    }
    auto get_view(size_type const offset, size_type const count) const -> ConstView {
        return get_view().slice(offset, count);
    }
    auto get_const_view(size_type const offset, size_type const count) const -> ConstView {
        return get_const_view().slice(offset, count);
    }
    auto slice(size_type const offset, size_type const count) -> View {
        return get_view(offset, count);
    }
    auto slice(size_type const offset, size_type const count) const -> ConstView {
        return get_const_view(offset, count);
    }
    auto left(size_type const count) -> View { return slice(0, count); }
    auto right(size_type const count) -> View { return slice(num() - count, count); }
    auto left(size_type const count) const -> ConstView { return slice(0, count); }
    auto right(size_type const count) const -> ConstView { return slice(num() - count, count); }
    template <typename Other>
    void copy_element(size_type const dst_index, Other const& other, size_type const src_index) {
        entity_indices[static_cast<std::size_t>(dst_index)] =
            other.entity_indices[static_cast<std::size_t>(src_index)];
        locations.copy_element(dst_index, other.locations, src_index);
        rotations.copy_element(dst_index, other.rotations, src_index);
        teams[static_cast<std::size_t>(dst_index)] =
            other.teams[static_cast<std::size_t>(src_index)];
        healths[static_cast<std::size_t>(dst_index)] =
            other.healths[static_cast<std::size_t>(src_index)];
        laser_damages[static_cast<std::size_t>(dst_index)] =
            other.laser_damages[static_cast<std::size_t>(src_index)];
    }
    template <typename Other>
    void copy_elements(size_type const dst_index,
                       Other const& other,
                       size_type const src_index,
                       size_type const count) {
        for (size_type i{}; i < count; ++i) {
            copy_element(dst_index + i, other, src_index + i);
        }
    }
    void apply_permutation(std::span<std::int32_t> const indices) {
        validate_array_sizes();
        ml::native_soa::require(indices.size() == static_cast<std::size_t>(num()));
        each_column([indices](auto& column) { ml::apply_permutation(std::span{column}, indices); });
    }
    template <typename Compare>
    void sort(Compare&& compare, std::span<std::int32_t> const scratch_indices) {
        validate_array_sizes();
        ml::native_soa::require(scratch_indices.size() == static_cast<std::size_t>(num()));
        for (size_type i{}; i < num(); ++i) {
            scratch_indices[static_cast<std::size_t>(i)] = i;
        }
        std::sort(scratch_indices.begin(),
                  scratch_indices.end(),
                  [this, &compare](size_type const lhs, size_type const rhs) {
                      return compare(*this, lhs, rhs);
                  });
        apply_permutation(scratch_indices);
    }
};

struct LevelMissionEventGroupsView;
struct LevelMissionEventGroupsConstView;
struct LevelMissionEventGroupsConstView {
    using View = LevelMissionEventGroupsView;
    using ConstView = LevelMissionEventGroupsConstView;
    using size_type = std::int32_t;
    std::span<ioj::sim::LevelMissionEventType const> types;
    std::span<std::int32_t const> offsets;
    std::span<ioj::sim::LevelEventCount const> counts;
    auto num() const noexcept -> size_type { return static_cast<size_type>(types.size()); }
    auto is_empty() const noexcept -> bool { return num() == 0; }
    template <typename Fn>
    void each_column(Fn&& fn) const {
        fn(types);
        fn(offsets);
        fn(counts);
    }
    void validate_array_sizes() const {
        auto const count{num()};
        each_column([count](auto column) {
            ml::native_soa::require(column.size() == static_cast<std::size_t>(count));
        });
    }
    auto slice(size_type const offset, size_type const count) const
        -> LevelMissionEventGroupsConstView {
        ml::native_soa::require(offset >= 0 && count >= 0 && offset <= num() &&
                                count <= num() - offset);
        return {
            types.subspan(static_cast<std::size_t>(offset), static_cast<std::size_t>(count)),
            offsets.subspan(static_cast<std::size_t>(offset), static_cast<std::size_t>(count)),
            counts.subspan(static_cast<std::size_t>(offset), static_cast<std::size_t>(count)),
        };
    }
    auto get_view() const -> LevelMissionEventGroupsConstView { return *this; }
    auto get_view(size_type const offset, size_type const count) const
        -> LevelMissionEventGroupsConstView {
        return slice(offset, count);
    }
    auto get_const_view() const -> ConstView {
        return {
            types,
            offsets,
            counts,
        };
    }
    auto get_const_view(size_type const offset, size_type const count) const -> ConstView {
        return get_const_view().slice(offset, count);
    }
    auto left(size_type const count) const -> LevelMissionEventGroupsConstView {
        return slice(0, count);
    }
    auto right(size_type const count) const -> LevelMissionEventGroupsConstView {
        return slice(num() - count, count);
    }
};
struct LevelMissionEventGroupsView {
    using View = LevelMissionEventGroupsView;
    using ConstView = LevelMissionEventGroupsConstView;
    using size_type = std::int32_t;
    std::span<ioj::sim::LevelMissionEventType> types;
    std::span<std::int32_t> offsets;
    std::span<ioj::sim::LevelEventCount> counts;
    auto num() const noexcept -> size_type { return static_cast<size_type>(types.size()); }
    auto is_empty() const noexcept -> bool { return num() == 0; }
    template <typename Fn>
    void each_column(Fn&& fn) const {
        fn(types);
        fn(offsets);
        fn(counts);
    }
    void validate_array_sizes() const {
        auto const count{num()};
        each_column([count](auto column) {
            ml::native_soa::require(column.size() == static_cast<std::size_t>(count));
        });
    }
    auto slice(size_type const offset, size_type const count) const -> LevelMissionEventGroupsView {
        ml::native_soa::require(offset >= 0 && count >= 0 && offset <= num() &&
                                count <= num() - offset);
        return {
            types.subspan(static_cast<std::size_t>(offset), static_cast<std::size_t>(count)),
            offsets.subspan(static_cast<std::size_t>(offset), static_cast<std::size_t>(count)),
            counts.subspan(static_cast<std::size_t>(offset), static_cast<std::size_t>(count)),
        };
    }
    auto get_view() const -> LevelMissionEventGroupsView { return *this; }
    auto get_view(size_type const offset, size_type const count) const
        -> LevelMissionEventGroupsView {
        return slice(offset, count);
    }
    auto get_const_view() const -> ConstView {
        return {
            types,
            offsets,
            counts,
        };
    }
    auto get_const_view(size_type const offset, size_type const count) const -> ConstView {
        return get_const_view().slice(offset, count);
    }
    auto left(size_type const count) const -> LevelMissionEventGroupsView {
        return slice(0, count);
    }
    auto right(size_type const count) const -> LevelMissionEventGroupsView {
        return slice(num() - count, count);
    }
    void set(size_type const index,
             ioj::sim::LevelMissionEventType const new_types,
             std::int32_t const new_offsets,
             ioj::sim::LevelEventCount const new_counts) const {
        ml::native_soa::require(index >= 0 && index < num());
        types[static_cast<std::size_t>(index)] = new_types;
        offsets[static_cast<std::size_t>(index)] = new_offsets;
        counts[static_cast<std::size_t>(index)] = new_counts;
    }
};
struct LevelMissionEventGroups {
    using View = LevelMissionEventGroupsView;
    using ConstView = LevelMissionEventGroupsConstView;
    using size_type = std::int32_t;
    ml::native_soa::Vector<ioj::sim::LevelMissionEventType> types;
    ml::native_soa::Vector<std::int32_t> offsets;
    ml::native_soa::Vector<ioj::sim::LevelEventCount> counts;
    auto num() const noexcept -> size_type { return static_cast<size_type>(types.size()); }
    auto is_empty() const noexcept -> bool { return num() == 0; }
    template <typename Fn>
    void each_column(Fn&& fn) {
        fn(types);
        fn(offsets);
        fn(counts);
    }
    template <typename Fn>
    void each_column(Fn&& fn) const {
        fn(types);
        fn(offsets);
        fn(counts);
    }
    void validate_array_sizes() const { get_const_view().validate_array_sizes(); }
    void reserve(size_type const count) {
        ml::native_soa::require(count >= 0);
        types.reserve(static_cast<std::size_t>(count));
        offsets.reserve(static_cast<std::size_t>(count));
        counts.reserve(static_cast<std::size_t>(count));
    }
    void reset() noexcept {
        types.clear();
        offsets.clear();
        counts.clear();
    }
    void set_num(size_type const count) {
        ml::native_soa::require(count >= 0);
        auto const size{static_cast<std::size_t>(count)};
        types.resize(size);
        offsets.resize(size);
        counts.resize(size);
    }
    void add_uninitialised(size_type const count) {
        auto const old_num{num()};
        ml::native_soa::require(count >= 0 &&
                                count <= std::numeric_limits<size_type>::max() - old_num);
        set_num(old_num + count);
    }
    void add_defaulted(size_type const count) { add_uninitialised(count); }
    void remove_at_swap(size_type const index, size_type const count) {
        auto const old_num{num()};
        ml::native_soa::require(index >= 0 && index <= old_num && count >= 0 &&
                                count <= old_num - index);
        auto const moved{std::min(count, old_num - index - count)};
        auto const source{old_num - moved};
        for (size_type i{}; i < moved; ++i) {
            types[index + i] = types[source + i];
        }
        for (size_type i{}; i < moved; ++i) {
            offsets[index + i] = offsets[source + i];
        }
        for (size_type i{}; i < moved; ++i) {
            counts[index + i] = counts[source + i];
        }
        set_num(old_num - count);
    }
    void set(size_type const index,
             ioj::sim::LevelMissionEventType const new_types,
             std::int32_t const new_offsets,
             ioj::sim::LevelEventCount const new_counts) {
        get_view().set(index, new_types, new_offsets, new_counts);
    }
    auto add(ioj::sim::LevelMissionEventType const new_types,
             std::int32_t const new_offsets,
             ioj::sim::LevelEventCount const new_counts) -> size_type {
        auto const index{num()};
        add_defaulted(1);
        set(index, new_types, new_offsets, new_counts);
        return index;
    }
    void append_from(ConstView source) {
        auto const count{source.num()};
        ml::native_soa::require(count <= std::numeric_limits<size_type>::max() - num());
        source.validate_array_sizes();
        if (count == 0) {
            return;
        }
        {
            auto const address{reinterpret_cast<std::uintptr_t>(source.types.data())};
            auto const begin{reinterpret_cast<std::uintptr_t>(types.data())};
            ml::native_soa::require(address < begin ||
                                    address >= begin + types.size() *
                                                           sizeof(ioj::sim::LevelMissionEventType));
        }
        {
            auto const address{reinterpret_cast<std::uintptr_t>(source.offsets.data())};
            auto const begin{reinterpret_cast<std::uintptr_t>(offsets.data())};
            ml::native_soa::require(address < begin ||
                                    address >= begin + offsets.size() * sizeof(std::int32_t));
        }
        {
            auto const address{reinterpret_cast<std::uintptr_t>(source.counts.data())};
            auto const begin{reinterpret_cast<std::uintptr_t>(counts.data())};
            ml::native_soa::require(address < begin ||
                                    address >=
                                        begin + counts.size() * sizeof(ioj::sim::LevelEventCount));
        }
        types.insert(types.end(), source.types.begin(), source.types.end());
        offsets.insert(offsets.end(), source.offsets.begin(), source.offsets.end());
        counts.insert(counts.end(), source.counts.begin(), source.counts.end());
    }
    auto get_view() -> View {
        return {
            types,
            offsets,
            counts,
        };
    }
    auto get_view() const -> ConstView {
        return {
            types,
            offsets,
            counts,
        };
    }
    auto get_const_view() const -> ConstView { return get_view(); }
    auto get_view(size_type const offset, size_type const count) -> View {
        return get_view().slice(offset, count);
    }
    auto get_view(size_type const offset, size_type const count) const -> ConstView {
        return get_view().slice(offset, count);
    }
    auto get_const_view(size_type const offset, size_type const count) const -> ConstView {
        return get_const_view().slice(offset, count);
    }
    auto slice(size_type const offset, size_type const count) -> View {
        return get_view(offset, count);
    }
    auto slice(size_type const offset, size_type const count) const -> ConstView {
        return get_const_view(offset, count);
    }
    auto left(size_type const count) -> View { return slice(0, count); }
    auto right(size_type const count) -> View { return slice(num() - count, count); }
    auto left(size_type const count) const -> ConstView { return slice(0, count); }
    auto right(size_type const count) const -> ConstView { return slice(num() - count, count); }
    template <typename Other>
    void copy_element(size_type const dst_index, Other const& other, size_type const src_index) {
        types[static_cast<std::size_t>(dst_index)] =
            other.types[static_cast<std::size_t>(src_index)];
        offsets[static_cast<std::size_t>(dst_index)] =
            other.offsets[static_cast<std::size_t>(src_index)];
        counts[static_cast<std::size_t>(dst_index)] =
            other.counts[static_cast<std::size_t>(src_index)];
    }
    template <typename Other>
    void copy_elements(size_type const dst_index,
                       Other const& other,
                       size_type const src_index,
                       size_type const count) {
        for (size_type i{}; i < count; ++i) {
            copy_element(dst_index + i, other, src_index + i);
        }
    }
    void apply_permutation(std::span<std::int32_t> const indices) {
        validate_array_sizes();
        ml::native_soa::require(indices.size() == static_cast<std::size_t>(num()));
        each_column([indices](auto& column) { ml::apply_permutation(std::span{column}, indices); });
    }
    template <typename Compare>
    void sort(Compare&& compare, std::span<std::int32_t> const scratch_indices) {
        validate_array_sizes();
        ml::native_soa::require(scratch_indices.size() == static_cast<std::size_t>(num()));
        for (size_type i{}; i < num(); ++i) {
            scratch_indices[static_cast<std::size_t>(i)] = i;
        }
        std::sort(scratch_indices.begin(),
                  scratch_indices.end(),
                  [this, &compare](size_type const lhs, size_type const rhs) {
                      return compare(*this, lhs, rhs);
                  });
        apply_permutation(scratch_indices);
    }
};

} // namespace ioj::sim
