// clang-format off
// This file is autogenerated. Do not edit by hand.
// Edit Codegen/manifest.py and regenerate it instead.

#include "EntityDeathInfo.h"

void EntityDeathInfo::add(ETestDeathReason const reason,
                          FRegistryEntityHandle const victim,
                          FRegistryEntityHandle const killer) {
    reasons.Add(reason);
    victims.Add(victim);
    killers.Add(killer);
}
// clang-format on
