using Microsoft.VisualStudio.TestTools.UnitTesting;

namespace NativeBinaryTools.Tests;

[TestClass]
public sealed class MimallocSymbolTests
{
    [TestMethod]
    public void AllocatorIdentifiers_extracts_c_cpp_and_internal_identifiers_but_ignores_prefixed_symbols()
    {
        const string output = """
            00000000 T mi_malloc
            00000000 T void __cdecl _mi_heap_init(struct mi_heap_s *)
            00000000 R _mi_tls_callback_pre
            00000000 T sbx_mi_free
            """;

        CollectionAssert.AreEquivalent(
            new[] { "mi_malloc", "_mi_heap_init", "mi_heap_s", "_mi_tls_callback_pre" },
            MimallocSymbolParser.AllocatorIdentifiers(output).ToArray());
    }

    [TestMethod]
    public void LinkerIncludes_extracts_case_insensitive_include_directives()
    {
        var includes = MimallocSymbolParser.LinkerIncludes(" /INCLUDE:_tls_used /include:_mi_tls_callback_pre");

        CollectionAssert.AreEquivalent(new[] { "_tls_used", "_mi_tls_callback_pre" }, includes.ToArray());
    }

    [TestMethod]
    public void WithoutMsvcStringLiterals_removes_string_literal_symbol_lines()
    {
        const string output = """
            00000000 R ??_C@_07LDBHFKDL@mi_free?$AA@
            00000000 T mi_free
            """;

        Assert.AreEqual("00000000 T mi_free", MimallocSymbolParser.WithoutMsvcStringLiterals(output).Trim());
    }

    [TestMethod]
    public void IsMsvcOperatorNewDelete_matches_all_forbidden_forms_but_not_string_literals()
    {
        foreach (var symbol in new[] { "??2@", "??3@", "??_U@", "??_V@" })
        {
            Assert.IsTrue(MimallocSymbolParser.IsMsvcOperatorNewDelete(symbol));
        }

        Assert.IsFalse(MimallocSymbolParser.IsMsvcOperatorNewDelete("??_C@"));
    }

    [TestMethod]
    public void Render_sorts_prefixes_and_emits_only_mimalloc_linker_includes()
    {
        var header = MimallocSymbolHeaderRenderer.Render(
            new HashSet<string>(new[] { "mi_malloc", "_mi_tls_callback_pre", "_mi_heap_init" }, StringComparer.Ordinal),
            new HashSet<string>(new[] { "_mi_tls_callback_pre", "_tls_used" }, StringComparer.Ordinal));

        var expected = """
            // Generated by NativeBinaryTools mimalloc-symbols. Do not edit.
            #pragma once

            #define _mi_heap_init sbx__mi_heap_init
            #define _mi_tls_callback_pre sbx__mi_tls_callback_pre
            #define mi_malloc sbx_mi_malloc

            #if defined(_MSC_VER)
            #pragma comment(linker, "/include:sbx__mi_tls_callback_pre")
            #endif

            """.ReplaceLineEndings("\n");

        Assert.AreEqual(expected, header);
        Assert.IsFalse(header.Contains("sbx__tls_used", StringComparison.Ordinal));
    }

    [TestMethod]
    public async Task Generate_aggregates_objects_preserves_spaced_paths_and_writes_lf_only_header()
    {
        using var fixture = new TemporaryDirectory();
        var outputPath = Path.Combine(fixture.Path, "generated header.h");
        var runner = new RecordingProcessRunner(request =>
        {
            if (request.Arguments.Contains("--coff-directives"))
            {
                return new ProcessResult(0, " /INCLUDE:_tls_used /INCLUDE:_mi_tls_callback_pre", string.Empty);
            }

            return request.Arguments[^1].EndsWith("one.obj", StringComparison.Ordinal)
                ? new ProcessResult(0, "00000000 T mi_malloc", string.Empty)
                : new ProcessResult(0, "00000000 T _mi_tls_callback_pre", string.Empty);
        });
        var tool = new MimallocSymbolTool(runner, fixture.Path);
        var request = GenerateRequest(
            outputPath,
            "C:/LLVM Tools/llvm-nm.exe",
            "C:/LLVM Tools/llvm-readobj.exe",
            "C:/Objects with spaces/one.obj",
            "C:/Objects with spaces/two.obj");

        await tool.GenerateAsync(request, CancellationToken.None);

        Assert.AreEqual(4, runner.Requests.Count);
        Assert.AreEqual("C:/LLVM Tools/llvm-nm.exe", runner.Requests[0].FileName);
        CollectionAssert.AreEqual(
            new[] { "--defined-only", "--extern-only", "--demangle", "C:/Objects with spaces/one.obj" },
            runner.Requests[0].Arguments.ToArray());
        Assert.AreEqual("C:/LLVM Tools/llvm-readobj.exe", runner.Requests[2].FileName);
        var bytes = File.ReadAllBytes(outputPath);
        CollectionAssert.DoesNotContain(bytes, (byte)'\r');
        CollectionAssert.AreNotEqual(new byte[] { 0xef, 0xbb, 0xbf }, bytes.Take(3).ToArray());
        var header = File.ReadAllText(outputPath);
        StringAssert.Contains(header, "#define mi_malloc sbx_mi_malloc");
        StringAssert.Contains(header, "/include:sbx__mi_tls_callback_pre");
    }

    [TestMethod]
    public async Task Generate_fails_when_no_allocator_identifiers_are_exposed()
    {
        using var fixture = new TemporaryDirectory();
        var tool = new MimallocSymbolTool(new RecordingProcessRunner(_ => new ProcessResult(0, "nothing", string.Empty)), fixture.Path);

        var exception = await Assert.ThrowsExceptionAsync<MimallocSymbolToolException>(
            () => tool.GenerateAsync(GenerateRequest(Path.Combine(fixture.Path, "header.h")), CancellationToken.None));

        StringAssert.Contains(exception.Message, "no allocator identifiers");
    }

    [DataTestMethod]
    [DataRow("00000000 T mi_free", "", "", "Unprefixed externally visible mimalloc identifiers remain")]
    [DataRow("", "U _mi_heap_init", "", "Unprefixed mimalloc references remain")]
    [DataRow("", "", "malloc", "Allocator override symbols are defined: malloc")]
    [DataRow("", "", "??_V@YAXPEAX@Z", "Allocator override symbols are defined: ??_V@YAXPEAX@Z")]
    public async Task Verify_rejects_unprefixed_symbols_and_allocator_overrides(
        string externalOutput,
        string undefinedOutput,
        string rawOutput,
        string expectedDiagnostic)
    {
        using var fixture = new TemporaryDirectory();
        var tool = new MimallocSymbolTool(
            new RecordingProcessRunner(request => ResultForVerifyRequest(request, externalOutput, undefinedOutput, rawOutput, string.Empty)),
            fixture.Path);

        var exception = await Assert.ThrowsExceptionAsync<MimallocSymbolToolException>(
            () => tool.VerifyAsync(VerifyRequest(), CancellationToken.None));

        StringAssert.Contains(exception.Message, expectedDiagnostic);
    }

    [TestMethod]
    public async Task Verify_rejects_unprefixed_mimalloc_linker_includes()
    {
        using var fixture = new TemporaryDirectory();
        var tool = new MimallocSymbolTool(
            new RecordingProcessRunner(request => ResultForVerifyRequest(request, string.Empty, string.Empty, string.Empty, "/INCLUDE:_mi_tls_callback_pre")),
            fixture.Path);

        var exception = await Assert.ThrowsExceptionAsync<MimallocSymbolToolException>(
            () => tool.VerifyAsync(VerifyRequest(), CancellationToken.None));

        StringAssert.Contains(exception.Message, "Unprefixed mimalloc linker directives remain: _mi_tls_callback_pre");
    }

    [TestMethod]
    public async Task Verify_accepts_prefixed_symbols_and_unrelated_linker_includes()
    {
        using var fixture = new TemporaryDirectory();
        var tool = new MimallocSymbolTool(
            new RecordingProcessRunner(request => ResultForVerifyRequest(
                request,
                "00000000 T sbx_mi_malloc\n00000000 R ??_C@_07LDBHFKDL@mi_free?$AA@",
                "U sbx__mi_heap_init",
                "sbx_mi_malloc",
                "/INCLUDE:_tls_used /include:sbx__mi_tls_callback_pre")),
            fixture.Path);

        await tool.VerifyAsync(VerifyRequest(), CancellationToken.None);
    }

    [TestMethod]
    public async Task Generate_reports_nm_nonzero_exit_and_stderr()
    {
        using var fixture = new TemporaryDirectory();
        var tool = new MimallocSymbolTool(
            new RecordingProcessRunner(_ => new ProcessResult(7, string.Empty, "nm failure")),
            fixture.Path);

        var exception = await Assert.ThrowsExceptionAsync<MimallocSymbolToolException>(
            () => tool.GenerateAsync(GenerateRequest(Path.Combine(fixture.Path, "header.h")), CancellationToken.None));

        StringAssert.Contains(exception.Message, "exit code 7");
        StringAssert.Contains(exception.Message, "nm failure");
    }

    [TestMethod]
    public async Task Generate_reports_readobj_nonzero_exit()
    {
        using var fixture = new TemporaryDirectory();
        var tool = new MimallocSymbolTool(
            new RecordingProcessRunner(request => request.Arguments.Contains("--coff-directives")
                ? new ProcessResult(8, string.Empty, "readobj failure")
                : new ProcessResult(0, "mi_malloc", string.Empty)),
            fixture.Path);

        var exception = await Assert.ThrowsExceptionAsync<MimallocSymbolToolException>(
            () => tool.GenerateAsync(GenerateRequest(Path.Combine(fixture.Path, "header.h")), CancellationToken.None));

        StringAssert.Contains(exception.Message, "exit code 8");
        StringAssert.Contains(exception.Message, "readobj failure");
    }

    [TestMethod]
    public async Task Generate_reports_process_launch_and_timeout_failures()
    {
        using var fixture = new TemporaryDirectory();
        var launchTool = new MimallocSymbolTool(new ThrowingProcessRunner(new ProcessLaunchException("missing", new InvalidOperationException())), fixture.Path);
        var launchException = await Assert.ThrowsExceptionAsync<MimallocSymbolToolException>(
            () => launchTool.GenerateAsync(GenerateRequest(Path.Combine(fixture.Path, "header.h")), CancellationToken.None));
        StringAssert.Contains(launchException.Message, "Unable to run");

        var timeoutTool = new MimallocSymbolTool(new ThrowingProcessRunner(new ProcessTimeoutException("timed out")), fixture.Path);
        var timeoutException = await Assert.ThrowsExceptionAsync<MimallocSymbolToolException>(
            () => timeoutTool.GenerateAsync(GenerateRequest(Path.Combine(fixture.Path, "header.h")), CancellationToken.None));
        StringAssert.Contains(timeoutException.Message, "timed out");
    }

    [TestMethod]
    public void TryParse_accepts_the_extensible_command_shape_and_rejects_bad_arguments()
    {
        Assert.IsTrue(
            NativeBinaryToolsApplication.TryParse(
                ["mimalloc-symbols", "generate", "--nm", "nm", "--readobj", "readobj", "--output", "header", "object one.obj"],
                out var request,
                out _));
        Assert.AreEqual(MimallocSymbolCommand.Generate, request!.Command);
        Assert.AreEqual("header", request.OutputPath);
        CollectionAssert.AreEqual(new[] { "object one.obj" }, request.ObjectPaths.ToArray());

        Assert.IsFalse(NativeBinaryToolsApplication.TryParse(["mimalloc-symbols", "verify", "--nm", "nm"], out _, out _));
        Assert.IsFalse(NativeBinaryToolsApplication.TryParse(["mimalloc-symbols", "generate", "--nm", "nm", "--nm", "other", "--readobj", "readobj", "--output", "header", "object.obj"], out _, out _));
        Assert.IsFalse(NativeBinaryToolsApplication.TryParse(["other", "generate"], out _, out _));
    }

    private static MimallocSymbolRequest GenerateRequest(
        string outputPath,
        string nmPath = "llvm-nm",
        string readObjPath = "llvm-readobj",
        params string[] objectPaths)
    {
        return new MimallocSymbolRequest(
            MimallocSymbolCommand.Generate,
            nmPath,
            readObjPath,
            outputPath,
            objectPaths.Length == 0 ? ["mimalloc probe.obj"] : objectPaths);
    }

    private static MimallocSymbolRequest VerifyRequest()
    {
        return new MimallocSymbolRequest(MimallocSymbolCommand.Verify, "llvm-nm", "llvm-readobj", null, ["mimalloc object.obj"]);
    }

    private static ProcessResult ResultForVerifyRequest(
        ProcessRequest request,
        string externalOutput,
        string undefinedOutput,
        string rawOutput,
        string directiveOutput)
    {
        if (request.Arguments.Contains("--coff-directives"))
        {
            return new ProcessResult(0, directiveOutput, string.Empty);
        }

        if (request.Arguments.Contains("--undefined-only"))
        {
            return new ProcessResult(0, undefinedOutput, string.Empty);
        }

        if (request.Arguments.Contains("-j"))
        {
            return new ProcessResult(0, rawOutput, string.Empty);
        }

        return new ProcessResult(0, externalOutput, string.Empty);
    }

    private sealed class RecordingProcessRunner(Func<ProcessRequest, ProcessResult> resultFactory) : IProcessRunner
    {
        public List<ProcessRequest> Requests { get; } = [];

        public Task<ProcessResult> RunAsync(ProcessRequest request, CancellationToken cancellationToken)
        {
            Requests.Add(request);
            return Task.FromResult(resultFactory(request));
        }
    }

    private sealed class ThrowingProcessRunner(Exception exception) : IProcessRunner
    {
        public Task<ProcessResult> RunAsync(ProcessRequest request, CancellationToken cancellationToken)
        {
            throw exception;
        }
    }

    private sealed class TemporaryDirectory : IDisposable
    {
        public TemporaryDirectory()
        {
            Path = Directory.CreateTempSubdirectory("NativeBinaryTools Tests ").FullName;
        }

        public string Path { get; }

        public void Dispose()
        {
            Directory.Delete(Path, recursive: true);
        }
    }
}
