if(CMAKE_CXX_COMPILER_ID STREQUAL "MSVC" OR
   CMAKE_CXX_COMPILER_FRONTEND_VARIANT STREQUAL "MSVC")
  set(SANDBOX_MSVC_FRONTEND TRUE)
else()
  set(SANDBOX_MSVC_FRONTEND FALSE)
endif()
set(SANDBOX_MSVC_FRONTEND "${SANDBOX_MSVC_FRONTEND}" PARENT_SCOPE)

add_subdirectory(compiler_warnings)
add_subdirectory(compiler_options)
