include_guard(GLOBAL)

if(DEFINED CACHE{LLVM_ROOT})
  message(STATUS "Ignoring LLVM_ROOT cache entry; set the LLVM_ROOT environment variable instead.")
  unset(LLVM_ROOT CACHE)
endif()
if(DEFINED ENV{LLVM_ROOT} AND NOT "$ENV{LLVM_ROOT}" STREQUAL "")
  cmake_path(SET LLVM_ROOT NORMALIZE "$ENV{LLVM_ROOT}")
else()
  set(LLVM_ROOT "")
endif()

function(ioj_find_llvm_tool output)
  if(NOT LLVM_ROOT STREQUAL "")
    find_program(llvm_tool NAMES ${ARGN}
      PATHS "${LLVM_ROOT}/bin" NO_DEFAULT_PATH NO_CACHE REQUIRED)
  else()
    find_program(llvm_tool NAMES ${ARGN} NO_CACHE REQUIRED)
  endif()
  set(${output} "${llvm_tool}" CACHE INTERNAL "LLVM tool derived from LLVM_ROOT" FORCE)
  set(${output} "${llvm_tool}" PARENT_SCOPE)
endfunction()
