cmake_minimum_required(VERSION 4.4.2)

if(NOT DEFINED MACHINE_ACTIVITY_MODULE OR MACHINE_ACTIVITY_MODULE STREQUAL "")
  message(FATAL_ERROR "MACHINE_ACTIVITY_MODULE is required.")
endif()
include("${MACHINE_ACTIVITY_MODULE}")

if(DEFINED MACHINE_ACTIVITY_ACTION AND MACHINE_ACTIVITY_ACTION STREQUAL "status")
  sandbox_machine_activity_status()
  return()
endif()

if(NOT DEFINED MACHINE_ACTIVITY_MODE OR MACHINE_ACTIVITY_MODE STREQUAL "")
  message(FATAL_ERROR "MACHINE_ACTIVITY_MODE is required.")
endif()
if(NOT DEFINED MACHINE_ACTIVITY_OPERATION OR MACHINE_ACTIVITY_OPERATION STREQUAL "")
  set(MACHINE_ACTIVITY_OPERATION "command")
endif()

set(activity_command)
set(found_command_separator FALSE)
math(EXPR last_argument_index "${CMAKE_ARGC} - 1")
foreach(argument_index RANGE 0 ${last_argument_index})
  set(argument_variable "CMAKE_ARGV${argument_index}")
  set(argument "${${argument_variable}}")
  if(found_command_separator)
    string(REPLACE ";" "\\;" escaped_argument "${argument}")
    list(APPEND activity_command "${escaped_argument}")
  elseif(argument STREQUAL "--")
    set(found_command_separator TRUE)
  endif()
endforeach()
if(NOT found_command_separator OR NOT activity_command)
  message(FATAL_ERROR "A command must be supplied after '--'.")
endif()

if(DEFINED MACHINE_ACTIVITY_BYPASS_ARGUMENT AND
    NOT MACHINE_ACTIVITY_BYPASS_ARGUMENT STREQUAL "")
  list(FIND activity_command "${MACHINE_ACTIVITY_BYPASS_ARGUMENT}" bypass_index)
  if(NOT bypass_index EQUAL -1)
    execute_process(COMMAND ${activity_command} RESULT_VARIABLE command_result)
    if(NOT command_result MATCHES "^[0-9]+$")
      message(FATAL_ERROR "Failed to run bypassed command: ${command_result}")
    endif()
    if(NOT command_result EQUAL 0)
      cmake_language(EXIT "${command_result}")
    endif()
    return()
  endif()
endif()

sandbox_machine_activity_acquire(
  "${MACHINE_ACTIVITY_MODE}" "${MACHINE_ACTIVITY_OPERATION}")
execute_process(COMMAND ${activity_command} RESULT_VARIABLE command_result)
sandbox_machine_activity_release()

if(NOT command_result MATCHES "^[0-9]+$")
  message(FATAL_ERROR "Failed to run protected command: ${command_result}")
endif()
if(NOT command_result EQUAL 0)
  cmake_language(EXIT "${command_result}")
endif()
