include_guard(GLOBAL)

function(sandbox_resolve_unreal_root absolute_output canonical_output root base_directory)
  cmake_path(ABSOLUTE_PATH root BASE_DIRECTORY "${base_directory}" NORMALIZE
    OUTPUT_VARIABLE absolute_root)
  file(REAL_PATH "${absolute_root}" canonical_root)
  cmake_path(NORMAL_PATH canonical_root)
  set(${absolute_output} "${absolute_root}" PARENT_SCOPE)
  set(${canonical_output} "${canonical_root}" PARENT_SCOPE)
endfunction()

function(sandbox_get_unreal_editor_names editor_output editor_cmd_output configuration)
  if(configuration MATCHES "^(Debug|DebugGame|Development)$")
    set(editor_configuration "${configuration}")
  else()
    set(editor_configuration Development)
  endif()

  if(editor_configuration STREQUAL "Development")
    set(editor_name UnrealEditor.exe)
    set(editor_cmd_name UnrealEditor-Cmd.exe)
  else()
    set(editor_name "UnrealEditor-Win64-${editor_configuration}.exe")
    set(editor_cmd_name "UnrealEditor-Win64-${editor_configuration}-Cmd.exe")
  endif()

  set(${editor_output} "${editor_name}" PARENT_SCOPE)
  set(${editor_cmd_output} "${editor_cmd_name}" PARENT_SCOPE)
endfunction()

function(sandbox_configure_game_artifact_paths prefix artifact_root base_directory platform configuration)
  cmake_path(ABSOLUTE_PATH artifact_root BASE_DIRECTORY "${base_directory}" NORMALIZE
    OUTPUT_VARIABLE artifact_root_absolute)
  set(platform_root "${artifact_root_absolute}/${platform}")
  set(configuration_root "${platform_root}/${configuration}")
  set(${prefix}_ROOT "${artifact_root_absolute}" PARENT_SCOPE)
  set(${prefix}_COOK_ROOT "${platform_root}/cook" PARENT_SCOPE)
  set(${prefix}_COOK_DIRECTORY "${platform_root}/cook/Windows" PARENT_SCOPE)
  set(${prefix}_STAGE_ROOT "${configuration_root}/stage" PARENT_SCOPE)
  set(${prefix}_ARCHIVE_ROOT "${configuration_root}/archive" PARENT_SCOPE)
  set(${prefix}_STAGE_DIRECTORY "${configuration_root}/stage/Windows" PARENT_SCOPE)
  set(${prefix}_ARCHIVE_DIRECTORY "${configuration_root}/archive" PARENT_SCOPE)
  set(${prefix}_STAGE_EXECUTABLE "${configuration_root}/stage/Windows/Sandbox.exe" PARENT_SCOPE)
  set(${prefix}_VERIFICATION_ROOT "${configuration_root}/verification" PARENT_SCOPE)
endfunction()
