// This file is autogenerated. Do not edit by hand.
// Edit lispb/schema and regenerate it instead.

#pragma once

#include "CoreMinimal.h"
#include "ShipLaserMode.generated.h"
UENUM(BlueprintType)
enum class EShipLaserMode : uint8 {
    Single = 0 UMETA(DisplayName = "Single"),
    Double = 1 UMETA(DisplayName = "Double"),
    Hyper = 2 UMETA(DisplayName = "Hyper"),
};
