// clang-format off
// This file is autogenerated. Do not edit by hand.
// Edit lispb/schema and regenerate it instead.

#pragma once

#include "ioj/sim/entity_unique_id.h"
#include "ioj/sim/fighter_order_queue.h"
#include "ioj/sim/fighter_spawn_queue.h"
#include "ioj/sim/fighters/sim.h"
#include "ioj/sim/spawned_entity_handles.h"

namespace ioj::sim::fighters {
class CommandInterface {
    public:
    CommandInterface(Sim& new_target)
        : fighters{new_target} {

    }

    std::int32_t queue_spawns(FighterSpawnQueueConstView queue) {
        return fighters.queue_spawns(queue);
    }

    void queue_orders(FighterOrderQueue const& queue) {
        fighters.queue_orders(queue);
    }

    void self_destruct_fighter(EntityUniqueId const fighter) {
        fighters.self_destruct_fighter(fighter);
    }

    RegistryEntityDataConstView get_new_spawn_entity_data() const {
        return fighters.get_new_spawn_entity_data();
    }

    SpawnedEntityHandles const& get_new_spawn_entity_handles() const {
        return fighters.get_new_spawn_entity_handles();
    }

    std::int32_t get_num_instances() const noexcept {
        return fighters.get_num_instances();
    }

    std::span<EntityUniqueId const> get_parent_ids() const {
        return fighters.get_parent_ids();
    }

    std::span<EntityUniqueId const> get_entity_ids() const {
        return fighters.get_entity_ids();
    }

    std::span<Health const> get_healths() const {
        return fighters.get_healths();
    }

    void set_parent_id(EntityUniqueId fighter, EntityUniqueId parent) {
        fighters.set_parent_id(fighter, parent);
    }

    std::span<EntityUniqueId const> get_target_ids() const noexcept {
        return fighters.get_target_ids();
    }

    private:
    Sim& fighters;
};
} // namespace ioj::sim::fighters
// clang-format on
